### ISSUE TITLE
Feature: Allow umzug JSON storage

### ISSUE THREAD

**Issue by itoed** [sequelize/cli#101]
Hi folks,

I was looking at the [task that interfaces with umzug](https://github.com/sequelize/cli/blob/87b7b836b39ac7bda001f17f5e25f538e895c266/lib/tasks/db.js#L181) and I noticed the storage is hardcoded to Sequelize.

I have a requirement where the migrations tracking data cannot be on the database.  I'm now trying to use Umzug without the sequelize-cli.

So, it would be really nice if you could allow the option to configure umzug JSON storage.

Thank you!

**Comment by sdepold** [comment]
Hmmm..... Well.... That should be pretty easy. Would you like to provide a PR for that?

**Comment by itoed** [comment]
A PR has been created (#103).  Please let me know if there is anything else I can do so that sequelize cli can have this feature.

**Comment by sdepold** [comment]
this is done right?

**Comment by itoed** [comment]
Yes, everything seems fine with v1.4.0 now.  Thank you so much for all your help!
