### ISSUE TITLE
Unable to resolve sequelize package

### ISSUE THREAD

**Issue by the1corndog** [sequelize/cli#1056]
Was setting up a new project and giving the latest Sequelize (V7) a try (Knowing it's in alpha)

## What you are doing?
Using  to @sequelize/core to try it out. Tried to run `npx sequelize db:migrate` to populate new local dev environment
 
Package JSON dependencies:
```json
{
    "@sequelize/core": "^7.0.0-alpha.10",
    "cors": "^2.8.5",
    "express": "^4.17.3",
    "morgan": "^1.10.0",
    "pg": "^8.7.3",
    "pg-hstore": "^2.3.4",
    "sequelize-cli": "^6.4.1",
    "sqlite3": "github:mapbox/node-sqlite3#593c9d"
  }
```

Config file:
```json
{
  "development": {
    "dialect": "sqlite",
    "storage": "./db.sqlite"
  }
}

```

## What do you expect to happen?
Migrations to be ran and database setup.

## What is actually happening?
Terminal output from above command showed: `Unable to resolve sequelize package in <project path>`

__Dialect:__ postgres
__Database version:__ postgres docker image@latest
__Sequelize CLI version:__ 6.4.1
__Sequelize version:__ (Sequelize core)  v7 alpha 10

I'm fine with using the stable v6, not sure if this cli needs to be updated for v7 or not yet. Haven't seen anything in issue threads about it so if this is a dupe issue, my apologies

**Comment by the1corndog** [comment]
For others who are looking at this issue, what I did was this: 

`npm i --save sequelize@npm:@sequelize/core` which creates an alias as a temporary workaround - I am not sure what issues this may cause, but it's what I'm doing in my "playground" area

**Comment by Benandry** [comment]
Thanks @the1corndog
