### ISSUE TITLE
migration add column is creating camelcase columns instead of underscore

### ISSUE THREAD

**Issue by sayanee** [sequelize/cli#107]
I added a migration:

```
"use strict";

module.exports = {
  up: function(migration, DataTypes, done) {
    migration.addColumn('Machines', 'customerEmail', DataTypes.STRING);
    done();
  },

  down: function(migration, DataTypes, done) {
    migration.removeColumn('Machines', 'customerEmail');
    done();
  }
};
```

and subsequently in the model:

```
'use strict';

module.exports = function(sequelize, DataTypes) {
  var Machine = sequelize
    .define('Machine', {
      ...
      customerEmail: {
        field: 'customer_email',
        type: DataTypes.STRING
      }
      ...
      underscored: true
    });

  return Machine;
}
```

and migrated:

```
NODE_ENV=development sequelize db:migrate --config config/development.json
```

I'm using the following versions:

```
$ sequelize --version
Sequelize [Node: 1.4.3, CLI: 1.3.1, ORM: 2.0.4]

$ node --version
v1.4.3

$ postgres --version
postgres (PostgreSQL) 9.3.1
```

In the db, the column created is `customerEmail` instead of `customer_email`. How can I create an underscored column name? Thanks!

Previously, with `db.sequelize.sync({force: true})` I could create the underscore columns. But now I cannot drop the table anymore. Maybe i'm missing something else?

**Comment by sdepold** [comment]
This happens because of the following line in your migration:

migration.addColumn('Machines', 'customerEmail'

The second argument is the name of the column.

**Comment by sayanee** [comment]
thanks! will try with `migration.addColumn('Machines', 'customer_email'...`
