### ISSUE TITLE
/usr/bin/env: ‘bash\r’: No such file or directory

### ISSUE THREAD

**Issue by RenaudAubert** [sequelize/cli#1073]
## What you are doing?
Updated node to `16.14.2` and got this error `/usr/bin/env: ‘bash\r’: No such file or directory` when executing the command `npx sequelize db:migrate:undo:all` on WSL 2 Ubuntu version 20.04.

Reverted to node `16.14.0` and it works fine. 

## What do you expect to happen?
`npx sequelize db:migrate:undo:all` to succeed when using node `16.14.2`

## What is actually happening?
I get this error `/usr/bin/env: ‘bash\r’: No such file or directory`

**Comment by WikiRik** [comment]
Does this happen on Node 16.15.0 as well?

**Comment by WikiRik** [comment]
No worries, thanks for the quick response!
