### ISSUE TITLE
add db:seed

### ISSUE THREAD

**Issue by Americas** [sequelize/cli#109]
There already is an easy way to create table data. While developing, having a command ´db:seed´ that populates tables (à la artisan) is very useful.

**Comment by sdepold** [comment]
What would this task do in detail?

**Comment by Americas** [comment]
It would run just like a db:migrate, but it would populate tables (with fake data) instead of defining the database.
This needs to be separated form the migrations so that when running in dev or test environments, we can  rebuild the fake data to do tests. Since this data is not for production consumption, it cannot be a normal migration file, or it would disrupt the migration flow when in production.
I was checking the sequelize/umzug project, and maybe this request fits better there, since there is no support for this yet.

**Comment by sdepold** [comment]
Not necessarily. We could make the CLI call umzug while pointing umzug to a different directory which contains migrations which actually seed the content.

**Comment by ericrini** [comment]
We've just created a set of seed migrations in another folder and run them using the --migrations-path argument.
