### ISSUE TITLE
when migrate sequelize i get ERROR: Access denied for user 'root;'@'localhost' (using password: NO) 

### ISSUE THREAD

**Issue by PratamaRizki22** [sequelize/cli#1097]
## error when i run ./node_modules/.bin/sequelize-cli db:migrate in this database.js

```js
require("dotenv").config();
module.exports = {
  development: {
    username: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    host: process.env.BD_HOST,
    dialect: "mysql",
  },
  test: {
    username: "root",
    password: null,
    database: "database_test",
    host: "127.0.0.1",
    dialect: "mysql",
  },
  production: {
    username: "root",
    password: null,
    database: "database_production",
    host: "127.0.0.1",
    dialect: "mysql",
  },
};

```

## What do you expect to happen?
how to solve this?

## What is actually happening?
im now learning sequelize when i run ./node_modules/.bin/sequelize-cli db:migrate in this database.js but i get Sequelize CLI [Node: 16.14.0, CLI: 6.4.1, ORM: 6.20.0]   

Loaded configuration file "src\config\database.js".      
Using environment "development".      

ERROR: Access denied for user 'root;'@'localhost' (using password: NO)

**Comment by WikiRik** [comment]
This is not an issue with Sequelize CLI. The values you have set up in the environment variables are not correct
