### ISSUE TITLE
Faking migrations

### ISSUE THREAD

**Issue by FreakTheMighty** [sequelize/cli#116]
Hi there, I have a question. In a development environment where I drop my database then sync the db I find that my migrations fail due to fields already existing. 

I would like to a way to "fake" run the migration. Does a `--fake` option similar to django's South library exist http://south.readthedocs.org/en/latest/commands.html?

This would allow me to run `sequelize db:migrate` from the point where I last synced. Currently, I clear the contents of each migration, run the migrations, then continue on.

**Comment by sdepold** [comment]
Something like this does not exist by now. People are apparently interested in this feature though: https://github.com/sequelize/umzug/issues/25

It shouldn't be too hard to add this, but I'm currently a bit short on time. Therefore I would be more than happy to review a PR :D

**Comment by ustun** [comment]
Here is what I came up with, based on https://github.com/sequelize/umzug/issues/25#issuecomment-116432267

```
const {
  getMigrator,
  ensureCurrentMetaSchema
} = require('sequelize-cli/lib/core/migrator')


const { default: helpers } = require('sequelize-cli/lib/helpers')

async function fakeMigrations() {
  await helpers.config.init()
  getMigrator('migration').then(migrator => {
    return ensureCurrentMetaSchema(migrator)
      .then(() => migrator.pending())
      .then(async migrations => {
        console.log(migrations.length + ' pending migrations will be faked')

        for (const migration of migrations) {
          console.log('faking ' + migration.file)
          await migrator.storage.logMigration(migration.file)
        }

 
      })
  })
}

if (require.main === module) {
  fakeMigrations()
}



```
