### ISSUE TITLE
Logging parameter in config.json bug

### ISSUE THREAD

**Issue by ee99ee** [sequelize/cli#118]
- Setting `logging` to `false` in config.json disables logging, as expected. However, setting it to `true` throws an error shown below. You can't define a function in a json file, so you can't implement a custom logging handler nor set it to `console.log`.

`DEPRECATION WARNING: The logging-option should be either a function or false. Default: console.log`
- Omitting the logging value all together actually disables logging on the CLI, although the above message would make one think it will default to console.log.

**Comment by ericrini** [comment]
+1

**Comment by sdepold** [comment]
good point.

**Comment by benjhoo** [comment]
+1

**Comment by sdepold** [comment]
While this is more of a workaround than a fix for your problem: Update to the lastest version of the cli, rename the config file to `.js` and add a `module.export`. Now you can set it to `console.log`.

**Comment by golendukhin** [comment]
+1

**Comment by drewdotpro** [comment]
+1

**Comment by justechn** [comment]
I just ran into this problem. +1 from me as well

**Comment by benjhoo** [comment]
As @sdepold said, you just need to export your conf as javascript : 
`module.exports = {
    database: {
        host: "",
        port: "",
        ...,
        logging: console.log
    }
}`

**Comment by justechn** [comment]
He also said "this is more of a workaround than a fix for your problem"

**Comment by dgobaud** [comment]
+1

**Comment by sushantdhiman** [comment]
Closing (Issue Cleanup), Please comment if you want to keep it open

**Comment by martijnhiemstra** [comment]
I use this line of code to enable / disable according to environment:

    logging: (process.env.NODE_ENV !== 'production' ? console.log : null)
