### ISSUE TITLE
Migration with typescript file not working => ERROR: Unexpected token

### ISSUE THREAD

**Issue by ks-krimi** [sequelize/cli#1222]
## What you are doing?

I changed 20221222130619-create-test.js to 20221222130619-create-test.ts

```ts
// 20221222130619-create-test.ts
import { DataTypes, QueryInterface } from 'sequelize';

export async function up(queryInterface: QueryInterface, Sequelize: typeof DataTypes) {
  await queryInterface.createTable('test', {
    id: {
      type: Sequelize.INTEGER,
      allowNull: false,
      autoIncrement: true,
      primaryKey: true,
    },
    createdAt: {
      allowNull: false,
      type: Sequelize.DATE,
    },
    updatedAt: {
      allowNull: false,
      type: Sequelize.DATE,
    },
  });
}
export function down(queryInterface: QueryInterface, _Sequelize: typeof DataTypes) {
  return queryInterface.dropTable('test');
}

```
After, run 
```js
npx sequelize-cli db:migrate
```

## What do you expect to happen?
Executing (default): INSERT INTO "SequelizeMeta" ("name") VALUES ($1) RETURNING "name";
== 20221222130619-create-test: migrated (0.422s)

## What is actually happening?
Executing (default): SELECT "name" FROM "SequelizeMeta" AS "SequelizeMeta" ORDER BY "SequelizeMeta"."name" ASC;
== 20221222130619-create-test: migrating =======

ERROR: /workspace/sequelize-project/migrations/20221222130619-create-test.ts: Unexpected token, expected , (1:39)
sequelize-cli db:migrate

__Dialect:__ postgres 
__Database version:__ 15.1 (Debian 15.1-1.pgdg110+1)
__Sequelize CLI version:__ 6.5.2
__Sequelize version:__ 6.26.0

**Comment by WikiRik** [comment]
v6 currently does not support migration files in TypeScript. You can use either regular JS files or use the transpiled version of the TS file in migration. This support will be added in v7. We're tracking this in #693

**Comment by ks-krimi** [comment]
@WikiRik Thank you 👍🏾
