### ISSUE TITLE
Custom Templates

### ISSUE THREAD

**Issue by kevinawoo** [sequelize/cli#125]
Is anyone interested in having a custom skeleton that the file path can be provided by config file?

I'm thinking of having it similar to [Example for a Node.JS script](https://github.com/sequelize/cli#example-for-a-nodejs-script):
```js
module.exports = {
  'skeleton-path': path.resolve('config', 'custom_skeleton.js')
}
```

**Comment by sdepold** [comment]
That is a great idea. I would highly recommend the wording template though. Where would you put that configuration? as an option to the CLI and/or via the .sequelizerc ?

**Comment by kevinawoo** [comment]
No problem, and I agree! I was just following what I found in the code.

I think most use cases are just `sequelize foo`, so a CLI option wouldn't be too useful, but a welcomed addition.

`.sequelizerc` would be the ideal place for a custom template path. 

That is, unless you you're thinking about having the template to be created with `sequelize init` and defaultly reference the project's template. If that's the case maybe a `migrations/.template.js` might be a good choice?

Developers can either manually copy, or `sequelize migration:create` generates it for them.

**Comment by sdepold** [comment]
Hi @kevinawoo, 

sorry for the delay. While I think this could be potentially an interesting feature, I wonder if isn't too error prone. I mean the actual template looks pretty awkward and I'm not sure if anyone will be happy touching it. On the other hand, we could add a task that puts the template to specific place (which is defined by the user) and let the user modify that thing afterwards plus making the migrations-template property point to the new template file. I wouldn't copy the file by default to the user land though. Additionally I would call the template config property `migrations-template-path`, I guess :)

**Comment by kevinawoo** [comment]
I like that!

I wasn't sure, did you want me to work on it also?

I can fork the repo, and add you as a contributor, so we can work on the same branch `feature/migrations-templates`, then submit a PR/merge when completed. (I found Pull Requests for new features seem have a bit too much back and forth asking for changes)

**Comment by brad-decker** [comment]
I implemented a simpler approach by just allowing the creation of a skeleton.js file in the pre-generated folders (seeders/ migrations/). See #183

**Comment by sdepold** [comment]
I think the approach from @brad-decker is promising. We just have to make add the last bits and pieces to the PR :)

**Comment by kevinawoo** [comment]
closing, opting for #183
Thanks @brad-decker!
