### ISSUE TITLE
syncing model in migration

### ISSUE THREAD

**Issue by Olgagr** [sequelize/cli#128]
I'd like to ask can I run model sync in migration? I have such migration:

```
'use strict'
db = require './../src/db'

module.exports =
  up: (queryInterface, Sequelize) ->

    return db.model('user').sync({ force: true })

  down: (queryInterface, Sequelize) ->

    return queryInterface.dropTable('users');
```

And I run migration:

```
NODE_ENV=test ./node_modules/sequelize-cli/bin/sequelize db:migrate --coffee
```

My config.json file is:
```
{
  "development": {
    "username": "postgres",
    "password": null,
    "database": "trh_development",
    "host": "127.0.0.1",
    "dialect": "postgresql",
    "migrationStorageTableName": "sequelize_meta"
  },
  "test": {
    "username": "postgres",
    "password": null,
    "database": "trh_test",
    "host": "127.0.0.1",
    "dialect": "postgresql",
    "migrationStorageTableName": "sequelize_meta"
  }
}
```
It seems like the migration is messing databases. It writes into correct sequelize_meta (in the thr_test db) but the users table is created in trh_development db. Can I use db.model('user').sync({ force: true }) in migrations ? I can use in migration: 

```
queryInterface.createTable 'users', { #all attributes }
```
but it have to repeat all data I have already defined in the model. I'm curious how do you deal with that.

**Comment by Olgagr** [comment]
Well, I response my own question. It was my fault :) The db url is taken from .env file and in this .env file I have url to development db. That's why the db's were messed. To sum up: this is possible to sync the model in the migration.

**Comment by amirklick** [comment]
@Olgagr Can you share your db file content? I'm using ES6 in my project and am having issues importing my models to use sync. Thanks
