### ISSUE TITLE
use_env_variable returns undefined because not string value

### ISSUE THREAD

**Issue by kzunino** [sequelize/cli#1322]
**What you are doing?**
I am trying to deploy a PERN app to Heroku using sequelize. When I configure my production settings in the config.js file as per sequelize-CLI docs I am throwing an error:

``` 

internal/validators.js:107
 throw new ERR_INVALID_ARG_TYPE(name, 'string', value);

 TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
at validateString (internal/validators.js:107:11)
at Url.parse (url.js:155:3)
at Object.urlParse [as parse] (url.js:150:13)
at new Sequelize (/app/node_modules/sequelize/lib/sequelize.js:187:28)
at Object.<anonymous> (/app/models/index.js:14:15) 

```

**Post a minimal code sample that reproduces the issue, including models and associations**
```
production: {
    use_env_variable: process.env.DATABASE_URL,
    dialect: 'postgres',
    dialectOptions: {
      ssl: {
        require: true,
        rejectUnauthorized: false, // <<<<<<< YOU NEED THIS TO FIX UNHANDLED REJECTION 
      },
    },
  },
```
**What do you expect to happen?**
I expect the environment variable, which is effectively a URI connection string to the postgress database add-on in Heroku to parse the string.

**What is actually happening?**
What is happening is that use_env_variable is being send as an argument to `/app/node_modules/sequelize/lib/sequelize.js:187:28` and inside this module it is passed as an object, not a string. Below is a snippet of the module where the problem occurs. `url.parse(options[0])` expects to accept a string as an argument and is instead given an object which is undefined. If i modify this snippet to accept the value as per the documentation like this `const urlParts = url.parse(options.use_env_variable, true);` I don't seem to run into the same error again. I get an error about the SSL, which I fixed from an earlier bug report by changing my production figuration.

```
constructor(database, username, password, options) {
    let config;

    if (arguments.length === 1 && typeof database === 'object') {
      // new Sequelize({ ... options })
      options = database;
      config = _.pick(options, 'host', 'port', 'database', 'username', 'password');
    } else if (
      (arguments.length === 1 && typeof database === 'string') ||
      (arguments.length === 2 && typeof username === 'object')
    ) {
      // new Sequelize(URI, { ... options })

      config = {};
      options = username || {};

      // url.parse wants to access the object like an array, however, first item is always undefined and it 
      // needs to access the use_env_variable, which is attached to username argument
     // const urlParts = url.parse(options.use_env_variable, true);

      const urlParts = url.parse(arguments[0], true);

      options.dialect = urlParts.protocol.replace(/:$/, '');
      options.host = urlParts.hostname;
```

Which dialect you are using (postgres, mysql etc)?
**Which sequelize version you are using?**
```
    "node": ^12.0.0
    "sequelize": "^5.21.11",
    "sequelize-cli": "^5.5.1"
```

**Comment by sreeparnadas** [comment]
> I found the solution to this stackoverflow question at https://stackoverflow.com/questions/49988002/getting-error-error-parsing-url-undefined-when-trying-to-run-migrations-with-s. In short, the `.env` file is not being loaded correctly by `sequelize`. To fix this issue, create a file in the root folder called `.sequelizerc`. Then, inside this file, add the following code. I changed it back to `json` because the original stackoverflow post was using a `js` file in the `config` folder.
> 
> ```js
> // .sequelizerc
> require("dotenv").config(); // <- require this here
> 
> // ...Any aditional configuration for sequelize-cli like custom folders for models and migrations
> const path = require("path");
> module.exports = {
>   config: path.resolve("config", "config.json"),
>   "models-path": path.resolve("models"),
>   "seeders-path": path.resolve("seeders"),
>   "migrations-path": path.resolve("migrations"),
> };
> ```

Thank you so much. It worked for me. I was struggling last 2 days for this issue.

**Comment by sreeparnadas** [comment]
@Juan321654 Thank you so much..
