### ISSUE TITLE
Document use_env_variable and database.json

### ISSUE THREAD

**Issue by vikeen** [sequelize/cli#135]
Environment variables appear to be supported, but I was unable to find anything in the documentation and just happened to be searching issues and saw another example. This should be far easier to find in my opinion. On this note the entire database.json should be documented

```json
  "production": {
    "use_env_variable": "PRODUCTION_ENV_DATABASE_URL"
  }
}
```

The CLI is a great feature and the help sections are very good, but again I came up empty here.
```bash
$ sequelize help:init:config

Sequelize [Node: 0.10.30, CLI: 1.7.0, ORM: 2.1.3]

Loaded configuration file "server/config/database.json".
Using environment "development".
COMMANDS
    sequelize init:config -- Initializes the configuration.

DESCRIPTION
    Initializes the configuration.

OPTIONS
    --env              The environment to run the command in. Default: development
    --coffee           Enables coffee script support. Default: false
    --config           The path to the config file. Default: config/config.json
    --options-path     The path to a JSON file with additional options. Default: none
    --migrations-path  The path to the migrations folder. Default: migrations
    --models-path      The path to the models folder.Default: models
```

**Comment by MrOrz** [comment]
+1 for this.

**Comment by JHouk** [comment]
Agreed. Current documentation implies putting passwords in source control. Better to demonstrate how to pull passwords from the environment.

**Comment by sdepold** [comment]
@vikeen @MrOrz @JHouk Want to review the #149 ?

**Comment by sdepold** [comment]
Just released a new version (which fixes usage of use_env_variable for SQLite)
