### ISSUE TITLE
Postgres Schemas 

### ISSUE THREAD

**Issue by grindfuk** [sequelize/cli#141]
Hi. Was wondering if the cli-tool can migrate tables under specific PostgreSQL schemas? Sorry if this is too dialect specific but I couldn't find it in the documentation. I have used sequelize to add schemas to my models but I'm not sure how I should migrate the table outside of using straight SQL.

**Comment by milovanderlinden** [comment]
As far as I can see, it cannot at the moment.

This is my migration on a postgres database:
```sql
'use strict';
module.exports = {
    up: function (queryInterface, Sequelize) {
        return queryInterface.createSchema('foo');
        return queryInterface.createTable('Sites', {
            id: Sequelize.INTEGER,
            title: Sequelize.STRING
         }, {
            schema: 'foo'
         });
    },
    down: function (queryInterface) {
       return queryInterface.dropTable('Sites',{schema: 'foo'});
       return queryInterface.dropSchema('foo');
    }
};
```
It gives no errors, it up's and down's the schema, but the table is not created.

However, when my model is this:
```javascript
module.exports = function (sequelize, DataTypes) {
    var Site = sequelize.define("Site", {
        title: DataTypes.STRING
    }, {
        schema: 'foo'
    });
    return Site;
};
```

And I use sync, the table is created correctly in the schema. As the output from my express app is:
```sql
CREATE TABLE IF NOT EXISTS "foo"."Sites" ("id"   SERIAL , "title" VARCHAR(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
```
```sql
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND a.attnum = ANY(ix.indkey) AND t.relkind = 'r' and t.relname = 'Sites' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
```
```
Running in development mode, listening on port 3000...
```
And a look at the postgres db shows it is created.

**Comment by gonzobrandon** [comment]
@milovanderlinden once the up function hits its first `return ...` it wont run anything underneath it.
 If you are trying to run multiple promises...I ended up chaining `createTables` with .then().

```
return queryInterface.createTable('foo').then(
        queryInterface.createTable('Sites', {
            id: Sequelize.INTEGER,
            title: Sequelize.STRING
         }, {
            schema: 'foo'
         });
    );
```
Unless i'm missing something, it seems the authors of sequelize prefer the design pattern of one migration file per table/command? (I dont like it) I have always thought a migration action item (a single migration file with a date in the filename) is a batch of DB commands.

**Comment by milovanderlinden** [comment]
Thanks @gonzobrandon going to give it a spin!

**Comment by grindfuk** [comment]
Thanks for confirming my suspicion. I like the migration tool so I just used a straight up query string. Not the most elegant way but it gets the job done.

**Comment by jonnolen** [comment]
See these pull requests:  #207 and #205  this allows you to specify a schema for migration tracking table as well as a schema for any model  you create. #205 has a dependency on sequelize/umzug#34.

If you use this branch of this fork git@github.com:jonnolen/cli.git#becks_rollup (in your package.json it would look like this: `"sequelize-cli": "git://github.com/jonnolen/cli.git#becks_rollup"`, you'll get all of our changes related to schema work (until the pr's get resolved).

**Comment by sushantdhiman** [comment]
Moved to https://github.com/sequelize/cli/issues/265
