### ISSUE TITLE
Sequelize message "is not in your gulpfile" 

### ISSUE THREAD

**Issue by brunosiqueira** [sequelize/cli#143]
I'm running the following command: sequelize migration:create addNewadmintovideos

And I'm getting this output:

Sequelize [Node: 0.12.3, CLI: 1.7.0, ORM: 3.3.1]

Loaded configuration file "config/config.json".
Using environment "development".
Using gulpfile /usr/local/lib/node_modules/sequelize-cli/lib/gulpfile.js
Task 'addNewAdminToVideos' is not in your gulpfile

**Comment by sdepold** [comment]
Please try migration:create --name <yourname>

**Comment by brunosiqueira** [comment]
Thank you, @sdepold. Sorry for the "did not read the help doc" question.
