### ISSUE TITLE
Model index CoffeeScript translation broken?

### ISSUE THREAD

**Issue by tylerFowler** [sequelize/cli#144]
Recently I switched my project from using migrations to using the `sync()` function so that I could take advantage of associations. So I used the models generated from the CLI with the CoffeeScript options, and found that none of my `associate` class methods were being called.

The offending (generated) code in the `index.coffee` file was:
```coffeescript
Object.keys(db).forEach (modelName) ->
  if 'associate' in db[modelName]
    db[modelName].associate db
  return
```

In each model the inner 'if' condition was failing completely. Changing the code to:
```coffeescript
Object.keys(db).forEach (modelName) ->
  db[modelName].associate db if db[modelName].associate
```

fixed the issue entirely.

**Comment by sdepold** [comment]
hmmm lets see why this is

**Comment by sdepold** [comment]
The generated file should be better now.

**Comment by tylerFowler** [comment]
Great, thanks!
