### ISSUE TITLE
Sequelize DB Sync

### ISSUE THREAD

**Issue by zeeshanjan82** [sequelize/cli#151]
I have few questions around the sync functinality using sequelize. As I understand sequelize-cli uses Umzug internally for doing all the migrations.What is the procedure for Alter Table, suppose I would like to alter the model in sequelize and let sequelize cli create the migration script for me , how can sequelize cli create the migration script by going through all the model changes or do I have to create the migration scripts myself.

**Comment by sdepold** [comment]
You currently have to create the migration manually yourself.
