### ISSUE TITLE
db:migrate:old_schema broken since sequelize version 3.0.0

### ISSUE THREAD

**Issue by peterjwest** [sequelize/cli#152]
This command relies on `sequelize.query` (`/lib/tasks/db.js:273`) which was changed in sequelize 3.0.0

**Comment by sdepold** [comment]
thanks for the heads up

**Comment by rjmunro** [comment]
So I guess the workaround is to upgrade to umzug before you upgrade sequelize?

**Comment by sdepold** [comment]
I will fix the actual problem today ig guess

**Comment by peterjwest** [comment]
@rjmunro yes, that would work

**Comment by sdepold** [comment]
#153 will fix this issue

**Comment by sdepold** [comment]
Just released version v1.7.2 of the CLI. Please check if it is working properly now :)

**Comment by peterjwest** [comment]
Works perfectly,  you're :star2:THE BEST:star2:

**Comment by sdepold** [comment]
great :+1:
