### ISSUE TITLE
How do I run the migration with SSL enabled?

### ISSUE THREAD

**Issue by STRd6** [sequelize/cli#154]
I'm trying to run a migration on a remote postgres host that requires SSL, passing `--url=...` on the command line. How do I enable SSL?

**Comment by dmcquay** [comment]
I have the same question, but I am using the config file. I added "ssl": true, but it still does not connect via SSL.

**Comment by ben-ng** [comment]
+1

**Comment by ryanwalters** [comment]
+1

**Comment by sdepold** [comment]
Hm I have a bit of hard times to answer this question, as I don't have an SSL enabled endpoint available.

**Comment by ryanwalters** [comment]
You can spin one up for free on Heroku.

**Comment by sdepold** [comment]
:cool: Will try to do that ASAP (which is probably one evening during this week)

**Comment by ryanwalters** [comment]
The SSL Heroku connection string looks something like:

    postgres://username:password@ec2-12-34-56-78.compute-1.amazonaws.com:5432/database?ssl=true

The `?ssl=true` comes from [Heroku's Docs](https://devcenter.heroku.com/articles/heroku-postgresql#connecting-in-node-js). It is required when connecting remotely.

So back to `sequelize`, I try to pass this value into `--url=...`, including `?ssl=true` and I get an error like:

    Unable to connect to database: SequelizeConnectionError: no pg_hba.conf entry for host "12.34.56.78", user "username", database "database?ssl=true", SSL off

You'll notice that the database value that is being parsed **includes the query parameter `?ssl=true`** and **SSL is not being enabled**.

Digging in a little bit, I see that [`urlStringToConfigHash`](https://github.com/sequelize/cli/blob/master/lib/helpers/config-helper.js#L139-L160) ignores the query string.

It seems like two things might help here:

1. Remove query string from database
1. If `ssl=true` is being passed, enable it

        // Tried this just for testing, and it doesn't work. How do we enable SSL?
        if (urlParts.query) {
            result = _.assign(result, {
                ssl: true
            });
        }

Any thoughts?

**Comment by icemilo** [comment]
My PR has been merged, could you test if specifying dialectOptions will work for postgres?

**Comment by jfishman** [comment]
:warning: The dialectOptions PR #220 allows users to specify the requisite ssl options, fulfilling this issue as far as the ssl feature request component, but the `--url` parameter parsing is still broken.  A flag named '--url' is reasonably expected to support valid URL forms, with or without query parameters. The database component is specified by the URI path, not including any part of the query.

It is unfortunate that node's url.parse incorrectly ambiguates the path component with the query component, and thus does not conform to [RFC3986](https://tools.ietf.org/html/rfc3986) terminology \[1]. As such, [urlStringToConfigHash](https://github.com/sequelize/cli/blob/master/lib/helpers/config-helper.js#L148) should apparently be using the `urlParts.pathname` field, not `urlParts.path`, a fairly understandable mistake.

\[1] "The path is terminated by the first question mark ("?") or number sign ("#") character, or by the end of the URI."

**Comment by joshuakarjala** [comment]
@gofish could you please give an example of how you solve this issue using `dialectOptions` for postgres.

**Comment by gofish** [comment]
@joshuakarjala You need to use a config file and specify "dialectOptions" with an "[ssl](https://github.com/sequelize/sequelize/blob/b8e24d0c3d35503039efe4bb1a4feff3a9146f6a/lib/dialects/postgres/connection-manager.js#L65)" entry.

Example:
```json
{
  "url": "postgres://localhost/database",
  "dialectOptions": {
    "ssl": {
      "ca": "path/to/ca.crt"
    }
}
```

The default config file is "config/config.json" (or config/config.js).  Specify an alternative using --config .

**Comment by joshuakarjala** [comment]
Got it to work by doing:

```json

{
   "use_env_variable":"DB_CONNECTION_STRING",
   "dialect":"postgres",
   "ssl":true,
   "dialectOptions":{
      "ssl":{
         "require":true
      }
   }
}
```

Still would be much appreciated if ?ssl=true as part of the URL was supported

**Comment by andrest** [comment]
```
{
  username: dbInfo.username,
  password: dbInfo.password,
  database: dbInfo.name,
  host: dbInfo.host,
  logging: false,
  ssl: true,
  dialect: dbInfo.dialect,
  dialectOptions: {
     ssl: {
        require: true
     }
  }
};
```
Migrations on a fresh database on Heroku (Postgres 9.5) returns:
```
Starting 'db:migrate'...
Finished 'db:migrate' after 55 ms
No migrations were executed, database schema was already up to date.
```

**Comment by sushantdhiman** [comment]
Added @joshuakarjala comment into docs https://github.com/sequelize/cli/tree/master/docs#configuration-for-connecting-over-ssl

**Comment by ivanlebed** [comment]
This seems to have slightly different information https://github.com/sequelize/cli/tree/master/docs#dialect-specific-options

**Comment by RedJanvier** [comment]
> 
> 
> Got it to work by doing:
> 
> ```json
> {
>    "use_env_variable":"DB_CONNECTION_STRING",
>    "dialect":"postgres",
>    "ssl":true,
>    "dialectOptions":{
>       "ssl":{
>          "require":true
>       }
>    }
> }
> ```
> 
> Still would be much appreciated if `?ssl=true` as part of the URL was supported

Thank you! I had an issue that the certificate was self-signed which was resolved by adding `rejectUnauthorized: false` to the `dialectOptions` as follows:

```json

{
   "use_env_variable":"DB_CONNECTION_STRING",
   "dialect":"postgres",
   "ssl":true,
   "dialectOptions":{
      "ssl":{
         "require":true
        "rejectUnauthorized": false
      }
   }
}

```

**Comment by decompil3d** [comment]
For anyone else who comes across this issue and, despite setting the `ssl` fields as above is still seeing problems, check if you have a `url` field specified either on the command line or in your `.sequelizerc` file. Sequelize seems to skip loading the config file if you've specified `url`. Just removing the `url` field from `.sequelizerc` and instead specifying it in your config file itself can make the difference to ensure that these SSL fields are actually respected.
