### ISSUE TITLE
Specify array type with model:create

### ISSUE THREAD

**Issue by sdroadie** [sequelize/cli#155]
As far as I can tell, there is no way to assign types to arrays using model:create. The syntax could be pretty simple: `sequelize model create --name Model --attributes 'info:array:string'`. Currently, this will pass, but just create an attribute that is an Array type. Without a type specified for the array, however, `db:migrate` fails.

Sorry if there is already a means for doing this: if so, I didn't see it after perusing the codebase.

**Comment by sdepold** [comment]
Yeah you are right. There is currently no way of doing this. Want to give it a try?

**Comment by link-alex** [comment]
Looks like this issue is still valid so I gave it a try :blush:

**Comment by link-alex** [comment]
Ok, so I forgot that String.prototype.includes appeared in node v6, so will update to support node v4+

**Comment by sushantdhiman** [comment]
Added by https://github.com/sequelize/cli/pull/589, Thanks @link-alex

**Comment by CognitiveClouds-Prasad** [comment]
So, how can I use this in sequelize cli? I am not able to migrate. There is no documentation I could find after about 3 hours of search.

**Comment by ccemeraldeyes** [comment]
> There is no documentation I could find after about 3 hours of search.

yeah guys the docs for the cli are impossible to find pls fix

**Comment by JoeRoddy** [comment]
For anyone stuck on this, the syntax is like:
`npx sequelize-cli model:generate --name Player --attributes favoriteColors:array:string`

^docs would be great for this!
