### ISSUE TITLE
db:migrate:undo running the wrong migration

### ISSUE THREAD

**Issue by richmarr** [sequelize/cli#156]
Great library, been using it a lot over the last few weeks. Have a hiccup now though:

My `SequelizeMeta` table ends with the following 3 entries, which is what I'd expect:

```
...
20150710144239-create-user.js
20150715175738-user-registration.js
20150716223356-remove-old-answers.js
```

I want to undo the last one, because I'm still working on it, but running `sequelize db:migrate:undo` causes an error, because it's running the last-but-two migration rather than the last.

```
== 20150710144239-create-user: reverting =======
Unhandled rejection SequelizeDatabaseError: cannot drop table "Users" because other objects depend on it
```

Looking at the code it's not clear whether the `migrations` array should come back from `umzug` already in the correct order. Inspecting it shows that it's only _mostly_ sorted, and that the incorrectly running migration is incorrectly at the end of the list.

The order is: `[ 0, 1, 2, 3, 14, 15, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ]` with just two elements out of place. See below for more detail on the contents of the array.

Has anyone seen this before? I normally assume user error but I'm not sure in this case. Is it an `umzug` bug?

versions: `Sequelize [Node: 0.12.2, CLI: 1.7.0, ORM: 3.2.0]`

In case it's relevant, the (trimmed) contents of the migrations array look like this:

```
[
    { ... }, // correct order
    { ... }, // correct order
    { ... }, // correct order
    {
        path: '/Users/rich/Projects/bit-jobs/20150701123620-create-org.js',
        file: '20150701123620-create-org.js'    // correct order
    },
    {
        path: '/Users/rich/Projects/bit-jobs/20150715175738-user-registration.js',
        file: '20150715175738-user-registration.js'    // should be second-last
    },
    {
        path: '/Users/rich/Projects/bit-jobs/20150716223356-remove-old-answers.js',
        file: '20150716223356-remove-old-answers.js'    // should be last
    },
    {
        path: '/Users/rich/Projects/bit-jobs/20150701231506-job-org-field.js',
        file: '20150701231506-job-org-field.js'    // correct order
    }, 
    { ... }, // correct order
    { ... }, // correct order
    { ... }, // correct order
    { ... }, // correct order
    { ... }, // correct order
    { ... }, // correct order
    { ... }, // correct order
    { ... }, // correct order
    { ... }, // correct order
    {
        path: '/Users/rich/Projects/bit-jobs/20150710144239-create-user.js',
        file: '20150710144239-create-user.js'
    }
]
```

**Comment by richmarr** [comment]
I dropped all my tables and built the DB again from scratch, and that worked for a couple of months, but now it seems to have got itself into this state again. 

`db:migrate:undo` seems to undo the 2nd-from-last script in my `SequelizeMeta` table rather than the last one.

I'm guessing there must be some kind of cache or state stored somewhere? The `SequelizeMeta` table is correct.

**Comment by sdepold** [comment]
That's super weird. Maybe it has to do something with the timestamps of the files. Did you find any reproducable pattern?

**Comment by richmarr** [comment]
Thanks for taking the time to read my incomprehensible bug report.

Agreed, really weird. Not sure if it's a coincidence that it's ignoring the
last two migrations on both of the occasions I've seen this.

If it manages to get into that state again I'll try and make time to dig
into it properly.



On Wednesday, 30 September 2015, Sascha Depold <notifications@github.com>
wrote:

> That's super weird. Maybe it has to do something with the timestamps of
> the files. Did you find any reproducable pattern?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sequelize/cli/issues/156#issuecomment-144390256>.
>


-- 
Richard Marr

**Comment by shawnbissell** [comment]
This just happened to me as well on my dev system. Was working great for months then just today the 4 new migrations seems to have been added to top of the SequelizeMeta table so when I did an db:migrate:undo it undid the wrong migrations. I had to wipe the DB and start again ... hopefully this doesn't happen on my staging server :(

@sdepold when you said "timestamps" you meant the first part of the name of the migration (ie 20150623152211-create-user.js) and not the actual "Date Created" or "Date Modified" reported by the OS right?

**Comment by sdepold** [comment]
Yeah it should order by the first part of the file name.

**Comment by sdepold** [comment]
@shawnbissell Could you post the names of our migrations? Also do you know the names of those 4 migrations?

**Comment by shawnbissell** [comment]
Yes the 4 new migrations that were out of order were
20151019122752-create-test-definition.js
20151019122805-create-task-definition.js
20151019122823-create-tdss.js
20151019122836-create-tdm.js
In my case these items somehow ended up at the top of the SequelizeMeta table (but not on the filesystem) so the undo was applying to the wrong migrations.

**Comment by richmarr** [comment]
Mine appears to have corrupted itself again. I have 78 migration files, all of which are in `SequelizeMeta` yet when I run `sequelize db:migrate:undo` it reverts the 62nd one. It's 62nd in both the  `SequelizeMeta` table and in the file system, and the LastModified date is also sequential, at least for that file and its neighbours. File system permissions are all consistent. 

Any suggestion where to start digging?

**Comment by sdepold** [comment]
Can you ensure that the order of the files is correct here https://github.com/sequelize/umzug/blob/master/index.js#L284 ? Also here? https://github.com/sequelize/umzug/blob/master/index.js#L50

**Comment by sushantdhiman** [comment]
Closing (Issue Cleanup), Please comment if you want to keep it open

**Comment by talibasya** [comment]
still exists with version 4.0.0 (@sushantdhiman it's for you to open issue ❤️ )

**Comment by krfong916** [comment]
Had this problem today.
