### ISSUE TITLE
migration:create to produce a complete migration file like sequelize-cmd

### ISSUE THREAD

**Issue by ivanmanolov90** [sequelize/cli#158]
I was watching the sequelize-cli video on youtube (https://www.youtube.com/watch?v=wHTBxtk8ezo) and found that the sequelize-cmd tool was able to determine the when the  models have been changed since last migration and create a complete migration file with the "addMigration" command  as shown below.
![image](https://cloud.githubusercontent.com/assets/6089500/8836419/d0a65eac-308e-11e5-961c-db94c2878f0a.png)

Sequelize-cli "migration:create" command just creates the skeleton of the file to my understanding. Is there a way to auto generate the whole migration file and not just the skeleton or can this feature be included ?

**Comment by jsumners** [comment]
See #157

**Comment by ivanmanolov90** [comment]
thank you :+1:

**Comment by SumanBandopadhyay** [comment]
In the video, it suggests that we should use sequelize-cli for production. But, we are not able to resolve the issue of migration recreate for a model change in there. Could you please suggest the best practice to implement?
