### ISSUE TITLE
Possible to check for pending migrations on startup?

### ISSUE THREAD

**Issue by derekscruggs** [sequelize/cli#165]
This isn't really an issue per se but I didn't see another forum for it.

Is it possible to configure Sequelize to check for pending migrations on startup? We've had numerous cases where devs forget to run migrations and proceed to chase their tails trying to figure out why their code suddenly stopped working.

**Comment by sdepold** [comment]
This is currently not possible but PRs are more than welcome.

**Comment by ShaharHD** [comment]
Use umzug in your code https://github.com/sequelize/umzug
I'm actually using umzug and not sequelize-cli for the automatic migrations

**Comment by sushantdhiman** [comment]
Fixed in https://github.com/sequelize/cli/pull/385

`sequelize db:migrate:status`
