### ISSUE TITLE
use_env_variable doesn't work in model

### ISSUE THREAD

**Issue by itslenny** [sequelize/cli#168]
When setting up a sequelize app for production I tried using `use_env_variable` as directed in the readme.md, but based on the models/index.js (generated by sequelize-cli) I don't see any way this could work.

I needed to add in the following block of code to make it work. Is there something I'm missing? If not I'll gladly do a pull request with this block of code which will make it work out of the box.

**Relevant portion of `models/index.js`:**
```
var env       = process.env.NODE_ENV || 'development';
var config    = require(__dirname + '/../config/config.json')[env];

/////// ADDED TO PARSE CONNECTION STRING IN TO COMPONENTS /////
if(config.use_env_variable){
  var db_info = process.env[config.use_env_variable].match(/([^:]+):\/\/([^:]+):([^@]+)@([^:]+):(\d+)\/(.+)/);
  config.dialect=db_info[1];
  config.username=db_info[2];
  config.password=db_info[3];
  config.host=db_info[4];
  config.port=db_info[5];
  config.database=db_info[6];
}
/////////////////////////////////////

var sequelize = new Sequelize(config.database, config.username, config.password, config);
```

**Comment by itslenny** [comment]
I didn't realize Sequelize could process a url directly. This is a slightly more elegant solution.

```
if(config.use_env_variable){
  var sequelize = new Sequelize(process.env[config.use_env_variable]);
}else{
  var sequelize = new Sequelize(config.database, config.username, config.password, config);
}
```

**Comment by sdepold** [comment]
Looks good. Want to provide a PR ?

**Comment by sdepold** [comment]
ah you did already :)

**Comment by whisher** [comment]
Hi,
sorry to bother you but I've got a problem to run migration in heroku.

>heroku addons:create heroku-postgresql:hobby-dev
>Creating postgresql-octagonal-XXXX... done, (free)
>Adding postgresql-octagonal-XXXX to xxxx... done
>Setting DATABASE_URL and restarting xxxx... done, v4
>Database has been created and is available
>! This database is empty. If upgrading, you can transfer
>! data from another database with pgbackups:restore
>Use `heroku addons:docs heroku-postgresql` to view documentation.

### config.json
```javascript
"production": {
    "use_env_variable": "DATABASE_URL",
    "username": "xxxxx",
    "password": "xxxxx_",
    "database": "xxxx",
    "host": "xxxxxx",
    "port":5432,
    "dialect": "postgres"
  }
```

this doesn't work but if I put the right credentials it works

**Comment by itslenny** [comment]
First of all, just incase you shouldn't be using both "use_env_variable" and username/password/etc.

Your total "production" section of the config file should look like this: 

```
"production": {
    "use_env_variable": "DATABASE_URL",
    "dialect": "postgres"
  }
```

Also, make sure you have "NODE_ENV" set to production on heroku as that is what tells it to use the production configuration. 

Outside of that I can't really think of anything. Make sure you have the version that is newer than this pull request. If so you'll see this code in your `models/index.js` file:

```
if(config.use_env_variable){
  var sequelize = new Sequelize(process.env[config.use_env_variable]);
}else{
  var sequelize = new Sequelize(config.database, config.username, config.password, config);
}
```

**Comment by BlazeNikhilesh** [comment]
Where do I keep my username and password when I am using "use_env_variable"?
I am using MySQL.

**Comment by andela-oolutola** [comment]
Hi, I am having a problem using config.use_env_variable as it is returning undefined.
`config.js` file
`module.exports = {
  development: {
    use_env_variable: 'postgres://postgres:password@localhost:5432/document_db',
    dialect: 'postgres'
  },
  production: {
    url: process.env.DATABASE_URL,
    dialect: 'postgres'
  },
  staging: {
    url: process.env.DATABASE_URL,
    dialect: 'postgres'
  },
  test: {
    url: process.env.DATABASE_URL ,
    dialect: 'postgres'
  }
};`
relevant portion of `models/index.js` file

`var env       = process.env.NODE_ENV || 'development';
var config    = require(__dirname + './../config/config.js')[env];
var db        = {};
var sequelize;

if (config.use_env_variable) {
  sequelize = new Sequelize(process.env[config.use_env_variable]);
} else {
  sequelize = new Sequelize(config.database, config.username, config.password, config);
}`

**Comment by Americas** [comment]
If you are passing a url, use `sequelize = new Sequelize(config.url);` instead of `sequelize = new Sequelize(config.database, config.username, config.password, config);`
