### ISSUE TITLE
Support multi-migrations

### ISSUE THREAD

**Issue by dantman** [sequelize/cli#174]
Migration operations like adding/changing columns and indexes don't have any form of rollback to them. And it probably isn't possible to create one. This means that to avoid migrations failing in the middle and creating a partially applied state where the migration cannot complete because re-running the first part of the migration (eg: trying to create the column that was already created). So to make reliable migrations you are stuck creating a separate migrations in a separate migration file for each column and index change you want to make. Even if you had 12 columns you wanted to add to a single table all at once.

I think a reasonable alternative to that would be a type of multi-migration where multiple migrations are exported from a single migration file as an array. These would run exactly like normal migrations but be in one file and have an additional integer index that would either be appended like `#1` to the end of the migration `name` or as a second column in the `SequelizeMeta` table.

``` js
"use strict";

module.exports = [
    {
        up: function(migration, Sequelize) {
            return migration
                .addColumn(
                    'FooBar',
                    'B',
                    {
                        type: Sequelize.STRING,
                        allowNull: true
                    });
        },
        down: function(migration) {
            return migration
                .removeColumn('FooBar', 'B');
        }
    },
    {
        up: function(migration, Sequelize) {
            return migration
                .addColumn(
                    'FooBar',
                    'C',
                    {
                        type: Sequelize.STRING,
                        allowNull: true
                    });
        },
        down: function(migration) {
            return migration
                .removeColumn('FooBar', 'C');
        }
    },
    {
        up: function(migration, DataTypes, done) {
            return migration
                .addIndex(
                    'FooBar',
                    ['C'],
                    {
                        indicesType: 'UNIQUE'
                    });
        },
        down: function(migration, DataTypes, done) {
            return migration
                .removeIndex('FooBar', ['C']);
        }
    }
];
```

As a bonus if you make some migration utils in your app that simplify common patterns of migrations into utils that generate up/down migration objects, then a multi-migration file could look like:

``` js
"use strict";
var utils = require('../lib/migration-utils');

module.exports = [
    utils.addColumn(
        'FooBar',
        'B',
        (Sequelize) => ({
            type: Sequelize.STRING,
            allowNull: true
        })),
    utils.addColumn(
        'FooBar',
        'C',
        (Sequelize) => ({
            type: Sequelize.STRING,
            allowNull: true
        })),
    utils.addIndex(
        'FooBar',
        ['C'],
        {
            indicesType: 'UNIQUE'
        }))
];
```

**Comment by sdepold** [comment]
It's probably a stupid question but why wouldn't you just do this:

```
module.exports = [
    {
        up: function(migration, Sequelize) {
          return migration.addColumn(/* b */).then(function () {
            return migration.addColumn(/* c */)
          }).then(function () {
            return migration.addIndex();
          });
      },

      down: ...
    }
];
```

**Comment by dantman** [comment]
@sdepold If `migration.addColumn(/* c */)` fails for any reason the migration will fail however `/* b */` will still exist. When you try to re-run the migration (after fixing whatever intermittent db error caused the failure in `/* c */`) the migration will fail because it will try to create `/* b */` which already exists, throwing an error, and causing the migration to fail. You cannot 'undo' this because the migration never completed (so it's not in the undo stack) plus `down` would assume that `/* c */` exists and fail when it tries to remove it.

The result is an unreliable migration that can get into a partially migrated failure state that requires manual modification of the database to fix.

**Comment by sdepold** [comment]
Right. Good point. So what if you would use a transaction then (which might not work for all dialects though)

**Comment by dantman** [comment]
> Right. Good point. So what if you would use a transaction then (which might not work for all dialects though)

Correct, this will not work in MySQL. It will COMMIT the transaction once it sees ALTER TABLE.

**Comment by sdepold** [comment]
yeah ok. got the point. So this is something one would have to implement in umzug. Want to give it a try? I sort of like the idea of using the `#` as a separator.

**Comment by iamjochem** [comment]
AFAICT half-run migrations can theoretically occur even if you stick to performing a single change per migration because some of the QueryInterface methods actually perform multiple queries under the hood ... although looking at the code it's unlikely to actually bite some-one ... but, maybe, from a technical perspective such internal query-sets should be treated as "multiple-migrations" also (which is liable to cause inception-like headaches if nothing else!)

it's worth noting that MySQL does not allow any schema-mutating queries inside of a transaction (sad panda) ... like @dantman mentioned, any running transaction will be automatically committed, prior to running a schema-mutating query.

**Comment by felixfbecker** [comment]
This array syntax doesn't work very well with ES6. Transaction support for schema changes is one of the reasons postgres is superior to mysql. If you still need this for mysql, just write seperate migrations. Split your commit into smaller ones, with their own migration file. If you still need multiple statements, you are totall free to split your migration up into seperate functions / submigrations in your migration file. You can push the migrations you executed to an array and in your catch block revert them with `Promise.all(executed.map(migration => migration.down(QueryInterface)))`. But all this is still only a workaround to get transactions, because the down migrations could fail aswell, and then you are in a really bad situation. If you need schema change transactions, use a DB that supports schema change transactions.

**Comment by dantman** [comment]
> This array syntax doesn't work very well with ES6.
I don't see how ES6 changes anything. It should work just as good.

**Comment by felixfbecker** [comment]
Because currently you can have a nice migration file with 
```js
export function up() { ... }
export function down() { ... }
```
Now please tell me how would you export your array with ES6 syntax? You would have to use default export, which is not even supported atm afaik and also considered an antipattern by some.

**Comment by felixfbecker** [comment]
I'm not totally against this, I just cant think of a nice syntax - and given you can easily do this with your own code...

**Comment by felixfbecker** [comment]
If you want to share code you could do this as an npm module:
```js
import multi from 'sequelize-multi-migrations';

const {up, down} = multi([
  {
    up() {
      
    },
    down() {
      
    }
  },
  {
    up() {
      
    },
    down() {
      
    }
  }
])

export {up, down}
```

**Comment by dantman** [comment]
How are you supposed to build a npm module to do multi migrations (**that work in mysql**) when the handling of migration files is built into umzug?

I do not consider 'You can just use PostgreSQL' or 'I don't like the look of the syntax' to be acceptable reasons to block a feature like this.

Switching DBMS is **not** an option; unless you want to pay the extra monthly hosting fees doing so would cost me and others.

As someone who does have to take MySQL into consideration, the mildly ugliness of the `export default ([]);` syntax is much less of an issue than being forced to split groups of logically linked migrations (like a column and index for that column) into multiple files making the code for my migrations harder to follow. And supporting this doesn't harm you in any way because as an optional feature if you don't like the look of the syntax, you don't have to use it anywhere.

**Comment by felixfbecker** [comment]
@dantman As I said, I'm not against this feature, but API syntax _needs_ to be **discussed** and **designed** first, because adding a new feature an API means it needs to be protected from breaking changes, maintained and tested for the future by maintainers. And often it is easier for such features to exist in plugins instead.

Please also note my point that migration "steps" are not equivalent to transactions. A transaction is guaranteed to always be able to rollback. You down migration however could fail aswell.

> How are you supposed to build a npm module to do multi migrations (that work in mysql) when the handling of migration files is built into umzug?

Just like the example I showed you. An example implementation:

```js
class Multi {
  constructor(migrations) {
    this._migrations = migrations;
    this._executed = [];
  }
  _execute(type, QueryInterface) {
    return this._migrations.reduce((previous, current) => {
      return previous.then(() => {
        return current[type](QueryInterface)
          .then(() => this._executed.push(current))
          .catch(err => {
            return Promise.all(
              this._executed.reverse().reduce((previous, current) => {
                const rollbackType = {up: 'down', down: 'up'}[type];
                return previous.then(() => current[rollbackType](QueryInterface))
              }, Promise.resolve())
            ).then(() => {
              throw err;
            });
          });
      });
    }, Promise.resolve());
  }
  up(QueryInterface) {
    return this._execute('up', QueryInterface);
  }
  down(QueryInterface) {
    return this._execute('down', QueryInterface);
  }
}
```
I don't know what environment you're in, but this can be made much prettier of course if you have async/await, and much uglier if you don't have classes or arrow functions.

**Comment by dantman** [comment]
@felixfbecker That is an improvement over the plain promises @sdepold described. However it is still inferior to separate migrations in one file. If the failure is due to something like a momentary network issue, the down migrations will fail and you will still be locked into a broken state where both `db:migrate` and `db:migrate:undo` fail and are unable to continue or fix the damage after the network recovers.

I do not need transactions or even something similar to transactions. If I want to create a column then create an index for it and write 2 migrations in 1 file for it; it is fine if a failure to create the index leaves the database in a state where the column still exists, as long as `db:migrate:undo` will remove the column using the previous migration's down and `db:migrate` will re-run the `up` that failed so I can try creating the index again after fixing the temporary issue.


Think about this another way.

Why does umzug have to demand that all migrations are defined in the same format (a migrations/ folder with each migration in a separate file as an export)? Why can't all migrations be defined as an array of objects in a single file; As a mix of both; As custom JSON or YAML files defining migrations common in a project; Or in whatever other format fits a project best.

The only thing Sequelize/Umzug seems to require is a list of objects (not necessarily with a defined length) each containing a name, up, and down function. How it acquires them is irrelevant.

If there is a problem with tweaking uzmug's current migration file reading to support a group of sub-migrations as an array; then what if I instead rewrote uzmug's current `migrations/` folder handling into a uzmug plugin for extracting migration data from a project and made a second community plugin that extends it to support sub migrations?
