### ISSUE TITLE
dropTable not schema-aware?

### ISSUE THREAD

**Issue by paulxtiseo** [sequelize/cli#178]
So, you can `createTable` in a schema, it creates the table in the assigned schema, but seems like we are not able to `dropTable` on the `down` migration when reversing changes?
```
return queryInterface.dropTable('ivr', {
      schema: 'raw_filemaker'
    });
```
gives me
`DROP TABLE IF EXISTS "ivr";`

This is in CLI v1.8.3 w/postgresql.

**Comment by paulxtiseo** [comment]
Seems like the problem is in the sequelize project's [dropTableQuery](https://github.com/sequelize/sequelize/blob/84c9a68e55d698f7ee999217aadf80604a5ed126/lib/dialects/postgres/query-generator.js#L89) function, so probably should be in reported there?

**Comment by sdepold** [comment]
Which version of sequelize are you using?

**Comment by sdepold** [comment]
so just to get that right: queryInterface.dropTable resolve a string for you?

**Comment by paulxtiseo** [comment]
I created a [ticket](https://github.com/sequelize/sequelize/issues/4422) in the Sequelize project. Using v3.6.0. The problem seems to be in the `dropTable()` function in `query-interface.js`. The `createTable()` function seems to have all sorts of logic for establishing how to stringify schemas, whereas `dropTable(0` does not...or, at least, that is my current theory. ;)

**Comment by sdepold** [comment]
I'm going to close this issue as it is not related to the CLI.
