### ISSUE TITLE
this.getDialect() returning wrong dialect

### ISSUE THREAD

**Issue by aray12** [sequelize/cli#184]
So I have been working getting my migration process working and I keep getting the following error

```
Sequelize [Node: 0.12.4, CLI: 1.9.1, ORM: 3.6.0]

Loaded configuration file "config/database.js".
Using environment "development".
Using gulpfile ~/WebstormProjects/skillx/node_modules/sequelize-cli/lib/gulpfile.js
Starting 'db:migrate'...
'db:migrate' errored after 32 ms
    at new Sequelize (/Users/alexanderray/WebstormProjects/skillx/node_modules/sequelize/lib/sequelize.js:183:11)
    at getSequelizeInstance (/Users/alexanderray/WebstormProjects/skillx/node_modules/sequelize-cli/lib/tasks/db.js:282:10)
    at getMigrator (/Users/alexanderray/WebstormProjects/skillx/node_modules/sequelize-cli/lib/tasks/db.js:287:21)
...

```

Following is my `sequelizerc`
```
var path = require('path')

module.exports = {
  'config':          path.resolve('config/', 'database.js')
}
```

Following is my config file
```
module.exports = {

    "development": {
        "username": "username",
        "password": null,
        "database": "test_db",
        "options": {
            "host": "localhost",
            "dialect": "postgres",
            "port": 5432,
            "quoteIdentifiers": false,
            "logging": false,
            "define": {
                "timestamps": true,
                "underscored": true,
                "freezeTableName": true
            }
        },
        "migrationStorageTableName": "sequelize_meta"
    }
}
```

After some investigating I found that the error being thrown has to do with an "unsupported" dialect. 
`sequelize/lib/sequelize.js`
```
try {
    var Dialect = require('./dialects/' + this.getDialect());
    this.dialect = new Dialect(this);
  } catch (err) {
    throw new Error('The dialect ' + this.getDialect() + ' is not supported. ('+err+')');
  }
```

I found that this.getDialect() was returning mysql. So the error makes sense because I don't have the correct dependencies since I am using postgres. I found that everything started working properly when I edited the above code to this:
```
try {
    var Dialect = require('./dialects/postgres');
    this.dialect = new Dialect(this);
  } catch (err) {
    throw new Error('The dialect ' + this.getDialect() + ' is not supported. ('+err+')');
  }
```

This is obviously not a sustainable fix, but I have no idea why this.getDialect() is returning the wrong value (I realize mysql is default) and haven't found any other related issues. I realize that the code I have altered above is in the sequelize repo, but I have only run into problems with sequelize-cli and have been using sequelize successfully for connecting and querying on my current project.

Am I defining the dialect in my config incorrectly? Any help would be greatly appreciated.

**Comment by sdepold** [comment]
This is happening because dialect should be defined directly under "development":

```
$ sequelize init
$ cat config/config.json

{
  "development": {
    "username": "root",
    "password": null,
    "database": "database_development",
    "host": "127.0.0.1",
    "dialect": "mysql" <---
  },
...
}
```

**Comment by Americas** [comment]
@sdepold that is actually something I find odd, in the sequelize-cli the dialect is required in the root of the config, but when you create a sequelize instance, the dialect needs to be in the options value of the config. As such, my config json has dialect in both places, so I can use it for both things.

**Comment by aray12** [comment]
@Americas I agree. This caused a lot of confusion for me and seems like I should be able to reuse the same config for migrations and running.

@sdepold Thanks for the quick reply. Helped a lot. I might recommend opening an issue so that the dialect doesn't have to be repeated, but I will let you decide whether that has any merit and am closing this issue

**Comment by sdepold** [comment]
I can understand the confusion. Will think about it.
