### ISSUE TITLE
Documentation - How to pass schema with references

### ISSUE THREAD

**Issue by milovanderlinden** [sequelize/cli#191]
I took a deep dive into sequelize source code and finally discovered:

```
references: {
    model: {
      schema: 'testSchema',
      tableName: 'otherTable'
    },
    key: 'id'
  },
```

Will create a reference to a table in another schema then public.
It would be good if this got documented.

**Comment by milovanderlinden** [comment]
See also https://github.com/sequelize/sequelize/issues/4567

**Comment by sdepold** [comment]
Uhm. Is there anything to do in the CLI?

**Comment by jonnolen** [comment]
I've added a flag in sequelize options that allows you to specify a schema as part of a command or as a global option. #207
