### ISSUE TITLE
Documentation -  When using Enum DataTypes, specifying tablename as a string will not work

### ISSUE THREAD

**Issue by milovanderlinden** [sequelize/cli#192]
``` javascript
queryInterface.createTable("Organizations",
```

Will fail (hard) when one of the attributes you define is an Enum. If you are using an Enum, your createTable should be written like:

``` javascript
queryInterface.createTable({
        table: 'PluralName',
        tableName: 'PluralName',
        name: 'SingularName',
        schema: 'mySchema',
        delimiter: '.'
      }
```

You cannot forget one of these attributes or it will still fail.

**Comment by sdepold** [comment]
Iek. Can you tell me which CLI call you were running to get this migration?

**Comment by milovanderlinden** [comment]
Oops. accidently closed. Source is on my other PC. Will post it later.

**Comment by milovanderlinden** [comment]
## Faulty migration

I have a table I want to create in a specific schema. For this I wrote the following migration.

```javascript
(function () {
'use strict';
module.exports = {
  up: function (queryInterface, Sequelize) {
    return Promise.all([
      queryInterface.createTable("Buildings", {
        id: {
          type: Sequelize.INTEGER,
          primaryKey: true,
          autoIncrement: true
        },
        name: Sequelize.STRING,
        source: Sequelize.ENUM('openstreetmap','imagery', 'user', 'import'),
        sourceId: Sequelize.STRING,
        geometry: Sequelize.GEOMETRY(),
        "createdAt": {type: Sequelize.DATE, allowNull: false},
        "updatedAt": {type: Sequelize.DATE, allowNull: false},
        "deletedAt": Sequelize.DATE
      }, {
        schema: "mySchema"
      })
    ]);
  },down: function (queryInterface) {
    return Promise.all([
      queryInterface.dropTable('Buildings',{schema: 'mySchema'})
    ]);
  }
};
}());
```

The failure is because the ENUM(TYPE for Postgres) will get created in the public(default) schema when defined like this, but later on, when it is being queried, it looks for the enum in my schema.

## Correct migration

So I ran sequelize.sync() to see what it created and it turns out sync DOES put the enum in the schema. Then I debugged sequelize and cli and found out sync passes the table as ann object while cli passes it as a string. I then decided to feed my migration an object instead of a string too. And this worked. A table defined like:
```javascript
{
  table: 'Buildings',
  tableName: 'Buildings',
  name: 'Building',
  schema: 'mySchema',
  delimiter: '.'
}
```
Is processed correctly. I then tried to limit the definition to see if it would grab default. But it didn't
```javascript
{
  table: 'Buildings',
  schema: 'mySchema'
}
```
Will still fail and create Enums as enum_undefined_.. So the solution is to pass the table object with all possible properties. So the final, working migration is:

```javascript
(function () {
'use strict';
module.exports = {
  up: function (queryInterface, Sequelize) {
    return Promise.all([
      queryInterface.createTable({
        table: 'Buildings',
        tableName: 'Buildings',
        name: 'Building',
        schema: 'mySchema',
        delimiter: '.'
      }, {
        id: {
          type: Sequelize.INTEGER,
          primaryKey: true,
          autoIncrement: true
        },
        name: Sequelize.STRING,
        source: Sequelize.ENUM('openstreetmap','imagery', 'user', 'import'),
        sourceId: Sequelize.STRING,
        geometry: Sequelize.GEOMETRY(),
        "createdAt": {type: Sequelize.DATE, allowNull: false},
        "updatedAt": {type: Sequelize.DATE, allowNull: false},
        "deletedAt": Sequelize.DATE
      }, {
        schema: "mySchema"
      })
    ]);
  },down: function (queryInterface) {
    return Promise.all([
      queryInterface.dropTable('Buildings',{schema: 'mySchema'})
    ]);
  }
};
}());

**Comment by milovanderlinden** [comment]
If this is acceptable behaviour, it should at least be documented. I offered to document this in the sequelize documentation.

**Comment by sushantdhiman** [comment]
http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html#instance-method-createTable
