### ISSUE TITLE
Passing configuration object instead of path in .sequelizerc

### ISSUE THREAD

**Issue by bassarisse** [sequelize/cli#198]
Hi there!

I was wondering if this would be a good feature.

In `.sequelizerc`:
```javascript
module.exports = {
  config:  { /* config */ }
};
```

I would definitely benefit from that.
What do you guys think?

**Comment by sdepold** [comment]
Can you elaborate on your use case? Might https://github.com/sequelize/cli/pull/194 be helpful?

**Comment by bassarisse** [comment]
Yes, this would be a perfect fit!

My application already contains a config.json (for settings other than db connection) located elsewhere, and I would like to load the db configuration from that file, without having to specify the path every time I use sequelize commands. My config.json also has a format a bit different from the sequelize config, so a bit of preprocessing would be needed.

Thank you so much!

**Comment by sdepold** [comment]
Cool. Could you please test the PR's branch and let me know if anything is missing or broken?

**Comment by bassarisse** [comment]
I'll check tomorrow and let you know!

**Comment by yasirhantoush** [comment]
What is the status of this feature, is it implemented?

**Comment by bassarisse** [comment]
AFAIK, yes.

**Comment by dasheck0** [comment]
I did it just now and it seems that is not implemented yet. See the log attached:

```
Sequelize CLI [Node: 8.9.3, CLI: 3.2.0, ORM: 4.18.0]

WARNING: This version of Sequelize CLI is not fully compatible with Sequelize v4. https://github.com/sequelize/cli#sequelize-support


ERROR: Path must be a string. Received { host: '127.0.0.1',
  username: '...',
  password: '...',
  database: '...',
  dialect: 'mysql',
  port: 3306 }
```

**Comment by edmundcong** [comment]
why was it removed in the later versions? seems like a very useful feature
