### ISSUE TITLE
missing instructions for test env setup

### ISSUE THREAD

**Issue by jonnolen** [sequelize/cli#202]
I can't find the instructions for getting an environment set up for testing, I'm would like to submit a PR for a bug I found in --options-path, but am unable to run tests locally.

**Comment by wwalser** [comment]
Same here, I'm slowly working my way through figuring out whether I should use vagrant or my own local instance of mysql with a subset of the tests.

**Comment by sushantdhiman** [comment]
Please checkout new contribution docs, default setup require no database setup (It use SQLite)
