### ISSUE TITLE
db:migrate does not work (with models that do not have a primary key?) [versions: CLI: 1.9.1, ORM: 3.11.0]

### ISSUE THREAD

**Issue by iamjochem** [sequelize/cli#208]
I get the following error output when trying to run `db:migrate`:

```
Sequelize [Node: 4.2.0, CLI: 1.9.1, ORM: 3.11.0]

Using gulpfile /work/oo/oong/node_modules/sequelize-cli/lib/gulpfile.js
Starting 'db:migrate'...
Cannot read property 'replace' of null
```

I created a single crappy model using the following command line:

``` zsh
bin/sequelize model:create --name foo --attributes='id:int,name:string'
```

which results in a model file that looks like:

``` js
'use strict';
module.exports = function(sequelize, DataTypes) {
  var foo = sequelize.define('foo', {
    id: DataTypes.INT,
    name: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
        // associations can be defined here
      }
    }
  });
  return foo;
};
```

looking into this a little further I notice that changing the model definition to the following does nothing to alleviate the error:

``` js
'use strict';
module.exports = function(sequelize, DataTypes) {
  var foo = sequelize.define('foo', {
    id: { type: DataTypes.INTEGER, primaryKey: true},
    name: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
        // associations can be defined here
      }
    }
  });
  return foo;
};
```

can someone explain what is going on here? are migrations broken? Am I doing something wrong?

**Comment by iamjochem** [comment]
some more info: 

1. I have tried with an older node version (v.0.12.7) but that gives exactly the same error.
2. I have tried to use older versions of sequelize and sequelize-cli but all version combinations that I tried gave unrelated errors, e.g.:
```js
TypeError: Path must be a string. Received [ '/work/oo/oong/bin/../db/config.json',
  '/work/oo/oong/db/config.json' ]
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at Object.module.exports.getConfigFile (/work/oo/oong/node_modules/sequelize-cli/lib/helpers/config-helper.js:13:19)
    at Object.module.exports.configFileExists (/work/oo/oong/node_modules/sequelize-cli/lib/helpers/config-helper.js:24:31)
    at getMigrator (/work/oo/oong/node_modules/sequelize-cli/lib/tasks/db.js:211:22)
    at Object.module.exports.db:migrate.task (/work/oo/oong/node_modules/sequelize-cli/lib/tasks/db.js:23:7)
    at Gulp.gulp.task.aliases (/work/oo/oong/node_modules/sequelize-cli/lib/helpers/gulp-helper.js:14:14)
    at module.exports (/work/oo/oong/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/work/oo/oong/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/work/oo/oong/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/work/oo/oong/node_modules/sequelize-cli/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /work/oo/oong/node_modules/sequelize-cli/node_modules/gulp/bin/gulp.js:129:20
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:134:18)
    at node.js:961:3
```

**Comment by sdepold** [comment]
is it possible that you specified the config path in both your config and the cli call?

**Comment by iamjochem** [comment]
yes that is possible! - but that would only explain the second error, right? gonna have a play with this information to see if removing one of them fixes stuff ..

**Comment by iamjochem** [comment]
okay then ... I have confirmed that having a `.sequelizerc` file AND giving options on the command line causes this error.

my .sequelizerc files looks like this: 
```js
// deps
var path = require('path');
var exec = require('child_process').execSync;

// locals
var dburl;

// exports
module.exports = {
    'config'          : path.resolve('db', 'config.json'),
    'migrations-path' : path.resolve('db', 'migrations'),
    'seeders-path'    : path.resolve('db', 'seeders'),
    'models-path'     : path.resolve('db', 'models'),
};

try {
    dburl = exec('./get_dburl', {
        cwd     : __dirname + '/bin/',
        encoding: 'utf8',
        timeout : 100
    });

    if (dburl)
        module.exports.url = dburl;


console.log(module.exports);
} catch (e) {
    process.exit(1);
}
```
I was also using a custom wrapper for `node_modules/.bin/sequelize` that [automatically] generated a command line like so:

```
./node_modules/.bin/sequelize --migrations-path=./db/migrations --seeders-path=./db/seeders --models-path=./db/models --url="postgres://localhost/mydb"
```

I had created the wrapper because I didn't want to have to specify the custom paths for every invocation ... this was before I realized that I could the same with `.sequelizerc` ... being a paranoid type I kept both in place (the parameter values in my `.sequelizerc` and those placed in the generated cmd-line were the same).

from my investigation I conclude that using `.sequelizerc` in combination with ANY command line parameters causes failure with the afore mentioned error.

I would like to make the observation that the error message in this case is completely unhelpful, also I would never have guessed that passing in [duplicate] options from 2 different places would cause such an error, I would expect the command line arguments to simply overrule what is specified in .sequelizerc.

maybe my expectations are wrong - either way the error message could be more helpful :-)

regardless - thank you for the quick response and for helping me over come this little hurdle!! - it was driving me mad :-)

**Comment by frank-borkin** [comment]
+1 - just got burned with the same issue.
Cannot read property 'replace' of undefined when trying to add a foreign key
Sequelize CLI [Node: 11.3.0, CLI: 5.4.0, ORM: 4.42.0]
Turned out to be the .sequelizerc file, once I removed it all was well.
Having better error handling / messaging would be a big help.
