### ISSUE TITLE
db:migrate:undo:all should also clear SequelizeData table

### ISSUE THREAD

**Issue by elado** [sequelize/cli#214]
Currently it keeps `SequelizeData` rows. `db:migrate:undo:all` and then `db:seed` doesn't seed.

And undoing seed after undoing migrations leads to an error (because the tables don't exists).

**Comment by theSuiGenerisAakash** [comment]
Is this [question](https://stackoverflow.com/questions/48730210/arent-migrations-supposed-to-be-not-deleted) good enough to represent the issue? @elado
