### ISSUE TITLE
Migration Order of Execution

### ISSUE THREAD

**Issue by aray12** [sequelize/cli#217]
I can't seem to find the answer to this anywhere. I understand how Sequelize migrations and seeder work, but I have not found anywhere that states if they execute in some particular order. So if I start with a database, make a bunch of migrations, and then decide to initialize a brand new database from the original start point, will it execute the migrations in the exact same order.

I am using sequelize-cli to create migrations, so the file name does begin with a timestamp.

**Comment by sdepold** [comment]
Hi @aray12,

it checks the files in the migrations / seeders folders and orders the list alphabetically. So if your migrations / seeds start with the timestamps, the migrations are ordered by timestamps asc.

**Comment by aray12** [comment]
Thanks @sdepold 

This is what I assumed (and what my testing communicated), but I couldn't find any documentation confirming this.
