### ISSUE TITLE
db:migrate not reading DATABASE_URL

### ISSUE THREAD

**Issue by ryanwalters** [sequelize/cli#218]
I'm trying to use the `db:migrate` command, but it isn't working.

My models are kept in a separate module that I load as a dependency into the main app. `.sequelizerc` loads the `config.json` from the models module. The `DATABASE_URL` environment variable is located in the main app's `.env` file, loaded when the server is started with `foreman start`.

    DATABASE_URL=postgres://abc:def@herokudb.com:5432/ghi?ssl=true

This is the output of the `sequelize db:migrate` command:

	> sequelize db:migrate

	Sequelize [Node: 4.2.1, CLI: 2.0.0, ORM: 3.13.0]

	Loaded configuration file "node_modules\project\config\config.json".
	Using environment "development".
	Using gulpfile C:\Utils\nodejs\node_modules\sequelize-cli\lib\gulpfile.js
	Starting 'db:migrate'...
	Finished 'db:migrate' after 156 ms
	Unable to connect to database: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432

`config.json`:

    "development": {
        "use_env_variable": "DATABASE_URL",
        "dialect": "postgres"
    }

**Why is `sequelize` trying to connect to 127.0.0.1?**

It seems that the `DATABASE_URL` isn't being loaded, but I don't know why. What am I missing?

**Comment by ryanwalters** [comment]
I ended up fixing this issue by using the `node-env-file` package and then using a `config.js` file instead of `config.json`.

    // config.js
    const Env = require('node-env-file');

    Env(__dirname + '/.env');

    module.exports = {
        development: {
            use_env_variable: 'DATABASE_URL',
            dialect: 'postgres'
        }
    }

**Comment by connor11528** [comment]
Yes make sure your username and password are included in config object to solve this issue!

**Comment by ankitgaurav** [comment]
Thanks, @ryanwalters. Your solution worked for me too. Just want to add that the file .sequelizerc file also needs to be updated after changes config.json to config.js. 
Maybe that's pretty obvious. 😁 Still.

`
// config.js
const Env = require('dotenv').config();

module.exports = {
  "development": {
    "use_env_variable": "DATABASE_URL",
    "dialect": "postgres"
  }
}

`

**Comment by joaovitorzv** [comment]
i spent 8 hours to solve that, i was putting on "DATABASE_URL" the DATABASE URI, but is literary the string "DATABASE_URL"

**Comment by webexpert821** [comment]
make sure all variables of development is correct.
In my case, I didn't declare password as string, and also database was already existed, so throws some errors. :)
Anyway, thanks everyone, your saying was really helpful for me.
