### ISSUE TITLE
Order of adding / removing columns shouldn't matter in a migration

### ISSUE THREAD

**Issue by kevin-friedheim** [sequelize/cli#221]
```
up: function (queryInterface, Sequelize) {
        return Promise.all([
            queryInterface.removeColumn('test', 'colB')
            queryInterface.addColumn('test', 'colA', Sequelize.INTEGER),
        ]);
    },
```

In this example - `colB` is removed from table `test`, but `colA` is not added to the schema. If i reverse the order and `addColumn` - things work.

In either case, no error is thrown.

**Comment by sushantdhiman** [comment]
Closing (Issue Cleanup), Please comment if you want to keep it open
