### ISSUE TITLE
Does config.json supports url format?

### ISSUE THREAD

**Issue by PavelPolyakov** [sequelize/cli#224]
Hi,

I have tried to do like this:

```
{
  "development": {
    "migrationStorageTableName" : "sequelize_meta",
    "url": "postgresql://xxx:yyy@hostname:5432/database",
    "dialect": "postgres"
  }
}
```

But it doesn't work. Is there an option to store the url in the config? 

Regards,

**Comment by sdepold** [comment]
Hi @PavelPolyakov,

I just looked into the code and this is currently not supported. The good news is though, that you could use either [an environment variable](https://github.com/sequelize/cli#configuration-connection-environment-variable) instead or a `config.js` file, which parses the url string and extracts the host, port, db name, etc etc.

Furthermore: Pull Requests are welcome. So if you want to implement this (and it shouldn't be too hard), go ahead :)

**Comment by PavelPolyakov** [comment]
@sdepold 

Yes, I will prepare PR then, probably.

I have just cloned the project, however, the tests are not passing:
![image](https://cloud.githubusercontent.com/assets/839290/11268724/a9550b50-8eb2-11e5-9767-341be85b3be0.png)

Do you have the same situation?

**Comment by sdepold** [comment]
oh crap!!!!!!!

please go to the readme and remove the code block about dialectOptions.

**Comment by sdepold** [comment]
Can you sync with master and see if that works better now?

**Comment by PavelPolyakov** [comment]
Yep, now it works. Except I don't have mysql running locally :) Thanks.

**Comment by sdepold** [comment]
:ok_hand:
