### ISSUE TITLE
CLI silently failing

### ISSUE THREAD

**Issue by toptensoftware** [sequelize/cli#234]
Hi, 

I'm just starting with sequelize and sequelize CLI, so this is certainly me making silly mistakes but I'm finding using the cli and the migration tools fairly infuriating - mostly because they seem to just silently fail if something goes wrong.

I've tried on OSX and Windows and in both cases I never seem to see errors.  I've seen this with migrations and with seeding and while I found the issue with migrations I can not figure out how to get a seeder to run and work.

I've reduced this to a fairly simple seed script which when invoked does this:

~~~
Brads-MacBook-Pro:portal brad$ ./node_modules/.bin/sequelize db:seed

Sequelize [Node: 0.12.5, CLI: 2.2.1, ORM: 3.14.2, sqlite3: ^3.1.1]

Loaded configuration file "config/config.json".
Using environment "development".
Using gulpfile ~/Projects/cantabilesoftware.com/portal/node_modules/sequelize-cli/lib/gulpfile.js
Starting 'db:seed'...
Finished 'db:seed' after 72 ms
== 20151127232107-createLicenseTypes: migrating =======
Brads-MacBook-Pro:portal brad$ 
~~~

To me, that looks like it worked - maybe, not sure.  Nothing in the db though.  Probably a mistake in my script but I have no way of tracking it down.

What magic am I missing to make sequelize cli tell me what's up?

**Comment by toptensoftware** [comment]
Looking more closely at this, turns out the above is actually a failed state.  Unless it says "migrated" something went wrong.  No news is bad news.

Also, I found that any error, even syntax errors in the seeder script were silently ignored.  Some of these I could find by just running the script through node:

    node seeders/12345678-somescript.js

But this doesn't help with mistakes like a mistyped table name.  So I started looking a little deeper and it looks like umzug swallows errors [here](https://github.com/sequelize/umzug/blob/master/index.js#L55).

I found by putting the following a little further down (before the final tap - about line 88) I could actually see the error:

            .catch(function (err) {
              console.error(err.message);
              throw err;
            })

eg:

~~~
Brads-MacBook-Pro:portal brad$ ./node_modules/.bin/sequelize db:seed

Sequelize [Node: 0.12.5, CLI: 2.2.1, ORM: 3.14.2, sqlite3: ^3.1.1]

Loaded configuration file "config/config.json".
Using environment "development".
Using gulpfile ~/Projects/cantabilesoftware.com/portal/node_modules/sequelize-cli/lib/gulpfile.js
Starting 'db:seed'...
Finished 'db:seed' after 73 ms
== 20151127232107-createLicenseTypes: migrating =======
SQLITE_ERROR: no such table: LicenseTypesX
~~~

Ah!  "no such table" - good to know!

So I guess this falls onto umzug, but as a first time user of sequelize having to debug through sequelize's cli source code, liftoff, gulp and umzug is not the most fun way to get started (though I did learn a few things along the way).

**Comment by SignalDancer** [comment]
@toptensoftware THANK YOU SO MUCH. I've been swearing at this for hours trying to figure out why my seeds weren't working and some other methods I was trying weren't working (probably because they were being tripped up by the syntax error I have now, finally, found.). This was remarkably unfun and I know my way around SQL fairly well but I'm new to Sequelize. 

I almost was going to see about dropping the package for a different one if I couldn't sort out what I was doing wrong.

**Comment by sdepold** [comment]
@toptensoftware good catch :)

**Comment by PavelPolyakov** [comment]
I just came here to create the same issue :)

would be good if fixed

**Comment by barak-shirali** [comment]
:+1:  @toptensoftware db:seed silently failed for me there as well

**Comment by dave-hillier** [comment]
I've also got a silent failure when running `db:seed` and no way to debug this will try the console logging.

**Comment by marol-hadidjaja** [comment]
Almost same case for me. But my seed sometimes is successfully worked and same for ```db:seed:undo```
+1 for fix this bug...wew

**Comment by Americas** [comment]
@toptensoftware I suggest opening this issue on umzug (or preferably, a PR), as it is not related to this project.
