### ISSUE TITLE
Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by Honghe** [sequelize/cli#241]
Environment:
    Windows 10

The usage and error message:

```
sequelize db:migrate --url 'mysql://name:pswd@www.example.com:3307/dbname'

Sequelize [Node: 4.2.2, CLI: 2.2.1, ORM: 3.14.1]

Using gulpfile ~\xxx\node_modules\sequelize-cli\lib\gulpfile.js
Starting 'db:migrate'...
Cannot read property 'replace' of null
```

What's the message meaning?
Appreciate!

**Comment by stuartZhang** [comment]
Maybe, compliant with the recommended flow, the error can be circumvented.

.sequelizerc -> config.js -> db connection string

**Comment by iamgabrielsoft** [comment]
if your experiencing this error till now, try setting up your database config correctly, probably in your .env file
