### ISSUE TITLE
Bug Report for the command "sequelize db:seed:undo:all"

### ISSUE THREAD

**Issue by stuartZhang** [sequelize/cli#252]
Hello experts,

I have discovered the command "sequelize db:seed:undo:all" always complains the below error, even though there are the db records of the executed seeds.
# 

Loaded configuration file "db/config.js".
Using environment "development".
Using gulpfile ~/usr/lib/node_modules/sequelize-cli/lib/gulpfile.js
Starting 'db:seed:undo:all'...
# No seeders found.

And then, I looked into the source codes and observed an incorrect underlying API (from Umzug) is invoked in the 116th line of the JavaScript file "sequelize-cli/lib/tasks/db.js"

```
  'db:seed:undo:all': {
    descriptions: {
      'short': 'Deletes data from the database.',
      'long': [
        'The command tries unseeding every existing seed.'
      ]
    },
    task: function () {
      getMigrator('seeder', function (migrator) {

    migrator.pending() // The error is here. The expected API invocation is  "migrator.executed()"

    .then(function (seeders) {
      ...
    }).then(function () {
       ...
    })
    .catch(function (err) {
       ...
    });
  });
}
```

  },

My question:

When will you fix the bug?

**Comment by Americas** [comment]
why not submit a PR?

**Comment by stuartZhang** [comment]
I have just submitted a PR: https://github.com/sequelize/cli/pull/253

**Comment by corbanb** [comment]
+1 - bump

**Comment by wstallard-gobalto** [comment]
+1 Still broken...

**Comment by deviltsc** [comment]
+1 Still broken

**Comment by jamespedid** [comment]
+1 Still broken

**Comment by trjstewart** [comment]
+1 Still broken.
