### ISSUE TITLE
Postgres schema for migration table

### ISSUE THREAD

**Issue by angelstoone** [sequelize/cli#265]
Hi guys,

I would like to create the migration table in a given postgres **postgres schema** different from the **public** one. Is there an option in the `config.json` file to specify the **postgres schema** of the migrations table?

I am talking about something like the `migrationStorageTableName` option, for example, called `migrationStorageSchemaName`?

Cheers

**Comment by Americas** [comment]
Hi @angelstoone, currently there isn't such an option, but it is doable.

A pull request is greatly appreciated if you are up to the task. If not, I can get to this in the not too distant future :laughing:

**Comment by angelstoone** [comment]
Hi @Americas, it looks like someone else already did it #141 but it has not been merged yet.

**Comment by Americas** [comment]
PR #205 seems to do the trick. However, it needs to be updated, and requires tests!

**Comment by jspeis** [comment]
+1 for supporting this feature

**Comment by llonchj** [comment]
+1

**Comment by TizianoPerrucci** [comment]
+1

**Comment by webloem** [comment]
+1

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/cli/pull/635
