### ISSUE TITLE
Upgrade gulp to 3.9.1

### ISSUE THREAD

**Issue by bobintornado** [sequelize/cli#267]
Hey just wonder why the project is still using gulp version 3.8.10? But not v3.9.1?

As it is giving me errors like following

```
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible. 
```

**Comment by sdepold** [comment]
PRs are welcome. There is no particular reason.
