### ISSUE TITLE
Unable to connect to database: SequelizeConnectionRefusedError: connect ECONNREFUSED

### ISSUE THREAD

**Issue by andela-amaborukoje** [sequelize/cli#273]
Whenever i launch my app, part of my task is to first run a migration. however, I get the below error 95% of the time.
```Message:
    Command failed: /bin/sh -c node_modules/.bin/sequelize db:migrate
Unable to connect to database: SequelizeConnectionRefusedError: connect ECONNREFUSED

Details:
    killed: false
    code: 1
    signal: null
    cmd: /bin/sh -c node_modules/.bin/sequelize db:migrate
    stdout:
Sequelize [Node: 0.12.7, CLI: 2.1.0, ORM: 3.14.0]```


Note: I can still query and connect to the database after the failure, also when i check the TCP `lsof -i tcp:5432`  its only one instance of postgres that runs.

I would appreciate any assistance in solving this issue.

**Comment by Americas** [comment]
Can you provide a simple example of code that runs into this problem? If it is an intermittent problem I would guess that some concurrency is messing up the connections.

**Comment by andela-amaborukoje** [comment]
it is actually intermittent and after some restarts maybe 4 or 5 times it might stop.  However this problem only affects migration as i can still connect and make queries to the database from the app.

**Comment by felixfbecker** [comment]
Closing as sequelize-cli doesnt handle connecting, but sequelize. This is probably a problem with your environment.
