### ISSUE TITLE
ENUM problem

### ISSUE THREAD

**Issue by AndrewBryukhov** [sequelize/cli#278]
I have follow cmd script:

SET seq="./node_modules/.bin/sequelize.cmd"
call %seq% model:create --name items --attributes name:string,condition:enum --underscored
1. How i can set enum correctly, like {condition:enum,values:['active','pending','deleted']}?
   I'm already trying many combinations, but without result.
2. How i can set oneToMany/ManyToMany and etc.

UPD.
3. Also i need to gen getter and setters methods.

**Comment by andhikamaheva** [comment]
This problems same with me, i want add some enum values with CLI

**Comment by sushantdhiman** [comment]
Moved to https://github.com/sequelize/cli/issues/550
