### ISSUE TITLE
Change models and migrations folder

### ISSUE THREAD

**Issue by grillorafael** [sequelize/cli#28]
Is there a way to change it?

**Comment by YouriT** [comment]
Was looking for this ! Good ! Maybe should be in the doc nope ? :)

**Comment by sdepold** [comment]
A first start would be an improved README.md. Want to provide a PR?

**Comment by YouriT** [comment]
I'm still in the learning curve of sequelize, I don't feel confortable enough now for that, but, by time running, I'm improving a memo so when it becomes strong enough I can give it a try, will keep you up to date :)

**Comment by jasonbodily** [comment]
This is still very much desirable. Any news on being able to provide a default set of options?

**Comment by caioflores** [comment]
Looking for a solution here too.

**Comment by caioflores** [comment]
I have to use --options-path=path/options.json in any command that I try? I can't set it as default or something like that?

**Comment by NitroBAY** [comment]
@caioflores one can (as I did) define a `sequelize` script in npm's `package.json` like this : 
```
{
"scripts": {
 "sequelize": "sequelize --options-path=sequelize/config.json"
}
}
```
then one can ` init:seeders -- --name=drugs` (note the `--` before the `--XXX=YYY`).
What's great with that method is that you don't have to install `sequelize-cli` globally but you may or may not install it as a dev-dependency (`npm i --save-dev sequelize-cli`).

**Comment by NitroBAY** [comment]
@caioflores define in `package.json` in `"scripts"` a new `script` like this `"sequelize": "sequelize --options-path=sequelize/config.json"` then you can `npm run sequelize seed:create -- --name=drugs` (note the -- mandatory to add arguments). This technique not only allows you to not have to type again and again same args but also allows you to have `sequelize-cli` as a dev dependency so you do not have to reinstall all your command lines tools on each PC.

**Comment by NitroBAY** [comment]
@caioflores now you can have a `.sequelizerc` file at the root : 
```
var path = require('path')

module.exports = {
  'config': path.resolve('path', 'options.json'),
}
```

**Comment by mabdullah353** [comment]
Migration path won't work when we provide `migrations-path` key in configuration file:

When i run migration i get the following message, however i have provided "migrations-path" to a different path (See complete database.json at the end of this comment)

```bash
./node_modules/sequelize-cli/bin/sequelize  migration:create

Sequelize [Node: 8.3.0, CLI: 2.8.0, ORM: 4.4.10]

Successfully created migrations folder at "/Users/XAM/liimex/koajsapp/migrations".
Loaded configuration file "config/database.json".
Using environment "development".
New migration was created at /Users/XAM/liimex/koajsapp/migrations/20170814152035-unnamed-migration.js .
```

So the following property in `config/database.json` is ignored.
```json
...
 "migrations-path": "./database/migrations"
...
```

However, It does work via cli argument, as shown below:

```bash
./node_modules/sequelize-cli/bin/sequelize --migrations-path ./database/migrations migration:create

Sequelize [Node: 8.3.0, CLI: 2.8.0, ORM: 4.4.10]

Successfully created migrations folder at "/Users/XAM/liimex/koajsapp/database/migrations".
Loaded configuration file "config/database.json".
Using environment "development".
New migration was created at /Users/XAM/liimex/koajsapp/database/migrations/20170814151846-unnamed-migration.js .
```


My  `.sequelizerc`  file is 
```
const path = require('path')

module.exports = {
  'config': path.join('config', 'database.json'),
}
```

And My `config/database.json` file is 
```json
{
  "development": {
    "dialect": "sqlite",
    "storage": "database/db.sqlite",
    "migrations-path": "./database/migrations"
  },
  "production": {
    "dialect": "sqlite",
    "storage": "database/production-db.sqlite",
    "migrations-path": "./database/migrations"
  }
}
```

**Comment by gavinbelson** [comment]
> yes:
> 
> from the implementation:
> 
> ```
>       "--migrations-path": "The path to the migrations folder. " + clc.blueBright("Default: migrations"),
>       "--models-path": "The path to the models folder." + clc.blueBright("Default: models")
> ```
> 
> so you just have to add those flags.

@sdepold where are all these options listed? I can't seem to find them on the sequelize github..

**Comment by nastari** [comment]
The default architecture of sequelize-cli to generate the folders breaks my architecure where everything about code stay inside of the src folder. Where i change that?

**Comment by muhyidin3222** [comment]
change file .sequelizerc for location migration sequelize

    const path = require('path');
    
    module.exports = {
        'config': path.resolve('your_path/config', 'config.json'),
        'models-path': path.resolve('your_path/models'),
        'migrations-path': path.resolve('your_path/migration') }

**Comment by wkasunsampath** [comment]
Change the .sequelizerc file. Below listed all the configuration options.

```
const path = require('path');

module.exports = {
    'config': path.resolve('your_path/config', 'config.json'),
    'models-path': path.resolve('your_path/models'),
    'migrations-path': path.resolve('your_path/migration'),
    'seeders-path': path.resolve('src', 'database/seeders')
}
```

Then you should run,
`npx sequelize-cli init`
