### ISSUE TITLE
Migrations do not respect Sequelize.NOW

### ISSUE THREAD

**Issue by andrewthornton** [sequelize/cli#286]
The code below doesn't set the default time in Postgres like it does when syncing through sequelize alone. Am I missing something here? I reviewed all the docs that I can, but I haven't found much. Any help is much appreciated. 

```
 return queryInterface.createTable('organizations', {
    ...
    last_modified : {
        type: Sequelize.DATE,
        defaultValue: Sequelize.NOW
    }
})
```

**Comment by Americas** [comment]
[This piece of code](https://github.com/sequelize/sequelize/blob/master/lib/utils.js#L309) prevents that from happening for now.

Basically, a default of `NOW` is not schemable on tables, and is ignored.
