### ISSUE TITLE
Authentication fails in Node.js v6

### ISSUE THREAD

**Issue by dylanfoster** [sequelize/cli#293]
Versions:
 - node: 6.0.0
 - npm: 3.8.3
 - cli: 2.4.0
 - orm: 3.22.0

output:

```sh
Sequelize [Node: 6.0.0, CLI: 2.4.0, ORM: 3.22.0]

(node:64771) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Loaded configuration file "config/db.js".
Using environment "development".
Unable to connect to database: SequelizeConnectionError: password authentication failed for user "postgres"
```

The only difference here is the Node.js version, my config Object did not change and works properly in Node v5.10 and v5.11

**Comment by lostintime** [comment]
@dylanfoster had same issue, but it worked after re-installed all dependencies: `rm -R node_modules; npm install`.
Versions: 
- node: 6.0.0
- npm: 3.8.6
- cli: 2.4.0
- orm: 3.22.0

**Comment by sdepold** [comment]
Hm so maybe it's because of some compilation incompatibilities?

**Comment by dylanfoster** [comment]
@lostintime nice that worked. @sdepold yes seems like a compilation issue between Node 5 and 6

**Comment by charlesdg** [comment]
I have this issue with Heroku, no one encountered it?

**Comment by kevingo** [comment]
I also have this issue. Versions:

- node: 6.2.0
- cli: 2.4.0
- ORM: 3.19.3
- pg: 3.6.3

fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

Unable to connect to database: SequelizeConnectionError: password authentication failed

**Comment by charlesdg** [comment]
We resolve it with an update of pg (`4.5.5`).

**Comment by kevingo** [comment]
Thanks. It's the problem of pg indeed.

**Comment by robela** [comment]
update up works for me

**Comment by oeddyo** [comment]
strange... I just got this error. 

The configuration I have is like:

{
  "development": {
    "username": "development",
    "password": "123456",
    "database": "development",
    "host": "127.0.0.1",
    "dialect": "postgres"
  },
  "test": {
    "username": "test",
    "password": "123456",
    "database": "test",
    "host": "127.0.0.1",
    "dialect": "postgres"
  },
  "production": {
    "uername": "production_user",
    "password": "XXXX",
    "database": "production",
    "host": "XXXX",
    "dialect": "postgres"
  }
}

however whenver I run sequelize, it tries to use the user "ubuntu" to do the migration.

**Comment by oeddyo** [comment]
ubuntu@ip-172-31-1-174:~/magic-tribe$ NODE_ENV=production ./node_modules/.bin/sequelize db:migrate

Sequelize CLI [Node: 6.11.2, CLI: 3.0.0, ORM: 4.14.0]

WARNING: This version of Sequelize CLI is not fully compatible with Sequelize v4. https://github.com/sequelize/cli#sequelize-support

Loaded configuration file "mt-db/src/config/database.json".
Using environment "production".
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:236:13

ERROR: password authentication failed for user "ubuntu"
