### ISSUE TITLE
custom primary key name 

### ISSUE THREAD

**Issue by matt212** [sequelize/cli#302]
How can one declare custom primarykey name in below command line , 

sequelize model:create --name MyUser --attributes first_name:string,last_name:string,bio:text
like i wanted MyUSERID instead of just id and no date params !

**Comment by skad0** [comment]
You can disable timestamps at configuration of your model:

```javascript
var Bar = sequelize.define('bar', { /* bla */ }, {
  // don't add the timestamp attributes (updatedAt, createdAt)
  timestamps: false
})
```
[Configuration docs](http://docs.sequelizejs.com/en/latest/docs/models-definition/#configuration)

And for custom primary key see this example:
```javascript
sequelize.define('collection', {
  uid: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true // Automatically gets converted to SERIAL for postgres
  }
});
```
[Working with legacy code](http://docs.sequelizejs.com/en/latest/docs/legacy/)

**Comment by sushantdhiman** [comment]
👆

**Comment by shikhashakarwar** [comment]
Hey @sushantdhiman ,

Does it means, we can not create primary key by above model generation command. To create custom primary key I must to do this manually by modify model structure? 

Am I Correct?

If not then what is way to create custom primary key by model generation command on cli?
