### ISSUE TITLE
Support for node-webkit

### ISSUE THREAD

**Issue by ua2004** [sequelize/cli#303]
Could you please add a support for [node-webkit](http://nwjs.io/)? Currently, _sequelize-cli_ can only run in pure Node mode. Whenever you try to run a migration with _node-sqlite3_ complied for NW it says:

```
Error: Please install sqlite3 package manually
```

**Comment by felixfbecker** [comment]
Don't know how this can be implemented. The driver is required lazily from the cwd. We cannot add all drivers as dependencies, users only need one.

**Comment by ua2004** [comment]
Maybe it should require different driver depending on the environment. I may suggest several ways to implement that:
* It may detect the environment (node/node-webkit) automatically and use only one necessary driver.
* Users may pass some flag in console to indicate that node-webkit driver is required.
* Detect the environment based on config file.

**Comment by felixfbecker** [comment]
What do you mean by "environment"? How should the `require()` of the driver work differently in NW.js?

**Comment by ua2004** [comment]
The situation is a little not clear for me since I did not look through the sequelize/cli source code. You said that it uses different drivers for node and NW.js? If drivers are files then a simple `if` can be used to detect which driver should be included.

**Comment by felixfbecker** [comment]
No. I have never worked with NW.js before and don't know why it would not work. But the drivers are required like this:
```js
try {
  driver = require(process.cwd() + '/node_modules/sqlite')
} catch (e) {
  throw new Error('Please install sqlite3 manually')
}
```
