### ISSUE TITLE
Sequelize db:migrate won't update make changes I've made to the models/model_name.js files

### ISSUE THREAD

**Issue by jamesone** [sequelize/cli#307]
I've made initial migrations for all of my database tables, but I when I want to update one of the model files and apply the changes, they're not applied!

Am I doing something wrong? `sequelize db:migrate`

**Comment by Americas** [comment]
I'm not sure I understand, but that is not how `sequelize db:migrate` works. You would need to create a migrations folder, and every new change (or group of changes) you want to apply on the db would be on a new file. This way, when the `sequelize db:migrate` command is issued, it checks that new migrations exist and tries to execute them.

Depending on what your goals are, you can check ou [the sync function with force: true](https://sequelize.readthedocs.io/en/latest/api/sequelize/#syncoptions-promise) that drops and creates all models from the model files.
