### ISSUE TITLE
Running seeders and migrations in tandem, chronologically

### ISSUE THREAD

**Issue by super-cache-money** [sequelize/cli#310]
I intend to use migrations/seeders to spin up a test environment database. How do I run migrations and seeders in tandem, in the order they were created? Here's a simple example showing what I'm asking for, and why I'm asking for it.

Let's say at `time-0` I create a table using a migration, **users**:

| uname | password |
| --- | --- |
|  |  |

Now at `time-1` I write a seeder adding a record, so **users** looks like this:

| uname | password |
| --- | --- |
| supercachemoney | passw0rd |

At `time-2` I write a migration. Realising I shouldn't be thrifty with keystrokes, I rename `uname` to `username`, so **users** looks like this:

| username | password |
| --- | --- |
| supercachemoney | passw0rd |

At `time-3`, I now write another seeder to add a second row to the table:

| username | password |
| --- | --- |
| supercachemoney | passw0rd |
| steveballmer | devel0pers |

So when I spin up a test db, I'd like to run these in the following order:
- run `time-0`'s migration
- run `time-1`'s seeder
- run `time-2`'s migration
- run `time-3`'s seeder

What would be the most sane way to do this?

Do I have to write a shell script which individually runs migrations and seeders in the order I need? 

PS: This entire plan for spinning up a test environment db may be stupid. If so, please tell me!

**Comment by sushantdhiman** [comment]
I will suggest just generate new seed file (or edit old ones) if one of the column it depends on is changed. Run all migrations then run all seeds

**Comment by cyrilchapon** [comment]
WTF closing this

**Comment by cyrilchapon** [comment]
Up

**Comment by mmiszy** [comment]
Has this ever been solved, or should we just ignore `seeders` and use migrations for everything?

**Comment by waqas19921** [comment]
You can use following script for that purpose
