### ISSUE TITLE
Specify location of sequelizerc

### ISSUE THREAD

**Issue by super-cache-money** [sequelize/cli#314]
As I understand it, **.sequelizerc** only takes effect when I run `sequelize` from the same directory it's in.

I want to do something like a `sequelize db:migrate` from a different directory. What's my most elegant option?

Note that I have already defined the path to migrations, seeders, etc in my **.sequelizerc** file and first prize would be not having to repeat these definitions.

**Comment by M-Porter** [comment]
Why not have `.sequelizerc` in the base of your repo and run `sequelize` from there?

**Comment by sushantdhiman** [comment]
rc files are supposed to be in base project directory, not in some random path
