### ISSUE TITLE
Default behaviors of `models/index.js` should be to return sequelize instance

### ISSUE THREAD

**Issue by benirose** [sequelize/cli#319]
I was looking into the `models/index.js` file that is generated when you run `sequelize init`, and I see it's very similar as to what is used in the [Express Example](https://github.com/sequelize/express-example) repository. I'm wondering why this file returns a JS object with keys to all the models and a key to both the sequelize instance and the library.

I would argue that this file should return the sequelize instance, since this contains all of the models at `sequelize.models` anyways, doesn't create an unnecessary abstraction object that many developers may not be using. This will help create a streamlined interface for the CLI to use when it needs to get ahold of a project's models, and the developer can know that calling `require('./models')` in their app will always return a configured sequalize instance with their models defined.

**Comment by sushantdhiman** [comment]
What will you prefer

1. `require('models').<ModelName>`
2. `require('models').sequelize.models.<ModelName>`

I think most of us prefer `1`. Thats the reason its done in such a way. This file also returns both `sequelize`(Instance) and `Sequelize`, You can use them if you like.

**Comment by benirose** [comment]
My proposal would be `require('models').models.<ModelName>`, since `index.js` would return the `sequelize` instance. It feels pretty silly to have a redundant object of models that our `sequelize` instance is already keeping for us. Additionally, I see no benefit from having the `Sequelize` library available on the redundant models object because it's a simple `require` away anyways. If anything it's confusing because you have both a `sequelize` and `Sequelize` property. 

My concern is that returning an instance of the library being used is a more expected behavior than a custom Javascript object, which feels a bit more mysterious and uncertain.

**Comment by sushantdhiman** [comment]
1 year later :D

Current system plays nicely with import as well

```js
import {
   User,
   Order
} from '_/db';
```

In the end both models are same so there is no no much overhead either.
