### ISSUE TITLE
Environment config in multiple files

### ISSUE THREAD

**Issue by craig552uk** [sequelize/cli#323]
Hi,

Is it possible to load environment config from multiple files?
I have my SQL config in files alongside other application config, one file per environment.
e.g.
**development.json**

``` json
{
    "logging":{
        "level": "debug"
    },
    "sql": {
        "storage": "db.sqlite",
        "dialect": "sqlite"
    }
}
```

As a work-around I can do something like:
**config.js**

``` javascript
module.exports = {
  "development": require('./development.json').sql,
  "production":  require('./production.json').sql,
  "test":        require('./test.json').sql,
}
```

...but I wondered if there is native support.

**Comment by sushantdhiman** [comment]
Yes

- Use [dynamic config](http://docs.sequelizejs.com/manual/tutorial/migrations.html#dynamic-configuration) file 
- Import various configuration to that file
- Properly expose correct config to correct environment key in `module.exports`

**Comment by craig552uk** [comment]
Thanks for the reply.

As an aside, does Sequelize-CLI only support environments named `development`, `test` and `production`? Are other environment names supported? If so, are these configurable?
