### ISSUE TITLE
Provide sequelize instance to up function 

### ISSUE THREAD

**Issue by jonyrock** [sequelize/cli#326]
```
  params:  [ sequelize.getQueryInterface(), Sequelize ],
```

I am absolutely do not need Sequelize in up() function because I can get via require. U see?

What I REALLY need is the `sequelize` instance in the up function. 

https://github.com/sequelize/cli/blob/master/lib/tasks/db.js#L355

**Comment by sushantdhiman** [comment]
Why

**Comment by jonyrock** [comment]
Otherwise I have to extract sequelize instance from queryInterface and do something like this
https://gist.github.com/jonyrock/324d2d3e2ab7e305774fc674bb60bd90

**Comment by sushantdhiman** [comment]
May be you can use https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L568

**Comment by jonyrock** [comment]
Maybe. But I have no idea how to use it without documentation. Anyway, the issue was about sequelize instance. I want underline that `queryInterface.sequelize` looks weird and `this.sequlize` supposed to be "private".

If you think that I am crazy then I totally fine to close the issue )

**Comment by felixfbecker** [comment]
I am very confused why you need to define a model in a migration file. Your migration file is supposed to setup the database _for_ a model. If you need to import a model from your code, you can easily do that. So I would say this use case is not very common, and if needed, can be easily accomplished by accessing `QueryInterface.sequelize`.
