### ISSUE TITLE
Will sequelize-cli detect changes in models folder?

### ISSUE THREAD

**Issue by frogcjn** [sequelize/cli#338]
Will sequelize-cli detect changes in models folder?

**Comment by frogcjn** [comment]
I try to add a column to a model file, but `sequelize migration:create` always get an empty migration file.

**Comment by frogcjn** [comment]
`sequelize db:migrate:old_schema`

(node:4654) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Loaded configuration file "sequelize/config.json".
Using environment "development".
SequelizeDatabaseError

**Comment by frogcjn** [comment]
https://www.youtube.com/watch?v=wHTBxtk8ezo

as this video demonstrates, how can I get a feature like this? Auto detect changes in models and generated migration file.

**Comment by sebastienbarre** [comment]
I'm with you here, I see the same behavior, empty migration. In the video, the command `stukko addMigration` seems to be used, no clue what that is

**Comment by felixfbecker** [comment]
Sequelize does NOT detect changes to your model, there are open issues about this. The graceful-fs warning comes from Gulp 3, there is an open issue about this as well.

**Comment by sebastienbarre** [comment]
@felixfbecker sorry, couldn't find the specific open issues about this, I searched for "update" but didn't see an issue where I could try to give a hand implementing it. Thanks.
