### ISSUE TITLE
Expected workflow

### ISSUE THREAD

**Issue by lrojas94** [sequelize/cli#343]
Hello,

I've been wondering what the expected workflow is using the CLI. I mean, I see that it does not auto-generates model when a new migration is created, so how it is that I should work this out? 

Create Migration -> Modify/Create model ?

or

Modify/Create Model -> Create Migration?

Also, is it still necessary to run "sync" in order to use the models?.
Thanks in advance :)

**Comment by kissmygritts** [comment]
I've been using the latter. The initial migration is created when a new model is created. Future migration need to be created "by hand".

```
model:create ...
db:migrate ...
migration:create ...
```
