### ISSUE TITLE
Duplicate Foreign Key Constraint Name

### ISSUE THREAD

**Issue by lrojas94** [sequelize/cli#346]
So, I've created two tables which reference the same one (say, address and a user has an address and company too). This makes me run into this problem:

**Constraint created by sequelize:** addressId_foreign_idx

**Results:** Both tables will try to use the same constraint name, which, as you might expect, results in: 

``` bash
code: 'ER_DUP_KEY',
errno: 1022,
sqlState: '23000',
```

**Comment by felixfbecker** [comment]
Are you configuring `foreignKey` or `alias`? Need to see more code

**Comment by lrojas94** [comment]
This is what I'm doing: 

```js
return queryInterface.addColumn(
        "companies",
        "addressId",
        {
          type: Sequelize.INTEGER,
          references: {
            model: "addresses",
            key: "id"
          },
          onDelete: "SET NULL"
        })
      .then(() => {
        return queryInterface.addColumn(
          "residentialCustomers",
          "addressId",
          {
            type: Sequelize.INTEGER,
            references: {
              model: "addresses",
              key: "id"
            },
            onDelete: "SET NULL"
          })
      });
```

As you can see, both use **addressId**. but I get that the foreign key created is the same.

**Comment by m3l7** [comment]
same problem

**Comment by PaulBehrendtVentoro** [comment]
+1

**Comment by eduardrock** [comment]
Is there any solution?
I've wasted all the day trying to figure this same problem out

**Comment by sushantdhiman** [comment]
You can now use addConstraint like methods to properly name them http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html#instance-method-addConstraint
