### ISSUE TITLE
Specify specific migration in db:migrate:undo

### ISSUE THREAD

**Issue by gotrevor** [sequelize/cli#350]
Umzug provides options for specifying which migration to `down`: https://github.com/sequelize/umzug#reverting-executed-migration

I'd like to be able to specify, at least, the name of the migration I'd like to `undo`.

I imagine a feature like this might be useful for `up`, as well.

Any support for adding such a feature?

**Comment by bcaudan** [comment]
+1

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/cli/pull/387

**Comment by patil-gaurav** [comment]
`db:migrate:undo --name 20180704124934-create-branch.js` 
this will work only if you don't have relation between your model with other models.

**Comment by jsina** [comment]
@patil-gaurav but this one just revert the last migration and it's not gonna any effect to the specific migration.

**Comment by Poliedro2000** [comment]
> `db:migrate:undo --name 20180704124934-create-branch.js`
> this will work only if you don't have relation between your model with other models.

Thanks you so much @patil-gaurav
