### ISSUE TITLE
Setting options for generated migrations

### ISSUE THREAD

**Issue by caioflores** [sequelize/cli#356]
I'm using "sequelize model:create" to create my migrations, but I want to use Sequelize.UUID instead of Sequelize.INTEGER for my IDs, but the generator creates a ID with integer by default. 
There's a way to change this default generation?

I searched for it and found nothing, sorry if it's a dumb question.

**Comment by virgenherrera** [comment]
let sequelize cli create the migration without {id:uuid} mod, and then update it both the migration and model.

also i have  that issue with in my projecto, but in this time sequelize-cli does not support the mod for id:uuid :(

**Comment by sushantdhiman** [comment]
Moved https://github.com/sequelize/cli/issues/551
