### ISSUE TITLE
Composite primary key

### ISSUE THREAD

**Issue by eddiejaoude** [sequelize/cli#361]
I am trying to replicate the _auto table generation_ from the models in **Sequelize** by using the **SequelizeCli** migration for `production`. However, I noticed that **Sequelize** creates a composite primary key, however I am unable to find the equivalent in **SequelizeCli**. 

What am I missing? Thanks 😄

**Comment by sushantdhiman** [comment]
Sequelize doesnt support composite primary keys, so CLI cant add its support
