### ISSUE TITLE
Case inconsistencies 

### ISSUE THREAD

**Issue by scf4** [sequelize/cli#362]
The "getting started" examples and other pages in the Sequelize docs suggest the model var is capitalised, but the model itself defined with a lowercase first letter:

`var User = sequelize.define('user', {})`

Which looks for a table name with lowercase "users", and requires accessing the model with lowercase `sequelize.user`:

`var User = require(__dirname + '/../models/index').user;`

Then `User.find()` etc. 

This is okay so far. But the CLI produces this:

`var User = sequelize.define('User', {})`

Along with an uppercase table name and `sequelize.User`.

Now, I _would_ go with the CLI casing, but it means Sequelize will look for capitalized foreign keys—and the even the CLI itself opts for lowercase fields. 

But then the CLI's example also mixes camelCase (createdAt) with underscores (first_name) in the same model, so I'm not sure what to think...

Could we have some consistency? It seems to me that this project is actively working _against_ Sequelize.

**Comment by felixfbecker** [comment]
The convention is PascalCase model names, because models are classes in v4.

**Comment by Shefali25** [comment]
Not sure if this might have caused it.. but it seems like the sequelize_cli is converting SQL table names to lower case internally.
