### ISSUE TITLE
New release with fixes?

### ISSUE THREAD

**Issue by lumaxis** [sequelize/cli#374]
Is there anything I can do to help get a new release of this package published?
Especially the fix in https://github.com/sequelize/cli/pull/353 is pretty critical to our infrastructure and I would greatly appreciate to have a version that includes this 👍 

Thanks!

**Comment by gotrevor** [comment]
@sdepold @Americas Is there any release schedule?  
I've also got a PR that recently merged that I'd like to see deployed: https://github.com/sequelize/cli/pull/385

Also, there's been no action on this open PR for 3 weeks: https://github.com/sequelize/cli/pull/387

Thanks!
-Trevor

**Comment by gotrevor** [comment]
There's recently been a release with #353 & #385 .
@Americas @lumaxis  Close this issue out, please.

**Comment by lumaxis** [comment]
Just noticed, very glad to see it! 😊
