### ISSUE TITLE
No way to regenerate migration from existing models

### ISSUE THREAD

**Issue by SamD** [sequelize/cli#377]
Steps followed: 
- I was just getting started so put in some basic attributes to satisfy the cli to see what the models would like. 
- After this I manually modified the models so that they met the schema required.
- I then tried to regenerate using migrations:generate, nothing happened
- I removed the incorrect migration files and ran the command again nothing happened

How do I regenerate the initial migration based on existing models?

 "sequelize": "^3.24.6",
 "sequelize-cli": "^2.4.0"

Thanks

**Comment by Americas** [comment]
Hi, this functionality does not exist.. You need to alter migrations manually.

**Comment by SamD** [comment]
Thanks, yeah I figured that.
