### ISSUE TITLE
Migrations won't run with Postgres Dialect Specified

### ISSUE THREAD

**Issue by mattcphillips** [sequelize/cli#382]
I may be doing something wrong, but ran `sequelize init` and updated my config.json file so that this is what I have:

`{
    username: 'postgres',
    password: null,
    database: 'db_name',
    host: '127.0.0.1',
    port: 5432,
    dialect: 'postgres',
    pool: {
        maxConnections: 5,
        maxIdleTime: 3000
    }
}`

This config is working fine for me while I run postgres locally, but when I try to run `sequelize db:migrate` I first receive confirmation that the config loaded from the correct path and then `Error: Please install mysql package manually`

Is there a configuration step I am missing? It seems like it is defaulting to mysql, but my config file is being read from the correct location and there's no mention of mysql in my project. Is this an issue others are having?

**Comment by cjrd** [comment]
FYI: restarting my system seems to have fixed this issue?

**Comment by gotrevor** [comment]
Are you still having this problem?  cjrd seems to suggest that a reboot would help.

**Comment by corbanb** [comment]
I rebooted and still not working. Thoughts?

**Comment by corbanb** [comment]
So I dug further and install mysql on my local machine. I was then able to get past the mysql error.

Next I logged out in the `migrations.js` file as well ast eh .sequelizerc file to assure all options being ran are correct.

When the cli tries to connect I am getting the error of `connect ECONNREFUSED 127.0.0.1:3306`.

This url is no where in my configs there for not being passed into the cli. Any ideas on why this might happen?

**Comment by corbanb** [comment]
Ok so I found what my issue was in particular. I had my `NODE_ENV=local` which meant the `migrations.js` file needed a `local: {}` setup. Otherwise it was looking at the wrong config some how by default. I believe the old default was development so this changed at some point had was not documented that I found. 

Hope this helps someone.
