### ISSUE TITLE
alter table add columns, indexes, associations

### ISSUE THREAD

**Issue by manuelfink** [sequelize/cli#386]
Maybe I just oversaw it in the docs, but is it with sequelize-clie not possible to:

- alter tables to add columns
- add foreign key relations
- add unique indexes

if possible, can anyone describe how and add to samples? If not, I think this is really necessary to be added.

**Comment by gotrevor** [comment]
I primarily use the CLI for managing migrations on PostgreSQL.
I use raw SQL, rather than Sequelize, if I'm doing something DB-specific.  For example:

```
  down: function (queryInterface, Sequelize) { // eslint-disable-line no-unused-vars
    return queryInterface.sequelize.query(`
      DROP FUNCTION mm_to_numeric(text);
    `);
  },
```

Will that work for you?
