### ISSUE TITLE
db:migrate creates SequelizeMeta record when the migration gives an error.

### ISSUE THREAD

**Issue by detaybey** [sequelize/cli#392]
Sequelize [Node: 6.9.1, CLI: 2.4.0, ORM: 3.27.0]

The migration should either success, or fail. SequelizeMeta record should be generated if only the migration runs completely without errors.

Currently, sequelize-cli generates a record of the migration that was run under SequelizeMeta table regardless of fail/success.

**Comment by gotrevor** [comment]
When a migration fails, no row is written to SequelizeMeta table.  If you're seeing otherwise, that is a bug.  Can you give more details on how to reproduce?

**Comment by Hanspagh** [comment]
When I get the following error 

> Unhandled rejection SequelizeDatabaseError: column "secret" contains null values

The migration row is still written.
My migration is trying to add the a column called secret to an existing table. 
The reason for the error is that there already exists data in the table which violates the nonNull constraint.
