### ISSUE TITLE
Return exit code 1 when undo migration failed

### ISSUE THREAD

**Issue by nehaabrol87** [sequelize/cli#394]
I see that exit code 1 is returned when a migration fails but same is not handled/returned when last migration is undone (undo).
I am using sequelize 1.9.2
Is there a reason why this is as is.

I see this was fixed https://github.com/sequelize/cli/issues/110 but the corresponding PR only catches errors for ups and not downs.

https://github.com/sequelize/cli/pull/161

**Comment by nehaabrol87** [comment]
Oops I just noticed it exists in master.
Can you tell me which is the version where this first became available.

**Comment by AFBarstow** [comment]
I would like to +1/upvote getting [cba03c8f](https://github.com/sequelize/cli/commit/cba03c8f17740cd652c40103830d4cff9e44f86b) pushed to a new release since not having this is quite painful for our application. Is there a rough-ish ETA when we can expect this commit in a release?

**Comment by gotrevor** [comment]
This has also been requested over here: https://github.com/sequelize/cli/issues/374

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/cli/commit/480f3fce309f84b2bf0e0ebd8d357d6988cbf635
