### ISSUE TITLE
migration:create should not require a config path

### ISSUE THREAD

**Issue by teogeos** [sequelize/cli#395]
`migration:create` throws an error if it can't find a config file to run. This doesn't make sense since creating a migration file shouldn't depend on a database configuration. Indeed, you can see [here](https://github.com/sequelize/cli/blob/master/lib/tasks/migration.js#L27) that the program throws if no config is found, but then nothing is done with the `config` variable since it's useless.

Is there a reason for this?

**Comment by kenhowardpdx** [comment]
I just tested this out and it did indeed throw the error when an invalid path was provided. If you don't provide the config argument the migration is created.

**Comment by sushantdhiman** [comment]
Its fixed with v3
