### ISSUE TITLE
getting error while executing commands like - npm install underscore or npm install node-dev through NPM: (node:7732) fs: re-evaluating native module sources is not supported. 

### ISSUE THREAD

**Issue by sanjayphadtare** [sequelize/cli#398]
(node:7732) fs: re-evaluating native module sources is not supported. If you are
 using the graceful-fs module, please update it to a more recent version.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\sanjay.p\
\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node
-dev"
npm ERR! node v6.9.2
npm ERR! npm  v2.12.0

npm ERR! process.getuid is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
/
npm ERR! Please include the following file with any support request:
npm ERR!     F:\node_training\7-Node-Package\7-1\npm-debug.log

**Comment by sushantdhiman** [comment]
Spend some effort on formatting and follow the issue template. Use stackoverflow for questions and general errors

**Comment by sushantdhiman** [comment]
Related https://github.com/sequelize/cli/issues/291
