### ISSUE TITLE
It seems v2.5.0 is released, but npm only has v2.4.0

### ISSUE THREAD

**Issue by artlogic** [sequelize/cli#401]
NPM briefly had v2.5.0 available, but since has reverted to v2.4.0 - while the repo still appears to be at v2.5.0. Is there a problem at NPM?

https://www.npmjs.com/package/sequelize-cli

**Comment by Americas** [comment]
Yeah, when i published it I thought it was just a caching problem, when I tried to republish it, I got a `"You cannot publish over the previously published version 2.5.0."` message, so I just left it alone. Version 2.5.1 worked, though.

**Comment by artlogic** [comment]
Thanks for resolving so quickly!
