### ISSUE TITLE
Migration created on model change

### ISSUE THREAD

**Issue by nitish24p** [sequelize/cli#405]
I've worked with the doctrine orm with symfony, where a migration file is created when the model is changed, is there a way to do the same in sequelize, where i update my model by adding a column or a FK and the concerned migration is created, or do i have to make a blank migration and use the query interface. Any help would be good.

**Comment by nitish24p** [comment]
@Americas ^^ any idea??

**Comment by sushantdhiman** [comment]
Moved https://github.com/sequelize/cli/issues/388
