### ISSUE TITLE
model validation using sequelize-cli

### ISSUE THREAD

**Issue by mortenko** [sequelize/cli#416]
Hi,
I created migrations and models using sequelize-cli commands. Then I ran `sequelize db:migrate`  and created tables in database. Now, I'm trying to insert some initialize data using seed method. 

The problem is when I'm running seed using `sequelize:seed:all command`,  data are saved in database although they didn't pass my validation. 

It's possible to define validations rules on model layer ?  I saw some examples in documentation  how to write validation rules but I think it's not suitable for sequelize-cli approach. 

here is my **customer.js** model
```
module.exports = (sequelize, DataTypes) => {
  const Customer = sequelize.define('Customer', {
    name: {
      type: DataTypes.STRING,
      validate: {
        min: 3,
        max: 12,
      },
    },
    surename: {
      type: DataTypes.STRING,
    },
    phone: {
      type: DataTypes.STRING,
    },
    email: {
      type: DataTypes.STRING,
      validate: {
        isEmail: true,
        min: 5,
        max: 64,
      },
    },
  }, {
    classMethods: {
      associate(models) {
        Customer.hasOne(models.CustomerPhoto);
        Customer.hasMany(models.Orders);
      },
    },
  });
  return Customer;
};
```
 Here in my  **seed file**, I'm trying to save data, which cannot pass my validation defined in my customer model. 
```
  up(queryInterface, Sequelize) {

    return queryInterface.bulkInsert('Customers', [{
      name: 'Jo',
      surename: 'Coltraine',
      phone: '+4219027202854',
      email: 'jank',
      createdAt: new Date(),
      updatedAt: new Date(),
    }], {});

  },
```
**Question:** How can I defined validation rules on model layer ?  When I run seed method ..it will fail when it don't fit  validation .
Thanks.

**Comment by jonesmac** [comment]
I believe this is still an issue.  I have `return queryInterface.bulkInsert('Users', fields, { validate: true })` according to the [docs](https://sequelize.org/master/class/lib/query-interface.js~QueryInterface.html#instance-method-bulkInsert) but validations do not happen.  I went into the REPL and verified that if I try to bulk create, they fail.  Its only when the seed runs do I lose validations.  

@mortenko did you ever solve this?

**Comment by papb** [comment]
Indeed `bulkInsert` does not run validations, you have to use bulkCreate instead

**Comment by jonesmac** [comment]
@papb tried that as well with no luck.  Here's my seed file:
```const bcrypt = require('bcrypt');
const User = require('../components/users');

module.exports = {
  up: (queryInterface, Sequelize) => {
    const fields = [{
      firstName: 'John',
      lastName: 'Doe',
      email: 'john.doe@gmail.com',
      password: bcrypt.hashSync('password', 10),
      createdAt: new Date(),
      updatedAt: new Date()
    }];
    return User.bulkCreate(fields, { validate: true });
    // return queryInterface.bulkInsert('Users', fields, { validate: true })
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Users', null, {});
  }
};
```

My relevant model code:
```
User.init({
    firstName: Sequelize.STRING,
    lastName: Sequelize.STRING,
    email: {
      type: Sequelize.STRING,
      allowNull: false,
      unique: true,
      validate: {
        isEmail: true,
        notEmpty: true    
      }
    },
```

And here's my db after running it a few times:
![image](https://user-images.githubusercontent.com/885417/63942560-fbeceb80-ca3b-11e9-9cd5-1864c21893bf.png)

**Comment by jonesmac** [comment]
@papb please disregard.  I thought my db had been updated with the unique constraint but it wasn't 😭 

Still find it interesting that even though the model had the validation, it didn't fail there until I added the unique constraint at the db level.  I would have thought model validations would have caught that. 🤷‍♂

**Comment by papb** [comment]
The unique constraint is only checked at the database level, not at sequelize level

(I will soon be pushing a docs update that clarifies this!)

**Comment by jonesmac** [comment]
@papb sounds great!  Let me know when you push it up if you would like a reviewer
