### ISSUE TITLE
db:seed does not run all the seeds 

### ISSUE THREAD

**Issue by mateusluizfb** [sequelize/cli#419]
Only db:seed:all run all the seeds, which is not documented. 

```
node_modules/.bin/sequelize db:seed

Sequelize [Node: 4.2.6, CLI: 2.5.1, ORM: 3.30.1, mysql: ^2.13.0]

Loaded configuration file "config/config.json".
Using environment "development".
Unspecified flag "seed". Check the manual for further details.
```

There's some details in this closed issue: https://github.com/sequelize/cli/issues/250

**Comment by hyber1z0r** [comment]
This seems like it's intentional. If you run `sequelize help:db:seed` it outputs 

```
COMMANDS
    sequelize db:seed -- Run specified seeder.
```
So it's for running specific seeders by using the `--seed` flag.

Where as `sequelize help:db:seed:all` outputs

```
COMMANDS
    sequelize db:seed:all -- Run every seeder.
DESCRIPTION
    The command runs every existing seed file in alphabetical order.
```

**Comment by mateusluizfb** [comment]
Sorry for misinterpretation, after you noticed that i've read again the documentation on https://github.com/sequelize/cli and made sense, thanks @hyber1z0r!
