### ISSUE TITLE
args.env turned into array if set multiple times, causing command to fail

### ISSUE THREAD

**Issue by rayshan** [sequelize/cli#42]
`0.2.5`

If `config.json` has `'env': 'development'` set, and CLI uses `config.json`, as well as `--env development`, `args.env` becomes `['development', 'development']`, causing CLI command to fail.

The correct behavior should be `--env development` overriding what's in `config.json`.

cc @gcatto

**Comment by tylerFowler** [comment]
+1 I'm actually still seeing this in the 1.7.0 CLI.

**Comment by paulxtiseo** [comment]
+1, I think.

When I run `sequelize db:migrate --migrations-path 'migrations/postgres' --config 'postgres/config.json'`, `resolve()` throws an error in `getConfigFile()`.

```
Starting 'db:migrate'...
    at Object.posix.resolve (path.js:439:13)
    at Object.module.exports.getConfigFile (/usr/local/lib/node_modules/sequelize-cli/lib/helpers/config-helper.js:13:19)
    at Object.module.exports.configFileExists (/usr/local/lib/node_modules/sequelize-cli/lib/helpers/config-helper.js:24:31)
    at getMigrator (/usr/local/lib/node_modules/sequelize-cli/lib/tasks/db.js:211:22)
```

My `.sequelizerc` is set as:
```
var path = require('path')
module.exports = {
  'config': path.resolve('migrations', 'config.json'),
}
```
Looking at `args.config` in `getConfigFile` when I run the CLI line with --config, it seems to be an array:
```
[ 'migrations/postgres/config.json',
  '/Users/ptiseo/Documents/Repositories/Mailroom/migrations/config.json' ]
```

This is with CLI v1.8.3.

**Comment by sdepold** [comment]
alright. let's fix this

**Comment by sdepold** [comment]
boom landed in master. I will wait for another PR till I release a new patch version

**Comment by sdepold** [comment]
and it's live as 1.9.1

**Comment by rayshan** [comment]
Thanks!
