### ISSUE TITLE
db:seed show successful migration but do not upload anything in SQLite  

### ISSUE THREAD

**Issue by abuzarhamza** [sequelize/cli#434]
I am trying to insert the dummy data using sequelize-cli command

`sequelize db:seed --seed seeders/20170212081140-subject_tags.js`

here is my config file
```
{
  "development": {
    "username": "root",
    "password": null,
    "database": "database_development",
    "host": "127.0.0.1",
    "dialect": "sqlite",
    "seederStorage": "sequelize",
    "storage": "./test"
  }
}
```
and here my seeder file

```
use strict';

module.exports = {
  up: function(queryInterface, Sequelize) {

    return 
      queryInterface.bulkUpdate('subject_tags', [

      {
        tag: 'agricultural-sciences',
        tag_description: '',
        subject_category: 'biological_&_medical_sciences',
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        tag: 'biochemistry',
        tag_description: '',
        subject_category: 'biological_&_medical_sciences',
        createdAt: new Date(),
        updatedAt: new Date()
      }, {
        tag: 'bioinformatics',
        tag_description: '',
        subject_category: 'biological_&_medical_sciences',
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ] , {});
  },

  down: function(queryInterface, Sequelize) {
     return 
      queryInterface.bulkDelete('subject_tags', null, {});

  }
}; 
```

Though I am getting the status

```
Using environment "development".
== 20170212081140-subject_tags: migrating =======
== 20170212081140-subject_tags: migrated (0.053s)
```
I tried `bulkCreate` and `bulkInsert` in the seed file , all of them run successful, but data does not get inserted into the table the data does not get inserted. Is I am doing something wrong?

**Comment by VictorVuSon** [comment]
sequelize db:seed:all
it worked for me.

**Comment by joaku** [comment]
Ok. For some reason, when you run a seed, if it's validations fails, there is not error msg. It looks like it ran succesfuly, but no data get's inserted.

This is driving me crazy, because I can not debug this. Anyone has any idea?

**Comment by tswaters** [comment]
```
  up: function(queryInterface, Sequelize) {
    return 
      queryInterface.bulkUpdate('subject_tags', [
```

You have a return on a single line - this exists the function.  

You need to include `queryInterface.bulkUpdate` on the same line or wrap it with parenthesis

**Comment by sushantdhiman** [comment]
issue is blank line after `return`, code never executes queryInterface and stuff
