### ISSUE TITLE
Requesting help on how to contribute correctly: How to run tests and how to extend arguments?

### ISSUE THREAD

**Issue by asishallab** [sequelize/cli#435]
Dear `sequelize / cli` team,

thank you very much for providing such a useful tool.

I'm _not_ a newby to Javascript, but I _am_ a newby to `NodeJS` programming.
Hence, my following questions may seem a little greenhornish.

My goal is simple, I want to extend the task `model:create`  to accept another argument `associations`, e.g. 
    
    sequelize model:create --name User --attributes 'name:string, email:string' --associations 'Todo: hasMany'
    sequelize model:create --name Todo --attributes 'name:string, description:string, urgency:integer' --associations 'User:belongsTo'

I would want the outcome in the generated model and migration files to be the usual, with the following extensions:

    // user.js
    classMethods: {
       associate: function(models) {
         User.hasMany(models.Todo);
       }
     }

    // todo.js
    classMethods: {
      associate: function(models) {
        Todo.belongsTo(models.User);
      }
    }

And, of course in the migration of `Todo`:

    // <date>-create-todo.js
    user_id: {
        type: Sequelize.INTEGER,
        references: {
            model: 'User',
            key: 'id'
        },
        onUpdate: 'cascade',
        onDelete: 'cascade'
    }

So, I [forked your repository](https://www.github.com/asishallab/cli) and edited these files:

* [`lib/assets/migrations/create-table.js`](https://github.com/asishallab/cli/blob/master/lib/assets/migrations/create-table.js)
* [`lib/assets/models/model.js`](https://github.com/asishallab/cli/blob/master/lib/assets/models/model.js)
* [`lib/tasks/model.js`](https://github.com/asishallab/cli/blob/master/lib/tasks/model.js)

Unfortunately, I can't even get the tests up and running. 
* How do I supply a `config.json` for my local database installation for the test suite? 
* Also, how do I specify the new command line argument? 
* Most importantly, what do I need to do, to mould my changes into a working contribution of `sequelize/cli`?

Help will be most appreciated. 
Thank you very much and have a great day!

**Comment by sushantdhiman** [comment]
New contribution guidelines are up

- https://github.com/sequelize/cli/blob/master/CONTRIBUTING.md#fixing-bugs-or-implementing-features
- `npm test` now use `SQLite` by default which require no database configuration for local testing
