### ISSUE TITLE
Configuration URL property not read

### ISSUE THREAD

**Issue by dmorrow** [sequelize/cli#436]
The docs state that `url` is an acceptable param to define the database url.  However, it doesn't seem to be picking it up.  

        {
            "development":  {
              "url": "mysql://root:password@mysql_host.com/database_name",
              "dialect": "mysql"
            }
        }

I don't see any code in `db.js/getSequelizeInstance()` that would pick up the url property

**Comment by framled** [comment]
in fact, when i migrate I get 
```
Error: Access denied for user ''@'localhost' (using password: NO)
ER_ACCESS_DENIED_ERROR 
```
