### ISSUE TITLE
How to run specify seed file?

### ISSUE THREAD

**Issue by TangMonk** [sequelize/cli#437]

**Comment by jeppester** [comment]
If you run `sequelize help:db:seed` you will get the available options for `db:seed`:

```
COMMANDS
    sequelize db:seed -- Run specified seeder.

DESCRIPTION
    The command runs every existing seed file.

OPTIONS
    --env              The environment to run the command in. Default: development
    --coffee           Enables coffee script support. Default: false
    --config           The path to the config file. Default: config/config.json
    --options-path     The path to a JSON file with additional options. Default: none
    --migrations-path  The path to the migrations folder. Default: migrations
    --seeders-path     The path to the seeders folder. Default: seeders
    --models-path      The path to the models folder.Default: models
    --url              The database connection string to use. Alternative to using --config files. Default: none
    --seed             List of seed files to run.
```

Use the `--seed` option to provide a specific seed to run:
`sequelize db:seed --seed [seed file name]`

The provided file name should be the name of the seeder file inside your seeders path.

**Comment by demian85** [comment]
Great, sequelize just doesn't care about my seed file, it just executes nothing.

**Comment by wmede-esens** [comment]
@JD-sixberries 
Install sequelize-cli on your project.
And you should run `npx sequelize-cli db:seed --seed 20191011121208-update-feature.js`

**Comment by EvertonLMsilva** [comment]
npx sequelize-cli db:seed:undo --seed 20191011121208-update-feature
anymore.

**Comment by james-skills** [comment]
I ran the following command on CLI but got error like this,
npx sequelize-cli db:seed --seed ./db/seeders/20241127174907-patient-information-type.js

Sequelize CLI [Node: 18.20.2, CLI: 6.6.2, ORM: 6.37.5]

Loaded configuration file "config/database.json".
Using environment "development".

ERROR: Migration is not pending: 20241127174907-patient-information-type.js

Do you have any idea?
