### ISSUE TITLE
Promise warning in gulp-helper

### ISSUE THREAD

**Issue by mliszewski** [sequelize/cli#439]
I am getting the following warning from the code in gulp-helper when I load a config via a promise. 

Warning: a promise was created in a handler at /node_modules/sequelize-cli/lib/helpers/gulp-helper.js:17:16 but was not returned from it. I think the issue is a missing return on the line indicated. https://github.com/sequelize/cli/blob/master/lib/helpers/gulp-helper.js#L17

**Comment by gotrevor** [comment]
I'm seeing the same warning.
To reproduce, you may need to set `BLUEBIRD_DEBUG=1`
