### ISSUE TITLE
cannot enable cancellation after promises are in use

### ISSUE THREAD

**Issue by ashnamuh** [sequelize/cli#449]
Hi, i'm facing following error. I don't what is wrong.. 

### What you are doing?

I'm trying to run a migration:

`20170420000245-alter-table-for-idea.js`
```js
'use strict';

const Participation = require('../models/').Participation;

module.exports = {
  up: (queryInterface, Sequelize, done) => {
    return queryInterface.sequelize.query(`ALTER TABLE "${Participation.getTableName()}" ALTER COLUMN "introduction" TYPE text;`)
      .then(() => done());
  },

  down: (queryInterface, Sequelize, done) => {
    return queryInterface.sequelize.query(`ALTER TABLE "${Participation.getTableName()}" ALTER COLUMN "introduction" TYPE text;`)
      .then(() => done());
  }
};

```
### What do you expect to happen?

I was expecting the migration to run successfully.

### What is actually happening?

![image](https://cloud.githubusercontent.com/assets/14067417/25208598/ae20d1b4-25b0-11e7-85c6-92ef3d289f09.png)

Dialect: postgres
Database version: 9.3
Sequelize CLI version: 2.7
sequelize version: 3.30.4
node version: 6.10.2

**Comment by sushantdhiman** [comment]
Looks like an userland issue, need more details
