### ISSUE TITLE
Rollback database when a migration fails automatically.

### ISSUE THREAD

**Issue by sushantdhiman** [sequelize/cli#455]
Hi! Is there a way to make a rollback when a migration fails in the middle? In my development environment occurs many times then I have to make the rollback manually (remove new table, column, etc). I wouldn't like it occurs on production. I'm using alembic in python in other project, for instance, and when something wrong happens the migration is rolled back automatically.

Migrated from https://github.com/sequelize/sequelize/issues/7508

**Author :** @ezequielrozen

**Comment by Americas** [comment]
There is no automatic way to do it as of now, but you can run the migration in a transaction, that way, the migration is atomic.

**Comment by sushantdhiman** [comment]
Migrated to https://github.com/sequelize/cli/issues/532 , Atomic migration will solve this issue
