### ISSUE TITLE
There should be no quotes for config.js export vs. config.json example

### ISSUE THREAD

**Issue by entrecoder** [sequelize/cli#456]
module.exports = {
    "production": {
        "hostname": process.env.DB_HOSTNAME
    }
}

Should be:

module.exports = {
    production: {
        hostname: process.env.DB_HOSTNAME
    }
}

**Comment by Americas** [comment]
Both are valid, though I do prefer no quotes. A PR is always welcome.

**Comment by sushantdhiman** [comment]
Its not an issue nor feature request, both quote and unquoted versions are valid. A PR is still welcomed
