### ISSUE TITLE
nsp check vulnerability

### ISSUE THREAD

**Issue by mihaidma** [sequelize/cli#466]
`nsp check` warns that sequelize-cli is vulnerable to a RegExp DoS issue on this path:
`sequelize-cli@2.7.0 > gulp@3.9.1 > vinyl-fs@0.3.14 > glob-stream@3.1.18 > minimatch@2.0.10 `

**Comment by Americas** [comment]
This is a known issue with gulp. Fortunately, that code is not used in a server, so a DoS attack is hardly an issue.

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/cli/commit/480f3fce309f84b2bf0e0ebd8d357d6988cbf635
