### ISSUE TITLE
sequelize-cli doesn't handle VIRTUAL fields.

### ISSUE THREAD

**Issue by kukukk** [sequelize/cli#469]
Hi,

To avoid duplicating model definition (in models and in migrations) I'm using the following code in the migrations to generate the tables directly from the model definition.
```
let model = require('../models').User;

module.exports = {
    up: (queryInterface, Sequelize) => {
        queryInterface.createTable(model.tableName, model.attributes, model.options);
    },

    down: (queryInterface, Sequelize) => {
        queryInterface.dropTable(model.tableName);
    },
};
```

It worked well until I tried to add a VIRTUAL field to my model. With a VIRTUAL field added to my model I get the following error when I run the migration:
```
Unhandled rejection SequelizeDatabaseError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VIRTUAL
```
Is it possible to tell sequelize-cli to ignore fields with VIRTUAL type?

I'm using:
  - node: v6.10.0
  - sequelize: v4.0.0
  - sequelize-cli: v2.7.0

**Comment by Americas** [comment]
The cli is not in charge of interface methods, sequelize is.

**Comment by sushantdhiman** [comment]
Yeah you are trying to create a table with virtual type, just pass the real attributes to createTable
