### ISSUE TITLE
db:migrate cli does not work if URL arg has special char

### ISSUE THREAD

**Issue by wascou** [sequelize/cli#475]
Using this CLI command :

`./node_modules/.bin/sequelize db:migrate --url=${MYSQL_URL}`

and with a password having either `(` or `[` or whatever used in reg exp, then we have :

`Invalid regular expression`

Which is not nice.

-----
"sequelize": "^3.30.2",
    "sequelize-cli": "^2.5.1",

**Comment by sushantdhiman** [comment]
Can you post full error thrown ?

**Comment by wascou** [comment]
`$ ./node_modules/.bin/sequelize db:migrate --url="mysql://user:Passwo)rd@server.com:3306/database"

Sequelize [Node: 8.1.3, CLI: 2.7.0, ORM: 4.1.0]

Invalid regular expression: /:?Passwo)rd@/: Unmatched ')'`

**Comment by sushantdhiman** [comment]
`Invalid regular expression: /:?Passwo)rd@/: Unmatched ')'` , just this ??, there must be file paths and error trace

**Comment by wascou** [comment]
Nope. Any suggestion to debug it ?

**Comment by manfrin** [comment]
You'll need to encode it. However, if the character is `:`, then it will fully break. I have a PR open to fix that.
