### ISSUE TITLE
`sequelize init` Incorrectly writes path to config.json

### ISSUE THREAD

**Issue by djbreen7** [sequelize/cli#478]
After running `sequelize init`, the index.js file in the models folder specifies an invalid path to config.json due to the back-slashes being read as escape characters.

```javascript
var config    = require(__dirname + '/..\config\config.json')[env];
```

This throws an error:
```
Error: Cannot find module '<path_to_directory>\models/..configconfig.json'
```

**Should be**
```javascript
var config    = require(path.join(__dirname + './../config/config.json'))[env];
```

I'm happy to contribute, but the tests won't run for me locally. I'm on Windows 10/powershell. I also tried the built in bash terminal that Windows has now, but no dice.  I get an error `<path-to-binary>\sequelize is not recognized as an internal or external command` from the tests. Works fine when I run `sequelize` on my own though.

_Edit: Simplified_

**Comment by vidjuheffex** [comment]
Same issue here, I changed mine to 
```
var config    = require(__dirname + '/../config/config.json')[env];
```
Doesn't seem to affect the Mac users here.

I'd be happy to contribute as well, but I couldn't not find strings that looked like that I'm trying to modify

**Comment by djbreen7** [comment]
@vidjuheffex: I'm not sure why I was trying to overcomplicate it with the escape characters and `path.join`. Must've been past my bed time. I've edited my initial issue to reflect your code. Confirmed it works on mine. I think I see how to fix this. I might be submitting a PR here soon.

**Comment by djbreen7** [comment]
I'm digging around in config.helper.js. It looks like it needs to have `path.normalize` implemented somewhere.

**Comment by djbreen7** [comment]
Duplicate of #365. My bad, but submitted a fix anyway :)
