### ISSUE TITLE
No Gulpfile Found (2.7.0)

### ISSUE THREAD

**Issue by ablankenship10** [sequelize/cli#480]
```
yarn sq v0.24.6
$ sequelize 

Sequelize [Node: 8.1.3, CLI: 2.7.0, ORM: 4.2.1]

No gulpfile found
error Command failed with exit code 1.
```

There is no gulpfile in the package from npm

![Package Files](https://user-images.githubusercontent.com/1980841/27983860-80284c86-63f1-11e7-9985-a574359b6b14.png)

**Comment by ablankenship10** [comment]
This seems to be the result of a call to `yarn clean`. Not sure if this is something for Yarn to fix or if theres some way to mark the gulpfile as necessary within this project.

**Comment by axetroy** [comment]
Same probmle.

whatever sequelize-cli or sequelize ORM. I have meet many bugs just in 1 day I used.

somebody complain in other community i ever seen

It make me feel like that : "This orm is not for production yet".

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/cli/commit/480f3fce309f84b2bf0e0ebd8d357d6988cbf635
