### ISSUE TITLE
How to set character limit for string type

### ISSUE THREAD

**Issue by ptums** [sequelize/cli#488]
I am creating a model called Post and this my command

```
sequelize model:create --name Post --attributes id:integer username:string user_posts:string
```

how do specify a character limit for the string datatype?

**Comment by ptums** [comment]
Any updates? If not I'll close this issue. But I still think its good for people to know.

**Comment by RobertShaw1** [comment]
I think the link below might provide some insight.
[http://corpus.hubwiz.com/2/node.js/16295118.html](http://corpus.hubwiz.com/2/node.js/16295118.html)

**Comment by ptums** [comment]
Nice thanks that works!
