### ISSUE TITLE
Unable to connect to database: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by MarkusPint** [sequelize/cli#489]
Using:
Postgres
Node version 6.6.0
Sequelize version 4.4.0 
CLI version: 2.7.0

When running "sequelize db:migrate" getting the error:
Unable to connect to database: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

**Comment by axetroy** [comment]
https://github.com/sequelize/sequelize/issues/7997
