### ISSUE TITLE
Migrations in different projects, which use the same DB

### ISSUE THREAD

**Issue by TK95** [sequelize/cli#492]
Greetings!

We have two different projects which use Sequelize migrations, but each project uses the same database, as a result it turned out the we have inconsistencies in our database. Here is an example:
Let's assume that we have 2 project with some migration files.

Project - 1 
migration-1
migration-2

Project - 2
migration - 3

Flow:
1) Project 1 applies migration-1 and migration-2
2) Project 2 applies migration-3
3) After first two steps SequelizeMeta table will look like:

name
migration-1
migration-2
migration-3

4) Then Project 2 wants to undo all migrations.  After executing sequelize migration:undo:all command we will get an error that says "migration-1 is not found"

Is there any way how to avoid this error? 

P.S. I know that it's a quite bad when two separate project use the same DB, but I can't do anything with that.

**Comment by sushantdhiman** [comment]
Because both projects share db, models and migrations, I would suggest aggregating models and sequelize setup to its own repo.

This way project A and project B can include this central sequelize-setup repo, run migration and be aware of changes made by either team A or team B

**Comment by TK95** [comment]
@sushantdhiman , thanks for the answer! I think we can go with that way.

**Comment by sushantdhiman** [comment]
Great
