### ISSUE TITLE
2.8.0?

### ISSUE THREAD

**Issue by gotrevor** [sequelize/cli#495]
The [README](https://github.com/sequelize/cli/blob/master/README.md#timestamps) references `v2.8.0`, but it looks like that version has not yet been released.

This section of the README was added in this commit:
https://github.com/sequelize/cli/commit/a0f471c1b88a8b95c201e5568d733e6874697d41

Is 2.8.0 imminent, or should the doc be updated to indicate that this feature is not yet released?

**Comment by sushantdhiman** [comment]
Released https://github.com/sequelize/cli/releases/tag/v2.8.0
