### ISSUE TITLE
Fork gulp tasks into gulp-sequelize and reintegrate.

### ISSUE THREAD

**Issue by dkushner** [sequelize/cli#5]
Since gulp has already been introduced as a dependency of the CLI binary, and most of the binary's functionality is based on a set of gulp tasks, I propose the creation of a separate gulp-sequelize project that implements these tasks in a way that conforms to gulp best practices.

After this has been completed, it should be relatively trivial to reintegrate with this standalone binary by simply making gulp-sequelize a package dependency and interacting with its tasks programmatically (as the binary already does). 

The advantage of this is that it provides a set of functional tasks to developers who already have an existing gulp-based workflow while simplifying the development of the standalone binary.

**Comment by brad-decker** [comment]
@sdepold Is there a way to use the gulp tasks in our own gulp file currently? This is a great feature and will simplify build processes.

**Comment by sdepold** [comment]
Can you describe the setup. Which tool should use your own gulp file?

**Comment by brad-decker** [comment]
We want to run seeds on our test database for testing, and to run every time before Travis runs. We have a series of functions that run in order and the seed:create command is one.

For now just using a gulp plugin to run commands on shell.

**Comment by sdepold** [comment]
So the gulpfile itself is here https://github.com/sequelize/cli/blob/master/lib/gulpfile.js

**Comment by sdepold** [comment]
And the task is defined here https://github.com/sequelize/cli/blob/master/lib/tasks/seed.js#L21-L47

**Comment by sdepold** [comment]
You might be able to load the gulpfile and to use the respective task. but I'm not entirely sure how hard that is

**Comment by timini** [comment]
Has anyone managed to run any of the sequelize tasks from their local gulpfile? 

This would be very useful, but at the minute I see is it blocked by the arg creating code in the bin/sequelize file.

**Comment by sdepold** [comment]
AFAIK nothing happened here.

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/cli/commit/480f3fce309f84b2bf0e0ebd8d357d6988cbf635
