### ISSUE TITLE
No meta information on seeders

### ISSUE THREAD

**Issue by jdgreenberger** [sequelize/cli#518]
When creating and running migrations, migration information is automatically added to a `SequelizeMeta` table, presumably so that the sequelize CLI knows which migrations have been run and will not rerun an existing migration when calling `db:migrate`. Seeders on the other hand, do not store any meta information, which causes them to be rerun every time when running `db:seed:all`. Is this intentional behavior, or do I need to lump my seeders in with database migrations in order to leverage the meta table?

**Comment by kuzmenko1256** [comment]
@jdgreenberger see documentation http://docs.sequelizejs.com/manual/tutorial/migrations.html#seed-storage

**Comment by jdgreenberger** [comment]
I see the issue was addressed in V4..will close it down.
