### ISSUE TITLE
Unable to pass multiple seeding files to db:seed

### ISSUE THREAD

**Issue by mattia85** [sequelize/cli#523]
Hi all,
i'm trying to execute the following command without success:
`sequelize db:seed --seed server/seeders/seed1.js, server/seeders/seed2.js --url $DB_URL`

The result is that only seed2 will be executed. 
The documentation say this: **--seed  List of seed files to run.**
Someone can explain me how to pass multiple files?

Thanks

**Comment by sushantdhiman** [comment]
Its a bug that I found out while working on next release, should be fixed in next release if no one submits a PR first.

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/cli/commit/480f3fce309f84b2bf0e0ebd8d357d6988cbf635
