### ISSUE TITLE
options not set properly

### ISSUE THREAD

**Issue by richardpringle** [sequelize/cli#526]
using sequelize-cli 3.9.1 and sequelize 3.24.1

command:
```
sequelize db:migrate --config <path_to_config>.json
```

config:
```json
{"database":"db","username":"ec2-user","password":"password","options":{"host":"mydb.rds.amazonaws.com","dialect":"mysql","logging":null,"pool":{"maxConnections":5,"maxIdleTime":30}}}
```

The options object that is parsed by the cli is as follows:
```node
{ logging: [Function: logMigrator],
  options:
   { host: 'mydb.rds.amazonaws.com',
     dialect: 'mysql',
     logging: null,
     pool: { maxConnections: 5, maxIdleTime: 30 } } }
```

and then passed into `new Sequelize(database, username, password, options)`... but the object that should really get passed into the `Sequelize` constructor is `options.options`.

**Comment by richardpringle** [comment]
I know the easy fix is to just update that config file but I should be able to use the same config files for both my app and the cli.

**Comment by sushantdhiman** [comment]
Sorry but `sequelize-cli` and `Sequelize` use different type of configuration

**Comment by richardpringle** [comment]
I don't understand why you wouldn't use the same configuration structure
