### ISSUE TITLE
Migrations. Atomic operations

### ISSUE THREAD

**Issue by TK95** [sequelize/cli#532]
Greetings!

Let's consider example before we start talking about issue. Here it is:
```
 up: function (queryInterface, Sequelize) {
      let migrations = [];

      migrations.push(queryInterface.removeColumn('test', 'name'));
      migrations.push(queryInterface.removeColumn('test', 'age'));

      return Promise.all(migrations);
  },
```

So, here we have example of migration which removes 2 columns from 'test' table. Let's assume that second command (which deletes age column) fails for some reasons. And here is the issue. If complex migration even partially applied, Seqeulize still will count it like a successful one, it means that Sequelize added entry into SequelizeMeta table which represents recently 'applied' (actually, partially applied) migration name.

Can Sequelize somehow provide atomic operations? 
And as consequential question, can Sequelize force 'down' migration? It's related to case, which I described above. Ideally code inside 'down' function fully depends on successful 'up' function and if it turned out that 'up' function is broken, 'down' also will be broken. So, I would like to force  down migration in order to skip broken part of 'up' migration and rollback other part.  

P.S. I know we can have atomic operations if I will write only one change per migration, but it seems to me a bit complicated(Having a dozens small files).

**Comment by vidangelops** [comment]
We also need this.

**Comment by TK95** [comment]
If anyone comes across this issue, I can give you good advice. Just wrap your migration statements into a transaction. That will provide atomicity.
