### ISSUE TITLE
Cannot execute seeder multiple times

### ISSUE THREAD

**Issue by mattia85** [sequelize/cli#533]
Hi,
i would like to execute the same seeder multiple times without getting errors, like migration system.
I'm using _sequelize_ as `seedStorage`, but executing the same seed multiple times i get this errore:
**Seed file failed with error: Migration is not pending: configuration-data.js Error: Migration is not pending: configuration-data.js**

Why **cli** returns an error?

**Comment by pavel-ismailov** [comment]
To be able to run seeder again you need to delete info about previous seed operation from table `SequelizeMeta`. Just remove from there row with your seeder file name.
