### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by mikbur** [sequelize/cli#538]
## What you are doing?
I want to create a new migrationfile witch worked in sequelize-cli 2.8.0 but not with 3.0.0-2

```js
// code here
```

## What do you expect to happen?
I wanted a new migrationfile

## What is actually happening?
node --nolazy --use_strict --harmony ./scripts/buildconf.js && sequelize migration:create   --config ./scripts/config.json

Sequelize [Node: 8.4.0, CLI: 2.8.0, ORM: 4.8.3]

No gulpfile found

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mikbur\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dbmigratecreate"
npm ERR! node v8.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! mmk-es6@1.0.0 dbmigratecreate: `node --nolazy --use_strict --harmony ./scripts/buildconf.js && sequelize migration:create   --config ./scripts/config.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mmk-es6@1.0.0 dbmigratecreate script 'node --nolazy --use_strict --harmony ./scripts/buildconf.js && sequelize migration:create   --config ./scripts/config.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mmk-es6 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --nolazy --use_strict --harmony ./scripts/buildconf.js && sequelize migration:create   --config ./scripts/config.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mmk-es6
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mmk-es6
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mikbur\OneDrive\Document\Visual Studio 2015\Projects\mmkng\mmkserve\npm-debug.log

_Output, either JSON or SQL_

__Dialect:__sqlite 
__Database version:__ XXX
__Sequelize CLI version:3.0.0-2
__Sequelize version:4.8.3

**Comment by mikbur** [comment]
with 2.8.0 and npm install it works but with yarn it does not and also npm with 3.0.0.-2 does not work

**Comment by sushantdhiman** [comment]
I cant understand your description, please refine

**Comment by mikbur** [comment]
The problem occurs when running "sequelize migration:create --config ./scripts/config.json”.
I recieve the error ”Sequelize [Node: 8.4.0, CLI: 2.8.0, ORM: 4.8.3]
No gulpfile found” and the entire errormessage is all in the first post. I have worked around the issue reinstalling sequelize-cli 2.8.0 using npm after removing sequelize-cli 3.0.0-2.

When I installed 2.8.0 using yarn I had the same problem, maybe that is a clue.

Med vänlig hälsning

Mikkel Burton
tel: 0708-305033

Från: Sushant<mailto:notifications@github.com>
Skickat: den 16 september 2017 09:38
Till: sequelize/cli<mailto:cli@noreply.github.com>
Kopia: Burton Mikkel<mailto:Mikkel.Burton@softronic.se>; Author<mailto:author@noreply.github.com>
Ämne: Re: [sequelize/cli] Error (#538)


Closed #538<https://github.com/sequelize/cli/issues/538>.
