### ISSUE TITLE
FYI: sequelize-cli fails install

### ISSUE THREAD

**Issue by abarcenas29** [sequelize/cli#544]
## What you are doing?
Installing sequelize-cli

## What do you expect to happen?
Should install properly

## What is actually happening?

```
npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/home/rof/.nvm/versions/node/v7.10.1/bin/node" "/home/rof/.nvm/versions/node/v7.10.1/bin/npm" "install" "-g" "sequelize-cli@3.0.0-2"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! path /home/rof/.nvm/versions/node/v7.10.1/lib/node_modules/sequelize-cli/node_modules/js-beautify/js/bin/css-beautify.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/home/rof/.nvm/versions/node/v7.10.1/lib/node_modules/sequelize-cli/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/rof/.nvm/versions/node/v7.10.1/lib/node_modules/sequelize-cli/node_modules/js-beautify/js/bin/css-beautify.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rof/.npm/_logs/2017-09-18T08_35_52_421Z-debug.log
```

This is in relation to one of the dependencies installed. See the relevant ticket on their page.

https://github.com/beautify-web/js-beautify/issues/1247

**Comment by thebarada** [comment]
+1

**Comment by az-esm** [comment]
have same problem just tried to install version sequelize-cli@2.8.0 or upper
C:\temp\qqq>npm install sequelize-cli
qqq@1.0.0 C:\temp\qqq
+-- cli-color@1.2.0  extraneous
+-- fs-extra@4.0.2  extraneous
+-- umzug@2.0.1  extraneous
`-- yargs@8.0.2  extraneous

npm WARN qqq@1.0.0 No description
npm WARN qqq@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sequelize-cli"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! path C:\temp\qqq\node_modules\js-beautify\js\bin\css-beautify.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\temp\qqq\node_modules\js-beautify\js\bin\css-beautify.js'
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\temp\qqq\node_modules\js-beautify\js\bin\css-beautify.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by gerbenmeyer** [comment]
+1, have the same when installing version 3.0.0-3

**Comment by s-connect** [comment]
+1

**Comment by AlexShuraits** [comment]
+1

**Comment by szromek** [comment]
+1

**Comment by irvingswiftj** [comment]
+1

**Comment by aidenwallis** [comment]
+1

**Comment by Kinnza** [comment]
+1

**Comment by bruno-serfe** [comment]
Hi Guys I've this issue using the release 2.8.0 can you take a look and downgrade the js-beautify version to 1.6.14 ?

**Comment by jfreak** [comment]
Try this for now  `npm install -g js-beautify@1.6.14 sequelize-cli`

**Comment by sebastian-serfe** [comment]
+1

**Comment by bruno-serfe** [comment]
@jfreak temporary solution works for now, thanks

**Comment by sushantdhiman** [comment]
New release from https://www.npmjs.com/package/js-beautify should fix this
