### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by sushantdhiman** [sequelize/cli#550]
It should be possible to create enum values from `model:create` command

```bash
$ sequelize model:create --name User --attributes opts:enum(x,y,z)
```

**Comment by JamesTheHacker** [comment]
I attempted to start. One of the problems is the use of commas in the `enum(x,y,z)`. Without some wizardry it's going to be difficult to parse them because attributes are already split using `,`. Also underscore's templates are awful to read/modify.

If you don't mind I'd like to take this one on.

**Comment by wjrjerome** [comment]
Hi @JamesTheHacker 
Any updates on this?

**Comment by Keydex** [comment]
Looking for an update on this as well.

**Comment by cevinlo23** [comment]
Has there been any update on this issue?
