### ISSUE TITLE
No migrations were executed, database schema was already up to date.

### ISSUE THREAD

**Issue by JamesTheHacker** [sequelize/cli#556]
**Versions:** `Sequelize CLI [Node: 8.4.0, CLI: 3.0.0, ORM: 4.10.3]` (I'm aware CLI and ORM may cause strange issues, but in this instance the ORM doesn't have anything to do with the CLI as I'm only running migrations at this stage).

**config.json**

```
{
  "development": {
    "username": "root",
    "password": null,
    "database": "rolledhigh",
    "host": "127.0.0.1",
    "dialect": "mysql"
  },
  "test": {
    "username": "root",
    "password": null,
    "database": "database_test",
    "host": "127.0.0.1",
    "dialect": "mysql"
  },
  "production": {
    "username": "root",
    "password": null,
    "database": "database_production",
    "host": "127.0.0.1",
    "dialect": "mysql"
  }
}
```

**models/image.js**

```
'use strict';
module.exports = (sequelize, DataTypes) => {
  var Image = sequelize.define('Image', {
    public_id: DataTypes.STRING,
    format: DataTypes.STRING,
    name: DataTypes.STRING,
    description: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
        // associations can be defined here
      }
    }
  });
  return Image;
};
```

I run `node_modules/.bin/sequelize db:migrate` the first time and it works. I then run `node_modules/.bin/sequelize db:migrate:undo` and this runs successfully.

But, if I try to run `node_modules/.bin/sequelize db:migrate` again I get the following error:

> No migrations were executed, database schema was already up to date.

It seems there's still a file in `migrations/`. I delete it and regenerate with `node_modules/.bin/sequelize init:migrations`. I then try to run `node_modules/.bin/sequelize db:migrate` again and I get the same error as above.

I've checked the database and the `SequelizeMeta` table is empty:

    mysql> SELECT * FROM SequelizeMeta;
    Empty set (0.00 sec)

With an empty migrations directory, and nothing in the database where is it getting the data from to make a decision on whether or not the migration is up to date?

Any help?

**Comment by JamesTheHacker** [comment]
Wait, I'm closing. I see what I did wrong. `migrations` and `models` are different.

**Comment by AakashPat** [comment]
> > Wait, I'm closing. I see what I did wrong. `migrations` and `models` are different. I was making edits to `models/image.js` thinking it would auto generate the migration file.
> 
> do you mean, we should write the migration file by our self?

Yes. I just did the same when I had to update my models after they had already been migrated once.
Just manually edit the migrations file and you should be good to go!
