### ISSUE TITLE
migration:create reports that it successfully created migrations folder even though it already exists

### ISSUE THREAD

**Issue by gabegorelick** [sequelize/cli#569]
## What you are doing?

I have the following in my `.sequelizerc`:
```js
const path = require('path');

module.exports = {
    'migrations-path': path.resolve(__dirname, 'migrations')
};
```

Running `sequelize migration:create --name foo` reports that it "Successfully created migrations folder at ...", even though the folder already exists.

## What do you expect to happen?
Not output this message. Or output a message about how it's using the existing directory.

## What is actually happening?

Migrations is created correctly, but the log message is misleading.

__Dialect:__ any
__Database version:__ any
__Sequelize CLI version:__ 3.0.0
__Sequelize version:__ 4.13.5

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/cli/pull/592 fixed it, but I would like to keep this open until I add more tests
