### ISSUE TITLE
Can't connect to local MySQL server through socket

### ISSUE THREAD

**Issue by rochapablo** [sequelize/cli#572]
Running drop, create and migrate to reset the entire database.

```js
$ node_modules/.bin/sequelize db:drop
$ node_modules/.bin/sequelize db:create
$ node_modules/.bin/sequelize db:migrate
```

Besides those commands been working, for some reason after restart the macOS, the mysql simply stop working giving me the following message:

```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
```

And to keep it working, I have to [completely remove](https://gist.github.com/vitorbritto/0555879fe4414d18569d) and re-install the mysql.

```
$ brew install mysql
$ brew tap homebrew/services
$ brew services run mysql
``` 

So I would like to know if those ```db:``` commands could be related to this creep problem.

> If I do not execute ```db:...``` and restart the macOS, the mysql will be working.

__Dialect:__ mysql
__Database version:__ 5.7.20
__Sequelize CLI version:__ 3.0.0
__Sequelize version:__ 4.8.0
__macOS Sierra version:__ 10.12.6

**Comment by rebz** [comment]
Did you manage to solve this?

**Comment by rochapablo** [comment]
I can't remember, but now I'm using sequelize-typescript which works pretty well.
