### ISSUE TITLE
host config option seems to be ignored (postgres)

### ISSUE THREAD

**Issue by cblair** [sequelize/cli#575]
## What you are doing?
The docs specify a host config option, but it seems to be ignored when running postgres dialect migrations:

config/config.js
```
{
  "development": {
    "username": "test",
    "password": "test",
    "database": "test",
    "host": "postgres",
    "dialect": "postgres"
  }
}
```
```
./node_modules/.bin/sequelize db:migrate
```

## What do you expect to happen?
I expected a successful migration:
```
Sequelize CLI [Node: 6.11.1, CLI: 3.0.0, ORM: 4.16.1]

WARNING: This version of Sequelize CLI is not fully compatible with Sequelize v4. https://github.com/sequelize/cli#sequelize-support

Loaded configuration file "config/config.json".
{"development":{"url":"postgres://test:test@db:5432/test","database":"test"},"test":{"username":"test","password":"test","database":"test","host":"postgres","dialect":"postgres"}}
Using environment "development".
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators ../node_modules/sequelize/lib/sequelize.js:236:13
== 20171023150718-create-field-definition: migrating =======
== 20171023150718-create-field-definition: migrated (0.107s)

== 20171023151615-create-field-instance: migrating =======
== 20171023151615-create-field-instance: migrated (0.114s)

# echo $?
0
```

## What is actually happening?
```
ERROR: connect ECONNREFUSED 127.0.0.1:5432
```

I did trace the config as far as https://github.com/sequelize/cli/blob/master/src/helpers/config-helper.js#L131, and its the object I would expect from above.

It's worth noting that using `url` instead fixes the issue, which maybe this is the best option for `postgres`.
```
{
  "development": {
    "url": "postgres://test:test@db:5432/test",
    "database": "test"
  }
}
```

Maybe a case of just needing to update the main docs, or linking to the postgres section to clarify that the example getting-started config doesn't work for the postgres config.

__Dialect:__ postgres
__Database version:__ sql (PostgreSQL) 9.6.5
__Sequelize CLI version:__ 3.0.0
__Sequelize version:__ 4.16.1

**Comment by cotterjd** [comment]
This happened to me as well. It completely ignored my host, and I was getting "Access denied" for an IP address they apparently sequelize pulled out of it's ass. Certainly not the IP I specified in the config. But I was using mysql not postgres. 

Thanks for posting the url solution. that worked.
