### ISSUE TITLE
SIGTERM, SIGINT can leave migrations in inconsistent state.

### ISSUE THREAD

**Issue by iamjochem** [sequelize/cli#577]
## What you are doing?
pressing CRTL+C during a migration run (up or down)

```js
// code here
```

## What do you expect to happen?
I expect to not [sometimes] end up with a broken migration state (i.e. a migration was run but not logged in the `sequelize_meta` table.

## What is actually happening?
The script dies immediately so that sometimes the queries in a migration will have been run but not been logged in the `sequelize_meta` table, this results in migrations being completely "stuck".

# What should be happening ...
I think the sequelize command should be trapping exit signals like SIGTERM & SIGINT and at least gracefully finishing off the current migration step (i.e. running the "up" or "down" handler to completion and add/removing the relevant record in the `sequelize_meta` table).

I did some simple tests and merely placing the following near the top of the sequelize-cli bin script mitigates the problem (although it's a bit of a sledgehammer):

```
process.on('SIGTERM', function() {});
process.on('SIGHUP', function() {});
process.on('SIGINT', function() {});
``` 

__Dialect:__ mysql
__Database version:__ 5.7.18
__Sequelize CLI version:__ 2.7.0
__Sequelize version:__ custom fork

**Comment by heisian** [comment]
I don't think there is a workaround for this. `SIGINT` is intended to do exactly that - interrupt the script. If you do that then you are, by definition, interrupting the migration process. It's on you to make sure your migrations are as expected before running them...

**Comment by iamjochem** [comment]
> Scenario: imagine you work in terminals all day then you have lots of them open, one day you accidently hit CTRL+C in the wrong window ... that window happens to running `sequelize-cli`, you mutter something under your breath and restart the process - lo and behold an error occurs, the migrator refuses to run, you spend the next 10 minutes figuring out what is going wrong and manually fixing the state of the DB. then you wish `sequelize-cli` 

the solution is to use a signal handler (of which I gave a most simple example - namely to catch and ignore the signal complete) to gracefully stop "the work", leaving things in a known/working state.

all but 2 POSIX signals can be caught and handled by the process that receives them, only if no handlers are defined for a particular signal will the kernel perform the default handler (i.e. default SIG_INT handler kills the process).

this has nothing to do with my migrations, it has to do with the fact that even if a migration performs only one query (which is either dispatched to MySQL or not) the migrator also performs an auxillary query to update the `sequelize_meta` table - at a minimum 2 queries, if the SIG_INT occurs after a migration query but before the query to update `sequelize_meta` and the process is killed at that point then the migrations are completely broken - it is no longer possible to run either "up" or "down" migrations without first resorting to manually hacking either the DB schema or the content of the `sequelize_meta` table.

> Side Note: *Postgres* allows DDL queries to occur within transactions, I do not know if the migrator uses transactions for *Postgres* but that would mitigate the problem, unfortunately not every datastore (e.g. MySQL) allows for DDL queries in transactions. 

my hacky solution is to simply catch and ignore process signals and let the migrator run it's course - this is acceptable in my case - a cleaner, more user-friendly strategy would bre to catch the signal and then exit the process once the current up or down migration has been performed *and* logged in the `sequelize_meta` table.
