### ISSUE TITLE
(node:4068) fs: re-evaluating native module sources is not supported.

### ISSUE THREAD

**Issue by antrez770** [sequelize/cli#583]
Hi, 
I want use **primo-explore-dom** and **primoUI-central-package** and Installing the dependence 
**$ npm install primo-explore-dom --save-dev**
OS: WINDOWS 10
Node: v6
npm: v3
after that recieve the following **error**:

```
> (node:4068) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
> VIEW_CODE@1.0.0 C:\primo-explore-devenv-master\primo-explore\custom\VIEW_CODE
> └── primo-explore-dom@0.0.10
> 
> npm WARN EPACKAGEJSON VIEW_CODE_DIR@1.0.0 No repository field.
```
If the version of Node or npm should be updated for it? Or any Solutions?
Is there somebody Who Installed the primoUI-central-package? 
Or know about Primo solution "Report Broken Links"?
Thanks.

**Comment by sushantdhiman** [comment]
I dont see how this is related to Sequelize CLI
