### ISSUE TITLE
How do i add a new column & migration?

### ISSUE THREAD

**Issue by joshbedo** [sequelize/cli#586]
Alright i've been searching for hours now and read the documentation multiple times. How can i modify an existing table, add a new column, and create a migration? I have a migration file but my DB isn't updating at all. Ex: Users model, i add a column 'password', new migration, run that migration and now the DB is up to date.

**Comment by joshbedo** [comment]
Figured out i was missing the `queryinterface` methods for adding a column

**Comment by tolerious** [comment]
> Figured out i was missing the `queryinterface` methods for adding a column

should I write a new migration file after addign a new column in model file?
