### ISSUE TITLE
Cannot read property '_' of undefined

### ISSUE THREAD

**Issue by jeffhuys** [sequelize/cli#587]
## What you are doing?
I'm trying to run my Database Seeder on a CI platform. I run the following command:

```bash
node_modules/.bin/sequelize db:seed:all
```

## What do you expect to happen?
As on my local environment, I expect Sequelize to start seeding my database (as defined in config files).

## What is actually happening?
I get the error `Cannot read property '_' of undefined` where the stacktrace is:

```js
/home/ubuntu/housescan.bleeve-servers.com/node_modules/sequelize-cli/lib/sequelize:87
if (!args._[0]) {
          ^

TypeError: Cannot read property '_' of undefined
    at Object.<anonymous> (/home/ubuntu/housescan.bleeve-servers.com/node_modules/sequelize-cli/lib/sequelize:87:11)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
   (...)
```

__Dialect:__ mysql
__Node version:__ 8.9.0
__Database version:__ MySQL 5.7
__Sequelize CLI version:__ 3.0.0
__Sequelize version:__ 4.20.1

Running on CircleCI

It seems like `yargs` is returning an undefined `argv` object.  
My guess would be to change the following:

```js
if (!args._[0]) {
  cli.showHelp();
}
```

to:

```js
if (!args || !args._[0]) {
  cli.showHelp();
}
```

would be enough to fix this.

If any additional information is needed, please, let me know! I could post the seeder and configs and such, but this seems to be a problem in another place than there.

**Comment by jeffhuys** [comment]
After some digging, I see that `yargs` has been updated, and I think that this specific commit: https://github.com/yargs/yargs/commit/a9f03e712a2176d348c34def80d7107adda2ba0e will fix my issue.

**Comment by sushantdhiman** [comment]
Fixed in v5
