### ISSUE TITLE
Bug? db:create cannot set default charset with connection information.

### ISSUE THREAD

**Issue by ALiangLiang** [sequelize/cli#590]
## What you are doing?

```js
// config/config.js
require('dotenv').config()
module.exports = {
  development: {
    username:: process.env.DEV_DB_USER,
    password: process.env.DEV_DB_PASS,
    database: process.env.DEV_DB_NAME, //database_dev
    host: process.env.DEV_DB_HOST,
    dialect: process.env.DEV_DB_TYPE,
    dialectOptions: {
      charset: 'utf8mb4',
      collate: 'utf8mb4_general_ci'
    },
    logging: true
  }
}
```

```bash
$ sequelize db:create --env development
```

## What do you expect to happen?
Create a database with charset in config/config.js
```bash
Executing (default): CREATE DATABASE `database_dev` DEFAULT CHARSET=`utf8mb4 DEFAULT COLLATE=`utf8mb4_general_ci`
```

## What is actually happening?
Doesn't use this configure.
```bash
# log
Executing (default): CREATE DATABASE `database_dev`
```

__Dialect:__ mysql
__Database version:__ 5.7.20
__Sequelize CLI version:__ 3.1.0
__Sequelize version:__ 4.22.15

**Comment by chris-fung** [comment]
Met the same problem with yours. Just need to modify the charset and collate by myself after creating db

**Comment by galki** [comment]
according to [this](https://stackoverflow.com/questions/41666820/node-sequelize-mysql-how-to-define-collation-and-charset-to-models) using `define` instead of `dialectOptions` works when creating a sequelize connection, but it doesn't work when using cli to `db:create`

i also tried to set the charset/collation in the model migration [like the docs say](http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html#instance-method-createTable) by adding the third arg to:
```
queryInterface.createTable(
  tableName,
  { /*... columns*/ },
  { charset: 'utf8' },
)
```
and that results in error:
```
ERROR: Can't create table `mydb`.`mytable` (errno: 150 "Foreign key constraint is incorrectly formed")
```

**Comment by kwbtdisk** [comment]
I avoid this problem by querying `ALTER DATABASE` from a migration file like this:

`/db/migrations/00000-fix-db-charset.js`
```javascript
module.exports = {
  up: (queryInterface, Sequelize) => {
    return Promise.all([
      queryInterface.sequelize.query(
        `ALTER DATABASE ${queryInterface.sequelize.config.database}
        CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;`
      )
    ])
  },
  down: (queryInterface, Sequelize) => { }
}
```

With naming the file like **00000**-xxxxx.js, we can throw the query just before running other migrations.

**Comment by jeanpchr** [comment]
+1

**Comment by perzanko** [comment]
Problem occured for me as well.

**Comment by huangyanyang** [comment]
so finally can I set charset by db:create with config.json now?

**Comment by ALiangLiang** [comment]
@huangyanyang 
You can specify with args. `sequelize db:create --charset <CHARSET>`

**Comment by cupko96** [comment]
> I avoid this problem by querying `ALTER DATABASE` from a migration file like this:
> 
> `/db/migrations/00000-fix-db-charset.js`
> 
> ```js
> module.exports = {
>   up: (queryInterface, Sequelize) => {
>     return queryInterface.sequelize.query(
>         `ALTER DATABASE ${queryInterface.sequelize.config.database}
>         CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;`
>       )
>   },
>   down: (queryInterface, Sequelize) => { }
> }
> ```
> 
> With naming the file like **00000**-xxxxx.js, we can throw the query just before running other migrations.

This solution worked for me. Is there any update on this by sequelize team?

**Comment by abhijeet029** [comment]
add { charset: 'utf8' } in your migration file after the data column object

**Comment by rem711** [comment]
> I avoid this problem by querying `ALTER DATABASE` from a migration file like this:
> 
> `/db/migrations/00000-fix-db-charset.js`
> 
> ```js
> module.exports = {
>   up: (queryInterface, Sequelize) => {
>     return queryInterface.sequelize.query(
>         `ALTER DATABASE ${queryInterface.sequelize.config.database}
>         CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;`
>       )
>   },
>   down: (queryInterface, Sequelize) => { }
> }
> ```
> 
> With naming the file like **00000**-xxxxx.js, we can throw the query just before running other migrations.

It works for me like that, but if someone is still experiencing the same issue, I needed to use back quotes around database name \`${queryInterface.sequelize.config.database}\`  or it throws a syntax error.
