### ISSUE TITLE
sequelize cli version 3 is unable to run migrations due to missing mysql2?

### ISSUE THREAD

**Issue by aprilmintacpineda** [sequelize/cli#609]
## What you are doing?

Trying to run migrations.

## What do you expect to happen?

For it to create the tables.

## What is actually happening?

```
npm run db:migrate

> servcon-backend@0.0.1 db:migrate /Users/me/Documents/projects/mobile-app/backend
> sequelize db:migrate

Sequelize CLI [Node: 8.9.4, CLI: 3.2.0, ORM: 4.31.2]

WARNING: This version of Sequelize CLI is not fully compatible with Sequelize v4. https://github.com/sequelize/cli#sequelize-support

Loaded configuration file "config/sequelize.json".
Using environment "development".

ERROR: Please install mysql2 package manually
```

- Dialect: Mysql
- Database version: mysql  Ver 14.14 Distrib 5.7.20, for macos10.12 (x86_64) using EditLine wrapper
- Sequelize CLI version: 3.2.0
- Sequelize version: 4.31.2

**Comment by aprilmintacpineda** [comment]
Please not that I actually have `mysql2` and `mysql` installed locally, and sequelize-cli installed globally.

**Comment by aprilmintacpineda** [comment]
Finally got it all figured out. I installed `sequelize-cli` globally and `mysql2` locally, so the npm script:

```
"db:migrate": "sequelize db:migrate"
```

looks for the package `mysql2` globally, to fix this, install, do `npm install --save-dev sequelize-cli`, then transform all the scripts to run the locally installed `sequelize-cli` as said in the documentation `node_modules/.bin/sequelize` instead. It worked for me after doing all that.

I also uninstalled `sequelize-cli` globally since it doesn't make sense anymore. Can I get some feedback about this please? I've tried this with other packages, they will always try to find a locally installed dependency first before checking the global scope.

**Comment by tedrob** [comment]
none of these work I still get the same warning, can anyone help?
