### ISSUE TITLE
ERROR: Parameter "url" must be a string, not object

### ISSUE THREAD

**Issue by ferryhinardi** [sequelize/cli#618]
somehow, when i use command `sequelize` (`sequelize db:migrate`, `sequelize db:migrate:undo`, `sequelize db:seed`) always show this. have any idea about this error

<img width="423" alt="screen shot 2018-02-07 at 16 47 27" src="https://user-images.githubusercontent.com/5007428/35914007-48a3e4e6-0c34-11e8-8c4d-f2c82ae79390.png">

**Comment by jacksoncharles** [comment]
I have the same issue. I understand the CLI is not in sync with sequelize hence the issue. I have tried a few fixes but to no avail. Any help is appreciated.

**Comment by ferryhinardi** [comment]
@jacksoncharles i already running with update/use this package
`"mysql2": "^1.5.2"`,
`"sequelize": "4.11.0"`

**Comment by jgentes** [comment]
@andrislusis `npm uninstall sequelize sequelize-cli -g` then `npm i sequelize sequelize-cli -g`

**Comment by developer239** [comment]
How is this still open? 😢

**Comment by developer239** [comment]
You have to have `sequelize` and `sequelize-cli` versions in sync:

```
    "sequelize": "4.38.1",
    "sequelize-cli": "^4.1.1",
```
