### ISSUE TITLE
Fork scaffolding logic into yeoman generator

### ISSUE THREAD

**Issue by maxmalov** [sequelize/cli#62]
Let assume that all migration logic are moved to a separate package to easily create grunt/gulp plugins (#5). But there is also need help with generation configs/models/migrations etc. For example, there is a `generate` script in the RoR world. Scaffolding is out of the tasks related logic there. Most of js developers already use task runner, some part of them is using yeoman generators. Having a third different tool that combines task related and scaffolding logic can make things slightly confusing.

For example, generator could provide the following (assume it named `generator sequelize`):

- this will ask where to store configs, models, migrations and create a structure based on answers:

```bash
yo sequelize
```

- this will create config at the specified location:

```bash
yo sequelize:config
```

and so on. What does you think about that?

**Comment by sdepold** [comment]
I was actually thinking about moving the "core logic" of the cli to another promise based package which is then triggered by the current gulp structure. closing this ticket for now. feel free to re-open it if there is something else to discuss.
