### ISSUE TITLE
ERROR: Parameter "url" must be a string, not object

### ISSUE THREAD

**Issue by connorphill** [sequelize/cli#634]
I am facing a migration command error with v`4.0.0` (`node_modules/.bin/sequelize db:migrate`) that does not provide me with hints on the issue with my configuration. 

Is this due to Sequelize version deprecation `pre-4.0.0` starting with `sequelize-cli` `v2.8.0`?

OR

Is there is a bug with newer versions? I have been using the same cli configuration without issues up until I upgraded to the latest version.

The error message in question is `ERROR: Parameter "url" must be a string, not object`. 

Because of this non-verbose error message I tried installing prior versions to see if the issue was fixed or if the error messages would provide better clues. 

I tried with 3.2.0, but still received the same error above.

2.8.0 also had an error, but provided the clues I was looking for.

```
TypeError: Parameter "url" must be a string, not object
    at Url.parse (url.js:81:11)
    at Object.urlParse [as parse] (url.js:75:13)
    at new Sequelize (/Users/test/Desktop/Projects/node/test-db/node_modules/sequelize/lib/sequelize.js:106:20)
    at getSequelizeInstance (/Users/test/Desktop/Projects/node/test-db/node_modules/sequelize-cli/lib/tasks/db.js:394:12)
    at getMigrator (/Users/test/Desktop/Projects/node/test-db/node_modules/sequelize-cli/lib/tasks/db.js:403:21)
    at Object.task (/Users/test/Desktop/Projects/node/test-db/node_modules/sequelize-cli/lib/tasks/db.js:175:14)
    at /Users/test/Desktop/Projects/node/test-db/node_modules/sequelize-cli/lib/helpers/gulp-helper.js:17:23

```
From this I console logged the expected "url" in Sequelize

 ```
 if (arguments.length === 1 || (arguments.length === 2 && typeof username === 'object')) {
    options = username || {};
    console.log("urlParts Sequelize");
    console.log(arguments);
    console.log("arguments one")
    console.log(arguments[0])
    console.log(url.parse(arguments[0]));

    urlParts = url.parse(arguments[0]);

```

Which outputed and explained why the "url" error appears, but I'm not sure what code has changed in sequelize-cli that is not sending the the object below rather than what I assume should be the database name based on the function argument in the `0` position.

```
urlParts Sequelize
{ '0': 
   { username: 'test',
     password: '',
     database: 'test-db',
     host: '127.0.0.1',
     dialect: 'postgres',
     migrationStorageTableName: 'sequelize_meta',
     autoMigrateOldSchema: true,
     logging: [Function: logMigrator] } }
arguments one
{ username: 'test',
  password: '',
  database: 'test-db',
  host: '127.0.0.1',
  dialect: 'postgres',
  migrationStorageTableName: 'sequelize_meta',
  autoMigrateOldSchema: true,
  logging: [Function: logMigrator] }

```

Finally, When I revert back to `2.7.0` I have success with my migration efforts as I had before.

Could this be a bug?

__Dialect:__ `postgres`
__Database version:__ N/A
__Sequelize CLI version:__ `4.0.0`
__Sequelize version:__ `3.19.2`

**Comment by developer239** [comment]
How is this still open? 😢

**Comment by developer239** [comment]
You have to have `sequelize` and `sequelize-cli` versions in sync:

```
    "sequelize": "4.38.1",
    "sequelize-cli": "^4.1.1",
```

**Comment by connorphill** [comment]
@developer239 thanks for confirming that it is because my Sequelize version needs to be more up to date.
