### ISSUE TITLE
using async config in .sequelizerc

### ISSUE THREAD

**Issue by nishant-dani** [sequelize/cli#637]
## What you are doing?
my config.js file calls calls loadConfiguration to first fetch the db settings from a secure database;  This is an async call, which is resolved on the then ... 
```js
loadConfiguration().then( function(params)
{
    module.exports = {
      development: {
        username: params.sql_username,
        password: params.sql_password,
        database: '...',
        host: params.sql_host,
        dialect: params.sql_dialect,
      },
};
```

## What do you expect to happen?
The sequelize waits for the async to complete before it tries to access the development.dialect.  If I do this synchronously by hardcoding the values without the async call it works.  If there is any workaround that will support an async callout could you let me know.

## What is actually happening?
sequelize executes loadConfiguration but does not wait for the async "resolve - then" to happen, so it fails saying that dialect is not defined.  

Loaded configuration file "..."

ERROR: Dialect needs to be explicitly supplied as of v4.0.0

**Comment by sushantdhiman** [comment]
return the config dont assign it to `module.exports` inside async method, that will never work

**Comment by papb** [comment]
See https://github.com/sequelize/sequelize/issues/11652
