### ISSUE TITLE
sequelize init cannot read .sequelizerc

### ISSUE THREAD

**Issue by fahmifan** [sequelize/cli#640]
## What you are doing?

I want to make .sequelizerc

```js
// .sequelizerc
const path = require('path');

module.export = {
  "config": path.resolve('./server/config', 'config.jsons'),
  "models-path": path.resolve('./server/models'),
  "seeders-path": path.resolve('./server/seeders'),
  "migrations-path": path.resolve('./server/migrations')
}
```
and i run `sequelize init`

## What do you expect to happen?
i expect to get `config models seeders migrations` inside `server` folder

## What is actually happening?
it place the `config models seeders migrations`  outside `server` folder

__Dialect:__ postgres
__Database version:__ 10.3
__Sequelize CLI version:__ 4.0.0
__Sequelize version:__ 4.37.6

**Comment by blankstar85** [comment]
I have the following that is working: 
"models-path": path.resolve('./','server/models'),

**Comment by fahmifan** [comment]
Mine is 8.9.0

**Comment by fahmifan** [comment]
Mine is 8.9.0

**Comment by fahmifan** [comment]
I think it solved

**Comment by LuisHCK** [comment]
Only as a clarification for future reference:
You have a typo
```js
// .sequelizerc
const path = require('path');

Typo ===> module.export = {
  "config": path.resolve('./server/config', 'config.jsons'),
  "models-path": path.resolve('./server/models'),
  "seeders-path": path.resolve('./server/seeders'),
  "migrations-path": path.resolve('./server/migrations')
}
```
it should be module.exports `module.exports`
