### ISSUE TITLE
sequelize-cli creates latin1 by default iso utf-8

### ISSUE THREAD

**Issue by mschipperheyn** [sequelize/cli#642]
I always create my databases in utf-8. . Please make this configurable.

**Comment by sushantdhiman** [comment]
More explanation please, are your talking about SequelizeMeta table?

**Comment by mschipperheyn** [comment]
Hi, no. the Schema itself. I can't seem to get the default collation to be utf-8.

**Comment by sushantdhiman** [comment]
With `db:create / db:drop`, yeah this was discussed before, Sequelize needs to support this first https://github.com/sequelize/cli/pull/591#issuecomment-346768315
