### ISSUE TITLE
Hyphens in model name create syntax error in model template. 

### ISSUE THREAD

**Issue by JoeHartzell** [sequelize/cli#644]
## What you are doing?
I typically like to use "hyphenated" model names when possible. One of the odd behaviors I get when trying to use the Sequelize Cli is the template for the model gets all wonky when you use hyphens in the parameter for the name. For example, running the below command...
```js
sequelize model:create --name foo-bar --attributes id:bigint
```

## What do you expect to happen?
You would expect to get a file with the name foo-bar.js and for the template to have foo-bar in the name for the definition. All while having the actual js be able to be complied. 

## What is actually happening?
This is what the model file looks like after running this command...

```js
'use strict';
module.exports = (sequelize, DataTypes) => {
  var foo - bar = sequelize.define('foo-bar', {
    id: DataTypes.BIGINT
  }, {});
  foo - bar.associate = function(models) {
    // associations can be defined here
  };
  return foo - bar;
};
```
## possible fix 
The issue from what I can see, seems to be in the template. 
The current template looks like this...
```js

'use strict';

module.exports = (sequelize, DataTypes) => {
  var <%= name %> = sequelize.define('<%= name %>', {
    <% attributes.forEach(function(attribute, index) { %>
      <%= attribute.fieldName %>: DataTypes.<%= attribute.dataFunction ? `${attribute.dataFunction.toUpperCase()}(DataTypes.${attribute.dataType.toUpperCase()})` : attribute.dataType.toUpperCase() %>
      <%= (Object.keys(attributes).length - 1) > index ? ',' : '' %>
    <% }) %>
  }, {
    <%= underscored ? 'underscored: true,' : '' %>
  });

  <%= name %>.associate = function(models) {
    // associations can be defined here
  };

  return <%= name %>;
};
```

My proposed fix would be to use the "evaluate" tag instead of the "interpolate" tag for the places where the name is used as a variable. This would allow us to control the rendering of it despite what the name is. For example, 

```js
'use strict';
import { camelCase as _camelCase } from 'lodash';

module.exports = (sequelize, DataTypes) => {
  var <% _camelCase(name) %> = sequelize.define('<%= name %>', {
    <% attributes.forEach(function(attribute, index) { %>
      <%= attribute.fieldName %>: DataTypes.<%= attribute.dataFunction ? `${attribute.dataFunction.toUpperCase()}(DataTypes.${attribute.dataType.toUpperCase()})` : attribute.dataType.toUpperCase() %>
      <%= (Object.keys(attributes).length - 1) > index ? ',' : '' %>
    <% }) %>
  }, {
    <%= underscored ? 'underscored: true,' : '' %>
  });

  <% _camelCase(name) %>.associate = function(models) {
    // associations can be defined here
  };

  return <% _camelCase(name) %>;
};
```

note: I have not actually tested this yet, just wanted to have a solution to go with my issue. 

__Dialect:__ any
__Sequelize CLI version:__ 4.0.0
__Sequelize version:__ 4.37.6

**Comment by sushantdhiman** [comment]
I have considered this bug, it wont be fixed
