### ISSUE TITLE
mysql dialect doues not support creating or dropping functions

### ISSUE THREAD

**Issue by GremeAllanBryce** [sequelize/cli#649]
## What you are doing?
call queryInterface.createFunction() in a migration file to create a new function in the database.  The issue is the same for dropFunction and for create and drop trigger.

The issue appears to be dialect specific.  The issue reported is with mySQL.  As far as I can tell it is implemented for postgress ONLY.

There is no mention in the documentation for limited support.

Perhaps I have a wrong dependency but I am following the docs and AFAIKT have all the required versions

```js
queryInterface.createFunction(
      'demoFunction',
      [{name:'length', type:'smallint', direction:'in'}],
      'VARCHAR(6)',
      'plpgsql',
      "RETURN 1;"
      ))
```

## What do you expect to happen?
I wanted it to create a function

## What is actually happening?
The call returns a error: ERROR: this.QueryGenerator.createFunction is not a function

_Output, either JSON or SQL_

__Dialect:  mysql
__Database version: 5.7
__Sequelize CLI version: 4.0.0
__Sequelize version: 4.37.6

**Comment by sushantdhiman** [comment]
Sequelize doesn;t support createFunction for MySQL, you will need to add support to MySQL dialect first in main repository
