### ISSUE TITLE
Generate Raw SQL Queries for DB migrations

### ISSUE THREAD

**Issue by rcarubbi** [sequelize/cli#653]
Could sequelize cli provide a feature to generate SQL scritp files instead execute migrations?

Something like in Entity Framework: Update-Database -script

It could looks like this: sequelize db:migrate -script

In some companies is forbidden to update a production environment database from sequelize-cli, it have to be done by DBA's with sql scripts

Anyone else with this need?

**Comment by OsoianMarcel** [comment]
It look's similar to my feature: https://github.com/sequelize/cli/issues/656

**Comment by sushantdhiman** [comment]
Duplicate of https://github.com/sequelize/cli/issues/656
