### ISSUE TITLE
Drop Support For Node 4

### ISSUE THREAD

**Issue by rtablada** [sequelize/cli#655]
I know that there was a 4.0 major release fairly recently that dropped 0.12 support for node.

Since April 30th there is no support for Node version 4.

https://medium.com/the-node-js-collection/april-2018-release-updates-from-the-node-js-project-71687e1f7742

Current supported versions are 6, 8, 9, and 10: https://github.com/nodejs/Release#release-schedule

**Comment by rtablada** [comment]
This also means that Babel can be updated to target 6+ instead of 4+.

**Comment by sushantdhiman** [comment]
Lets go straight to Node 8?

**Comment by rtablada** [comment]
Going to 8 unlocks some things but 6 is still in Maintenance LTS until April 2019 so there may be companies still using 6 for a while.
