### ISSUE TITLE
Configuration file not used / loaded

### ISSUE THREAD

**Issue by n4gashi** [sequelize/cli#664]
## What you are doing?

I'm trying to use a custom config file thanks to `.sequelizerc`.  

```js
// .sequelizerc
const path = require('path');

module.exports = {
  'config': path.resolve('config', 'database.js'),
  'models-path': path.resolve('db', 'models'),
  'seeders-path': path.resolve('db', 'seeds'),
  'migrations-path': path.resolve('db', 'migrations'),
}

```

```js
// config/database.js
const globalConfig = {
  username: process.env.DB_USERNAME,
  password: process.env.DB_PASSWORD || null,
  database: process.env.DB_DATABASE,
  host: process.env.DB_HOST,
  dialect: 'postgres',
  define: {
    timestamps: false,
  },
};

module.exports = {
  development: {
    ...globalConfig,
  },
  test: {
    ...globalConfig,
  },
  production: {
    ...globalConfig,
  },
};
```

## What do you expect to happen?

I expect to see my models and migrations created, taking into account every options that I've set in my config file. For this example, I've set `timestamps: false`, so my migrations shouldn't include  `createdAt` / `updatedAt` fields.

## What is actually happening?

Timestamps fields are included into the generated migrations.

SIDE NOTE : I've tried to specify `--config /config/database.js`, didn't seem to work as well (with or without `.sequelizerc`). Using `--debug` flag did not print anything.

```js
// 20180620192248-create-user.js
'use strict';
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('Users', {
      // [...]
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE
      }
    });
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('Users');
  }
};
```

__Dialect:__ postgres
__Sequelize CLI version:__ 4.0.0
__Sequelize version:__ 4.37.10

**Comment by sushantdhiman** [comment]
`define.timestamps` doesn't control generation of `createdAt / updatedAt` in migration generated files, that is just a Sequelize level construct.

I think we can support a option to not generated them at all https://github.com/sequelize/cli/issues/658
