### ISSUE TITLE
Feature request: add attribute key,constraint when model:generate

### ISSUE THREAD

**Issue by phmngocnghia** [sequelize/cli#676]
## What you are doing?
I have
```js
    SubTodo.associate = function(models) {
        const {
          Todo
        } = modules
    
        // associations can be defined here
        SubTodo.belongsTo(Todo)
    };
```

and have this in migrations to work with migration

```js
    TodoId: {
        type: Sequelize.INTEGER,
        reference: {
          model:'Todos',
          key:'id'
        }
  },
```

## What do you expect to happen?
I want it's should have option to automatically link between migrations and models or something like that (Not sync).
I suggest we should have option to specify association when create new model. Support for automatically create associations on model on migration.

```
    sequelize model:generate --name foo --attributes bar:string --belongsTo poo ---belongsToMany fuu[through: lorem]
```

would be make development process more enjoyable.

**Comment by MadeoIT** [comment]
+1
