### ISSUE TITLE
ERROR: Cannot find config.json". Have you run "sequelize init"? While trying to use the config module

### ISSUE THREAD

**Issue by MadeoIT** [sequelize/cli#677]
More a feature than a bug.

## What you are doing?
Trying to configure sequelize with the npm module config, so that my configurations files are cleaner and well organized and I can put sequelize unrelated configuration also in the same files.

`/config
 -development.json
 -test.json
 -production.json`

```
var fs        = require('fs');
var path      = require('path');
var Sequelize = require('sequelize');
var basename  = path.basename(__filename);
var config    = require('config');
var db        = {};

const database = config.get('db.database');
const username = config.get('db.username');
const password = config.get('db.password');
const option = config.get('db');
var sequelize = new Sequelize(database, username, password, option);

fs
  .readdirSync(__dirname)
  .filter(file => {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach(file => {
    var model = sequelize['import'](path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(modelName => {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
```

## What do you expect to happen?
Run the migration normally

## What is actually happening?
`ERROR: Cannot find config.json". Have you run "sequelize init"?`
The sequelize-cli cannot (of course) find my config.json
When I run the express app the database pick up correctly everything and the integration testes are all passing.

__Dialect: postgres
__Database version:__ 10.3
__Sequelize CLI version:__ 4.0.0
__Sequelize version:__4.38.0 
__Node: __9.5.0

Wouldn´t be possible to achieve this? Thanks

**Comment by theptrk** [comment]
I believe when you require something like this `require('config');` it will look to the node_modules and not be relative to your file or project. 

You should require this relative to the location of this file. Something like: 
`require(__dirname + '/../../config/config.js')[env];`

**Comment by euguilhermegirardi** [comment]
I'm having the same issue here. Could you help me?

ERROR: Cannot find "/Users/girardi.gui/config/config.json". Have you run "sequelize init"?

My path is...
const config = require('/../../config/database.js')

And in ".sequelizerc" is:
const path = require('path')
module.exports = {
  config: path.resolve('src', 'config', 'database.js'),
  'models-path': path.resolve('src', 'app', 'models'),
  'seeders-path': path.resolve('src', 'database', 'seeders'),
  'migrations-path': path.resolve('src', 'database', 'migrations')
}
