### ISSUE TITLE
ERROR: null value in column "createdAt" violates not-null constraint

### ISSUE THREAD

**Issue by frederikhors** [sequelize/cli#681]
## What are you doing?
I'm following the tutorial here: http://docs.sequelizejs.com/manual/tutorial/migrations.html#creating-first-model-and-migration-

But when I do:

`node_modules/.bin/sequelize db:seed:all`

it gives to me:

```log
ERROR: null value in column "createdAt" violates not-null constraint
```

I tested in a new `npm init` project with a new Postgres DB 10.4.

__Dialect:__ postgres
__Dialect version:__ "pg": "7.4.3",
__Database version:__ 10.4
__Sequelize version:__ "sequelize": "4.38.0"
__Tested with latest release:__ No

**UPDATE**:

Maybe this is a way to go? http://mmiyauchi.com/?p=2057

**Comment by vapurrmaid** [comment]
simple add them with the current date as following:

```javascript
'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Users', [{
        firstName: 'John',
        lastName: 'Doe',
        email: 'demo@demo.com',
        // add createdAt, updatedAt
        createdAt: new Date(),
        updatedAt: new Date()
      }], {});
  }
};
```

**Comment by frederikhors** [comment]
I found this: https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=it&ie=UTF-8&u=http%3A%2F%2Fmmiyauchi.com%2F%3Fp%3D2057&edit-text=

**Comment by vapurrmaid** [comment]
@frederikhors  I could be wrong, but I haven't seen anywhere demonstrating that `sequelize` handles it for you.

However, you could add a `new Date()` as a default value to the Users schema. In the migration:

```javascript
createdAt: {
  allowNull: false,
  defaultValue: new Date(),
  type: Sequelize.DATE
},
updatedAt: {
  allowNull: false,
  defaultValue: new Date(),
  type: Sequelize.DATE
}
```

**Comment by bingomanatee** [comment]
I found the answer; for some reason createdAt and updatedAt were added to the SequelizeMeta table -- but the migration was adding a record to the SequelizeMeta table without date values and it was THAT query that was breaking the migration.

**Comment by danielrvt** [comment]
@bingomanatee how did you fixed it?

**Comment by bingomanatee** [comment]
I deleted all the tables in my database (including sequelizeMeta) and rebuilt them by running my migrations. 

The key here is that for some reason the timestamps were added to my SequelizeMeta table but Sequelize doesn't expect them to be there so the inserts have no timestamp (createdAt/updatedAt) data, and therefore, fail.

When they were rebuild the sequelizeMeta tables no longer have timestamps and the problem does not occur. I think in retrospect I could have just deleted the sequelizeMeta. Obviously in production you'll want to back up your data first. 

Alternately create a fresh database, run your migrations there, and import your data from your old database, then point your system to the new database.

**Comment by markokosir** [comment]
> @frederikhors I could be wrong, but I haven't seen anywhere demonstrating that `sequelize` handles it for you.
> 
> However **I THINK** (have not tested), you could add a `new Date()` as a default value to the Users schema.
> 
> In the **migration**:
> 
> ```js
> createdAt: {
>   allowNull: false,
>   defaultValue: new Date(),
>   type: Sequelize.DATE
> },
> updatedAt: {
>   allowNull: false,
>   defaultValue: new Date(),
>   type: Sequelize.DATE
> }
> ```

thanks to @vapurrmaid it would be great if you could update your documentation (insreting default values) -  [migrations](http://docs.sequelizejs.com/manual/tutorial/migrations.html), so that not anyone would have to search for the solution.

**Comment by mhdtahawi** [comment]
The timestamps  in the metadata table are probably because of: 
`sequelize db:migrate:schema:timestamps:add `

**Comment by frederikhors** [comment]
nope, @stale.

**Comment by ShaharHD** [comment]
#899 should resolve this once approved and merged.

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/cli/pull/899

**Comment by rifky-rangkuti** [comment]
For v6+

`createdAt: {
        type: Sequelize.DATE,
        allowNull: false,
        defaultValue: Sequelize.NOW,
      }`

**Comment by wzrdx** [comment]
> For v6+
> 
> `createdAt: { type: Sequelize.DATE, allowNull: false, defaultValue: Sequelize.NOW, }`

Issue still exists, I'm using "sequelize-cli": "^6.6.2"
