### ISSUE TITLE
Sequelize-cli compatibility with node flag --experimental-module

### ISSUE THREAD

**Issue by frlinw** [sequelize/cli#683]
## What you are doing?
All my files are .mjs and work with node --experimental-modules
## What do you expect to happen?
Sequelize-cli should allow to specify node specific args like --experimental-modules

## What is actually happening?
`File: migration-file.mjs does not match pattern: /\.js$/`

Sequelize CLI version: 4.0.0

**Comment by frlinw** [comment]
duplicate of https://github.com/sequelize/cli/issues/607 but still relevant

**Comment by clementbmn** [comment]
Any update on it ?

**Comment by frlinw** [comment]
outdated as `--experimental-modules` is enabled by default in node 13+
