### ISSUE TITLE
use_env_variable rejects valid postgres urls

### ISSUE THREAD

**Issue by davidmfoley** [sequelize/cli#71]
The url parsing around lib/tasks/db.js:33 rejects urls has a couple of problems:
1. it rejects some valid urls, for example urls without username/password
2. it fails with a strange message when a URL is rejected:
```
[10:03:30] Starting 'db:migrate'...
[10:03:30] 'db:migrate' errored after 483 μs Cannot read property '6' of null
```

It seems like it might be better to use the [node built-in url module] (http://nodejs.org/docs/latest/api/url.html#url_url_parse_urlstr_parsequerystring_slashesdenotehost) instead of a regular expression for parsing.

**Comment by sdepold** [comment]
Yes this is a good idea!
