### ISSUE TITLE
Latest version of sequelize-cli is incompatible with latest node LTS version (>= 10) due to outdated dependency *upath*

### ISSUE THREAD

**Issue by depene** [sequelize/cli#720]
## What you are doing?

`yarn global add sequelize-cli`

## What do you expect to happen?
Package `sequelize-cli` installed.

## What is actually happening?
```
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.13.0"
error Found incompatible module
```

__Node.js version__ v10.13.0
__Sequelize CLI version:__ 5.3.0

Please update `upath` to latest version

**Comment by SimonSchick** [comment]
`upath` is a dev dependency, not a prod dependency, this should not be impacting you.
Furthermore this appears to have been fixed regardless.
