### ISSUE TITLE
Feature request: accept objects in config file instead of file path

### ISSUE THREAD

**Issue by guidsen** [sequelize/cli#723]
For example when you're using a general config by like this:

```
{
  development: {
    database: { ... },
    queue: { ... },
  },
  ...
}
```

It cannot be used by `sequelize-cli`, without creating another file that maps it to the correct format for the library. Which imo loses flexibility.

```
const config = require('./config');

exports.development = config.development.database;
exports.production = config.production.database;
```

I propose the following: make it able to directly accept a function inside `config` property in the `.sequelizerc` file, like this:

```
const path = require('path');
const config = require('./config');

module.exports = {
  'config':          (environment) => config[environment].database,
  'underscored':     true,
  'migrations-path': path.resolve('', 'migrations'),
  'seeders-path':    path.resolve('', 'seeders'),
}
```

The `environment` parameter is coming directly from the `--env` option. Which looks to be `development` by default.

Thoughts? I'm happy to implement this and create a pull request if this is something that would be accepted as a feature. This way we add a lot of flexibility with low effort.

**Comment by aprilmintacpineda** [comment]
Actually, the config itself could be moved to `.sequelizerc` since it's already a configuration file. Also, please support `sequelize.config.js`on the root not just `.sequelizerc`.
