### ISSUE TITLE
Unable to generate Model

### ISSUE THREAD

**Issue by ThisIsNoZaku** [sequelize/cli#731]
## What you are doing?

Install the CLI per the tutorial here: http://docs.sequelizejs.com/manual/tutorial/migrations.html#the-cli
`npm i -g sequelize-cli`
Initialize
`sequelize init`
Try to generate a new Model
`sequelize model:generate --name NewModel --attributes property:string`

## What do you expect to happen?
A file containing the new model definition is added to the models directory or something like that.

## What is actually happening?
`ERROR: Attribute 'property:string' cannot be parsed: Cannot read property 'STRING' of undefined`

__Dialect:__ mysql
__Database:__ version: 5.7
__Sequelize CLI version:__ 5.6.0
__Sequelize version:__ 2.0.0-beta.0

**Comment by ajbraus** [comment]
+1 inside AWS Cloud9, dialect Postgresql
