### ISSUE TITLE
Generate model with no attributes

### ISSUE THREAD

**Issue by tresdev** [sequelize/cli#732]
Can I generate model with no attributes but default ones,  id, createdAt, updatedAt ? 

I tried 
`sequelize model:generate --name TableName`  and
`sequelize model:generate --name TableName --attributes`  but to no avail.

**Comment by kwasimensah** [comment]
Just ran into this myself. I have a model that for now just has associations with other models while I'm getting the project up and running. Ideally, I wouldn't have to add a dummy attribute to stand this up.
