### ISSUE TITLE
models/index.js doesn't load models in the right order

### ISSUE THREAD

**Issue by mstoetzer** [sequelize/cli#739]
## What you are doing?

I have got the following files in my models folder:

* department.js
* entry.js
* entryStates.js

the following snippet in `models/index.js` returns an array with that order. I added a console.log for printing out the model names:

```js
fs
  .readdirSync(__dirname)
  .filter(file => {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach(file => {
    var model = sequelize['import'](path.join(__dirname, file));
    console.log(model);
    db[model.name] = model;
  });
```
It will print (as expected):

* Department
* Entry
* EntryState

The entry model now includes both models (department and entryStates) in a `default` scope:

```js
Entry.addScope('defaultScope', {
    include: [
      {
        model: sequelize.models.Department,
        attributes: ['displayName'],
      },
      sequelize.models.EntryState,
    ],
  }, { override: true });
```

Entry does have following associations:

```js
Entry.associate = (models) => {
    Entry.belongsTo(models.EntryState);
    Entry.belongsTo(models.Department);
};
```

## What do you expect to happen?

_If I use `findAll` I want to have both department and entryState included:_

```js
Entry.findAll();
```

## What is actually happening?

The include fails.

_I got the following error:_

```js
TypeError: Cannot read property 'getTableName' of undefined
    at Function._validateIncludedElement (project/path/foo/bar/node_modules/sequelize/lib/model.js:465:30)
```

If I console.log inside the Entry model

```js
const Entry = sequelize.define('Entry', {
    ....... // not important here
  });

  Entry.associate = (models) => {
    ....... // not important here
  };

  Entry.addScope('defaultScope', {
    include: [
      {
        model: sequelize.models.Department,
        attributes: ['displayName'],
      },
      sequelize.models.EntryState,
  }, { override: true });

  console.log(sequelize.models);
```

It prints the following:

```js
{ Department: Department, Entry: Entry }
```

As you can see, the entryStates model is not been loaded.

What can I do? What did I wrong?

__Dialect:__ sqlite
__Sequelize CLI version:__ 5.3.0
__Sequelize version:__ 4.42.0

**Comment by dygestor** [comment]
Any update on this issue? I have a similar problem. I'm trying to set up CASCADE delete on a OneToMany association. My model looks like this:

`Story.hasMany(Task)`

Therefore, I have 2 files, story.js and task.js. However, the generated CREATE TABLE query always sets `ON DELETE SET NULL` for the `tasks` table. Renaming the task.js file to anything, which makes it appear before the story.js file (a-r).js will set it correctly to `ON DELETE CASCADE`, all other names (t-z).js will set null.
