### ISSUE TITLE
sequelize model:create --name "Person", but generate "People"

### ISSUE THREAD

**Issue by tsurumure** [sequelize/cli#740]
I run this command: `$ sequelize model:create --name "Person"`， but generate the name "People"

20190121082004-create-person.js
```
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('People', {
```
Even if i change `People` to `Person`, i got some error when i was run: `$ sequelize db:migrate`

```
Unhandled rejection SequelizeDatabaseError: Table 'demodb.people' doesn't exist
```
Is there anyone got the same with me ?

**Comment by KinoshitaShimizu** [comment]
Greetings.

1. Please run `$ sequelize db:migrate:undo` to undo the migration before running it again.

Explanation:
- If the migration has been executed, an entry will be added to your _sequelize table. As long as it is there, running it again will yield no changes. Use `db:migrate:undo` to undo the migration.
- If you manually delete the entry, or delete the table, it may cause problems to do/undo migrations.
- The "do" migration is named "up".
- The "undo" migration is named "down".
- If there is no "down", `db:migrate:undo` will not work.

The model at `models/person.js` is meant to be used for an ORM environment. Please also consider updating it properly.

**Comment by tsurumure** [comment]
Thanks for reply. @KinoshitaShimizu
I found that when i create a name `man`, will change to `men`, so i think that is some kind of rule,
but i still can't found it in the docs.

**Comment by TheDirigible** [comment]
For cli, in models/index.js
`config.freezeTableName = true;`

**Comment by WikiRik** [comment]
Hi! It seems that this issue has been resolved, therefore I will close this. Feel free to comment/reopen if there is still an issue.
