### ISSUE TITLE
Add Column of Array of Enums fails with different erros

### ISSUE THREAD

**Issue by idrisadetunmbi** [sequelize/cli#749]
## What you are doing?
```js
module.exports = {
  up: (queryInterface, Sequelize) =>
    queryInterface.addColumn('table_name', 'newColumnName', {
      type: Sequelize.ARRAY(Sequelize.ENUM('value_1', 'value_2')),
      defaultValue: ['value_1', 'value_2']
    }),

  down: (queryInterface, Sequelize) =>
    queryInterface.removeColumn('table_name', 'newColumnName')
};

```

## What do you expect to happen?
_Migration running_

## What is actually happening?
_Migration Failed with:_

_ERROR: Cannot read property 'getTableName' of undefined_

__Dialect:__ postgres
__Database version:__ 10.1
__Sequelize CLI version:__ 4.0.0
__Sequelize version:__ 5.0.0-beta.13

**Comment by ianberdin** [comment]
Try remove defaultValue.

**Comment by 7hibault** [comment]
> 
> 
> Try remove defaultValue.

This populates the column with `null`, which might not be what we want. When we retrieve data from this table, we probably want to treat every result the same and not have to cast `null` values to empty arrays.
