### ISSUE TITLE
sequelize CLI vs umzug

### ISSUE THREAD

**Issue by dmbrowne** [sequelize/cli#75]
Sequelize 2.0.0-rc4, sequelize-cli 1.0.1

When using the sequelize-cli `db:migrate` command I get a warning that the migration engine is depreciated and will be removed in favour of umzug. From what I understand the main focus of sequelize CLI is migrations,  and upon reading the brief documentation of uzmug in the readme I don't understand how to use it instead of sequelize cli.

Sequelize methods still seems to work in migrations (e.g. `migration.createTable('posts', { \* column definitions *\ } )`)
1. Will these be removed for new uzmug methods?

Migrator is no longer availble from the migration object (e.g. `migration.migrator.sequelize.query('ALTER TABLE posts SET DEFAULT mongo_dB_object_id()')`)
2.  How do I run raw queries in migration?

**Comment by sdepold** [comment]
@dmbrowne need to check if this is still possible. might be that I broke that  behavior by accident.

**Comment by anthonator** [comment]
I was able to do the following:

```js
migration.sequelize.query('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"');
```

**Comment by sdepold** [comment]
@anthonator With CLI 1.x ?

**Comment by anthonator** [comment]
@sdepold Yep!

**Comment by anthonator** [comment]
My complete migration:

```js
module.exports = {
  up: function(migration, DataTypes, done) {
    migration.sequelize.query('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"');

    done();
  },

  down: function(migration, DataTypes, done) {
    migration.sequelize.query('DROP EXTENSION IF EXISTS "uuid-ossp"');

    done();
  }
};
```

**Comment by sdepold** [comment]
ah cool. good to know.

**Comment by dmbrowne** [comment]
Yup. Great migration.sequelize.query() works
:shipit:
