### ISSUE TITLE
Ignore file in migrations folder

### ISSUE THREAD

**Issue by jasonbronson** [sequelize/cli#756]
Would be great to able to ignore README.md in the migrations folder from the configuration file.

**Comment by alexcoroza** [comment]
> Would be great to able to ignore README.md in the migrations folder from the configuration file.

Any updates on this one?

**Comment by vincentdesmares** [comment]
Also useful for other helpful files like .eslintrc.json. This should be configurable.

**Comment by FlyingPumba** [comment]
Is there any way to workaround this issue? I also have a `.eslintrc.json` file inside my migrations folder, and its breaking the `sequelize db:migrate` command.

**Comment by dfyz011** [comment]
Any updates?

**Comment by WikiRik** [comment]
No updates on this. I tried to reproduce it on #1114 but wasn't able to. If you have a reproducible example for this, we can look into this further.

See #1113 for some comments we had about this earlier
