### ISSUE TITLE
Status of the CLI regarding sequelize v5

### ISSUE THREAD

**Issue by papb** [sequelize/cli#761]
Is `sequelize-cli` up-to-date with Sequelize v5?

I would like to help a bit with the CLI, especially with documentation, I think a first important step is to clarify both readmes (`sequelize` and `sequelize-cli`) with the answer to the above question and further instructions.

Thanks in advance :)

**Comment by trappar** [comment]
I'm super confused about the state of these two projects. I go to the V5 docs and there's conflicting information all over (between sequelize and sequelize-cli). Code examples don't show where imported variables are coming from, and the official CLI generates models in the "legacy" way - which is barely even mentioned in the docs.

Maybe it makes sense to someone who knows the internals really well but to a new user Sequelize is a nightmare right now. If you can help sort out the documentation I'm sure it would be super helpful for people like me.

**Comment by papb** [comment]
@trappar Thanks for the comment. I am a fan of clear documentation, and I feel your pain. I will try to help. The problem is: although I've been using sequelize a lot in the last year, and even made a few slight contributions to sequelize, I haven't really used the CLI in the last year. So I am a bit lost on the status, hence the question.

But I will investigate :grimacing: and will do soon, hopefully!

**Comment by eugene-matvejev** [comment]
i think it would be good, to release new CLI and/or sequlize when one of them is to ready for release :) so they can sync versions :) and it will be easier to understand that you use right version
these guys: https://symfony.com/ do exactly this :)

**Comment by slidenerd** [comment]
Oh! so thats the problem! Holy cow i was wondering why CLI s generating ES5 model classes while the docs talk about ES6,

**Comment by papb** [comment]
Hi everyone, I am aware of the problems with the CLI, stay tuned!!
