### ISSUE TITLE
JSON the right format for config?

### ISSUE THREAD

**Issue by anthonator** [sequelize/cli#77]
Is JSON the right format for the config? The only reason I ask is because I generally pull production config from ENV. You fine people have done a good job making this thing customizable so I wouldn't be surprised if you have something for this and I'm not seeing it.

**Comment by leehankyeol** [comment]
For anyone who might be lost like me...

If you're using [dotenv](https://www.npmjs.com/package/dotenv), you should require it in `config.js`.

````js
const dotenv = require('dotenv').config();

module.exports = {
  development: {
    database: process.env.DB_NAME,
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    dialect: 'mysql',
    define: {
      underscored: true
    },
  },
}
````

**Comment by mcranston18** [comment]
For anyone wondering why `sequelize -c my_config.js` doesn't work, the syntax has been updated. Use this instead `sequelize --config my_config.js`

**Comment by JWTappert** [comment]
Is the `--config` option not supported in sequelize-cli v4?

**Comment by noodlebreak** [comment]
There is no `config.js` in my installation. Is this to be manually written? I have an automatically created `models/index.js` when I ran `sequelie init`.

**Comment by Nastromo** [comment]
Current version of sequelize-cli supports config.JS by default. All you have to do is write your config.js as this:

```
require('dotenv').config();

module.exports = {
    dev: {
        username: process.env.DB_USER,
        password: process.env.DB_PASS,
        database: process.env.DB_NAME,
        host: process.env.DB_HOST,
        dialect: 'mysql'
    },
    "production": {
        "username": process.env.DB_USER,
        "password": process.env.DB_PASS,
        "database": process.env.DB_NAME,
        "host": process.env.DB_HOST,
        "dialect": "mysql"
    }
}
```
