### ISSUE TITLE
Fix npm audit Sensitive Data Exposure

### ISSUE THREAD

**Issue by raisaanjani92** [sequelize/cli#774]
## What you are doing?
I install sequelize-cli 5.4.0 and run npm audit

## What do you expect to happen?
0 vulnerabilities

## What is actually happening?
found 1 low severity vulnerability in 478275 scanned packages
1 vulnerability requires manual review. See the full report for details.
https://www.npmjs.com/advisories/825

__Dialect:__ mysql
__Database version:__ 5.7
__Sequelize CLI version:__ 5.4.0
__Sequelize version:__ 4.41.0

**Comment by SONGJIHYOEK** [comment]
cannot use sequelize-cli. Because of this problem.

**Comment by papb** [comment]
@SimonSchick did merging #722 fix this?

**Comment by phipag** [comment]
Same Problem here. Still persists.

**Comment by SimonSchick** [comment]
The owner of the package is unreachable, I cannot do anything until @sushantdhiman shows up.

**Comment by sushantdhiman** [comment]
Sorry for all the delay, I just released new version which got all related commits https://www.npmjs.com/package/sequelize-cli/v/5.5.0

I have requested an update in NPM advisory. I'll close this issue when status is updated
