### ISSUE TITLE
Is underscored: true option supported?

### ISSUE THREAD

**Issue by finnishprince** [sequelize/cli#78]
I'm trying to generate model User with it's migration. My config looks like this:

    {
        "development": {
            "host"     : "...",
            "database" : "...",
            "define"   : {
                "underscored": true
            },
            "dialect"  : "postgres",
            "port"     : "5432",
            ...
        },
        ...
    }

From project root I launch:

`node_modules/sequelize-cli/bin/sequelize model:generate --name User --attributes email:string,name:string,hash:string,salt:string`

After this I get `coffee/models/user.coffee`:

    "use strict"
    module.exports = (sequelize, DataTypes) ->
      User = sequelize.define("User",
        email: DataTypes.STRING
        name: DataTypes.STRING
        hash: DataTypes.STRING
        salt: DataTypes.STRING
      ,
        classMethods:
          associate: (models) ->
      )
  
      # associations can be defined here
      User
      
And `coffee/migrations/20150107142601-create-user.coffee`:

    "use strict"
    module.exports =
      up: (migration, DataTypes, done) ->
        migration.createTable("Users",
          id:
            allowNull: false
            autoIncrement: true
            primaryKey: true
            type: DataTypes.INTEGER

          email:
            type: DataTypes.STRING

          name:
            type: DataTypes.STRING

          hash:
            type: DataTypes.STRING

          salt:
            type: DataTypes.STRING

          createdAt:
            allowNull: false
            type: DataTypes.DATE

          updatedAt:
            allowNull: false
            type: DataTypes.DATE
        ).done done
        return

      down: (migration, DataTypes, done) ->
        migration.dropTable("users").done done
        return
        
Is it supposed migration file to create fields `createdAt` and `updatedAt` despite `underscored` option set to `true`? It seems migration file should contain smth like:

    created_at:
      allowNull: false
      type: DataTypes.DATE

    updated_at:
      allowNull: false
      type: DataTypes.DATE
      
and model one:

    ...
    hash: DataTypes.STRING
    salt: DataTypes.STRING
    createdAt:
      field: "created_at"
    updatedAt:
      field: "updated_at"
  
Is `underscored` option not yet supported in cli or I'm just doing something wrong?

Thank you.

**Comment by finnishprince** [comment]
Not sure, if it's important, but:

    $ cat .sequelizerc
    
    var path = require('path')
    module.exports = {
      'config': path.resolve('config', 'db-config.json'),
      'migrations-path': path.resolve('coffee', 'migrations'),
      'models-path': path.resolve('coffee', 'models'),
      'coffee': true
    }

**Comment by sdepold** [comment]
Did the config file ever evaluated that underscored option? I'm more or less sure it didn't. So this is more of a missing feature than a bug or something like this :)

**Comment by sdepold** [comment]
So to answer your question: No this is currently not supported

**Comment by finnishprince** [comment]
Thank you. Just to clarify, could you provide some explanation about usage of this option? Where and how should it be applied?

**Comment by finnishprince** [comment]
Got it myself, thank you)

**Comment by paulofaria** [comment]
I'd love to have support for this on the configuration file.
