### ISSUE TITLE
Sequelize Undo All ERROR: Could not find migration method: down

### ISSUE THREAD

**Issue by jerrychong25** [sequelize/cli#784]
## What you are doing?
I would like to undo migration all models from my project. However, it failed to undo for some projects.

```js
sequelize db:migrate:undo:all
```

## What do you expect to happen?
Undo migration all models from project successfully.

## What is actually happening?
```
macusers-MacBook:node-express-postgres-passport User$ sequelize db:migrate:undo --name 20190513150715-create-user.js

Sequelize CLI [Node: 11.14.0, CLI: 5.4.0, ORM: 4.41.2]

Loaded configuration file "config/config.json".
Using environment "development".
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13
== 20190513150715-create-user: reverting =======

ERROR: Could not find migration method: down

```

__Dialect:__ postgres
__Database version:__ 11.2
__Sequelize CLI version:__ 5.4.0
__Sequelize version:__ 4.41.2

Could anyone advise on this?

Thanks.

**Comment by jerrychong25** [comment]
Fixed this issue.

It is due to missing mode/xxx.js file.

**Comment by ngocducedu** [comment]
> Fixed this issue.
> 
> It is due to missing mode/xxx.js file.

I got same your issues. Can you tell me what is your  mode you are missing ? Thanks!

**Comment by jerrychong25** [comment]
> 
> 
> > Fixed this issue.
> > It is due to missing mode/xxx.js file.
> 
> I got same your issues. Can you tell me what is your mode you are missing ? Thanks!

Sorry, cant recall which exact file is missing now.
