### ISSUE TITLE
Seed bulkinsert requires createdAt, updatedAt by default (not documented)

### ISSUE THREAD

**Issue by izznogooood** [sequelize/cli#790]
## What you are doing?
Creating seeds for cli created models.

```js
'use strict';

module.exports = {
    up: (queryInterface, Sequelize) => {
        /*
      Add altering commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.bulkInsert('People', [{
        name: 'John Doe',
        isBetaMember: false
      }], {});
    */
        return queryInterface.bulkInsert(
            'Languages',
            [
                {
                    id: 1,
                    name: 'english',
                    createdAt: new Date(),
                    updatedAt: new Date()
                },
                {
                    id: 2,
                    name: 'norwegian',
                    createdAt: new Date(),
                    updatedAt: new Date()
                }
            ],
            {}
        );
    },
    
    down: (queryInterface, Sequelize) => {
        /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.bulkDelete('People', null, {});
    */
    }
};
```

## What do you expect to happen?
Expeted to work like the examples (without createdAt, updatedAt)

## What is actually happening?
Need createdAt, updatedAt.

_Output, either JSON or SQL_

__Dialect:__ sqlite / postgres 
__Database version:__ 3 / 10.3 
__Sequelize CLI version:__ 5.4.0
__Sequelize version:__ 5.8.7

## Suggestion
If you want I could update the docs to reflect this? 
/ or
Take a stab at adding this automatically.

**Comment by eugene-matvejev** [comment]
when you define models, you can use `timestamps: false,` may be that is what you are looking for?
https://github.com/eugene-matvejev/node-js-battleship/pull/1

**Comment by izznogooood** [comment]
Yes and no, I found that option later. Adding the timestamps to the documentation would save me the troubleshooting when following the documentation.

**Comment by ShaharHD** [comment]
#899 should resolve this once approved.

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/cli/pull/899
