### ISSUE TITLE
config file in production

### ISSUE THREAD

**Issue by mchicote** [sequelize/cli#80]
Hi
I'm wondering how can I run migrations on a production environment without using the config.json file. I don't want to write my credentials there in plain text.

Thanks
Marcos

**Comment by sdepold** [comment]
Would env vars be an options?

**Comment by mchicote** [comment]
Sure.

**Comment by sdepold** [comment]
There was quite some related discussion here: https://github.com/sequelize/cli/issues/77

tldr is:

You can configure your configuration file to point an environment to a specific environment variable, which is supposed to contain a database URL:

```
{
  "production": {
    "use_env_variable": "DB_HOST"
  }
}
```

In that case the CLI will load the env var `DB_HOST` and throw it into the url module to parse it. Credentials can be passed as well.

**Comment by mchicote** [comment]
Great. Thanks.

**Comment by bbnnt** [comment]
hope I'm not bothering coming by here; as for now this is not obvious

You then need to have two files to handle the configuration ( default sequelize.json, then some config.js than can parse environments variables) ? Or maybe 3 ( a something.js that declares which environments variables can be parsed via `use_env_variable` — according to #77) ?
