### ISSUE TITLE
how to add some additional sequelize options..??

### ISSUE THREAD

**Issue by kiyoshinyobee** [sequelize/cli#806]
## What you are doing?

i try to add some sequelize additional options like `freezeTableName: true` or `timestamps: false` to options of sequlizeCLI. i try insert in `options-path` or `.sequelizerc`.

```js
module.exports = {
  'config': path.resolve('db', 'config/db.js'),
  'options-path': path.resolve('db', 'config/options.js'),
  'models-path': path.resolve('db', 'models'),
  'seeders-path': path.resolve('db', 'seeders'),
  'migrations-path': path.resolve('db', 'migrations'),
  'underscored': true,
}
```

## What do you expect to happen?
i want add some sequelize option like `freezeTableName: true` or `timestamps: false` or else options. 

## What is actually happening?
showing error `Unknown arguments/options: timestamps, freezeTableName` 

__Dialect: postgres
__Database version: 11.0
__Sequelize CLI version: 5.5.0
__Sequelize version: 5.13.1

**Comment by madsonic** [comment]
Look at the example
https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor

**Comment by kiyoshinyobee** [comment]
i still get error with `Unknown arguments/options: define`
