### ISSUE TITLE
bug - running migration requires config.json

### ISSUE THREAD

**Issue by radzk** [sequelize/cli#807]
even though I remove all occurences from index.js and the config.json itself (I dont want to use it) the sequelize db:migrate throws `ERROR: Cannot find "/Applications/AMPPS/www/wedding-api/config/config.json". Have you run "sequelize init"?`

Sequelize CLI [Node: 10.2.1, CLI: 5.5.0, ORM: 5.15.0]

**Comment by AzorianMatt** [comment]
I recently encountered this issue, and came to realize that it was a bad assumption, which you also appear to have made. I realize this is an old issue, but for others finding this along the way, hope this helps>

The connection instance set up in `models/index.js`is not actually used by the migration process. That is just template code for use with the model files it generates.

The migration process seems to rely solely on the configuration in the `config/config.json` file.

From a devops perspective, this is not ideal, so I'm seeking a non intrusive way to remove this requirement, such as a different path of instantiation.
