### ISSUE TITLE
db:drop should not fail if not exists

### ISSUE THREAD

**Issue by edgedemon** [sequelize/cli#840]
## What you are doing?
when i run the command sequelize db:drop and the database does not exist, i get an error.

## What do you expect to happen?
the command to be ignored as there was no database to delete

## Issue insight
The error is due to the command being used without the "IF EXISTS" clause, despite this clause being common to all providers who support db:drop on the first place Mysql, Postgres and MSSql

to fix this we only need to change the /src/commands/database.js from this
```js
 await sequelize.query(`DROP DATABASE ${sequelize.getQueryInterface().quoteIdentifier(config.database)}`, {
        type: sequelize.QueryTypes.RAW
      }).catch(e => helpers.view.error(e));

```js

to this 
```js
 await sequelize.query(`DROP DATABASE IF EXISTS ${sequelize.getQueryInterface().quoteIdentifier(config.database)}`, {
        type: sequelize.QueryTypes.RAW
      }).catch(e => helpers.view.error(e));
```

**Comment by papb** [comment]
Thanks for the report!

**Comment by JSRossiter** [comment]
I encountered the same issue, glad to see it's already been fixed, but it hasn't been included in a release yet, could it be?

**Comment by ezegon** [comment]
> I encountered the same issue, glad to see it's already been fixed, but it hasn't been included in a release yet, could it be?

I'm still having the same issue. I had to replace the string in my Dockerfile to use the command.
