### ISSUE TITLE
Run Specific migration file

### ISSUE THREAD

**Issue by sujeet-agrahari** [sequelize/cli#860]
I can undo a specific migration file using `sequelize db:migrate:undo --name migration_file_name`.
I wonder why there is no option to migration just specific migration file?
Why below doesn't work?
`sequelize db:migrate --name migration_file_name`
It's just common sense everyone will go to this If they found out the method to undo a specific migration.

**Comment by FeezyHendrix** [comment]
Hi, Has this been done?

**Comment by muhyidin3222** [comment]
not yet done?, i can't run command above.

**Comment by Aaron46** [comment]
I know this is late - I do see the CLI has a `--from` and a `--to` option which can be used for this purpose
```Options:
...
  --to               Migration name to run migrations until                                                           [string]
  --from             Migration name to start migrations from (excluding)                                              [string]```

**Comment by remarkablemark** [comment]
See #1034
