### ISSUE TITLE
Node 13.x is not supported

### ISSUE THREAD

**Issue by frlinw** [sequelize/cli#861]
## What you are doing?
Nodejs 13.x enable esm module by default https://nodejs.org/api/esm.html

```
> npx sequelize --options-path ./.sequelizerc.js db:migrate:undo:all && npx sequelize --options-path ./.sequelizerc.js db:migrate

Must use import to load ES Module: d:\...\.sequelizerc.js
require() of ES modules is not supported.
require() of d:\...\.sequelizerc.js from d:\...\node_modules\sequelize-cli\lib\core\yargs.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename .sequelizerc.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from d:\...\package.json.
```

So I rename `.sequelizerc.js` to `.sequelizerc.cjs` and change all migration files extension to `.cjs` and get:

```
File: 00001-MyModel-createTable.cjs does not match pattern: /\.js$/
```

## What do you expect to happen?
Do not force cjs module, things should just work with esm modules.

## What is actually happening?
esm modules are not supported

**Comment by frlinw** [comment]
Node 8 is end of life so Node 10 is the current active LTS and dynamic import was introduced in Node 9.7.
So with a major version bump, it could be possible to just replace `require()` by `import()`

**Comment by NaumanZahid** [comment]
Whats the status of this? Anybody working on it?

**Comment by jmeintjes** [comment]
Another solution could be to change the pattern to accept .cjs files as well. Seems like people ran into the same problem with TypeScript at some point. I managed to work around the problem following [this](https://gist.github.com/andrewmunro/030f0bf62453239c495b0347c8cd1247). Installing the babel-core package and adding `require("babel-core/register");` to my config.cjs file did the trick for me. 

Not necessarily the most elegant solution but it unblocked me.

**Comment by frlinw** [comment]
https://github.com/sequelize/cli/pull/905 will fix it, partially.

**Comment by frlinw** [comment]
And Node 12 is the current Active LTS

**Comment by al-mahi** [comment]
Is there any fix for this issue so far. Having similar issue while running the command npx sequelize db:migrate. Using Node 14 with  "sequelize": "^6.6.2","sequelize-cli": "^6.2.0"

**Comment by MaxiSantos** [comment]
https://sequelize.org/master/manual/migrations.html check for babel
