### ISSUE TITLE
Easy way to select and update values on migration

### ISSUE THREAD

**Issue by gaprl** [sequelize/cli#862]
Let's suppose I have a model `User` with the following schema:

``` javascript
{
  addressStreet: DataTypes.STRING,
  addressCity: DataTypes.STRING,
  addressState: DataTypes.STRING,
  addressZip: DataTypes.STRING
}
```

And I'd like to change it to:

``` javascript
{
  address: { type: DataTypes.STRING, allowNull: false },
}
```

Ok. All good. I'll just create a migration to create and drop the columns.

The problem is, I need to migrate the data from the old schema to the new one. It may be a stupid question or maybe I am just missing a step here but is there an easy way of doing it instead of creating SELECT/UPDATE queries with `queryInterface.sequelize.query`?

I could load the model `User` and use it's `findAll` function but at the time the migration is running all the old fields (addressStreet, addressCity, etc) are not accessible anymore. :(

I'd be glad if anyone can give me some light on this. Thanks in advance!

_Edit: @nichdiekuh had a similar problem about a year ago with sequelize/sequelize#2050. I was wondering if by now we have a better solution._

**Comment by ajbraus** [comment]
This is the clean answer: https://ajbraus.github.io/sequelize-it/#/?id=data-migrations

**Comment by ephys** [comment]
@ajbraus In your example, there is no need for the array return. This is enough:

```typescript
// DATA MIGRATION

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.addColumn('Order', 'address', {
      type: Sequelize.STRING(150),
      defaultValue: ''
    }),
    await queryInterface.sequelize.query(
      'UPDATE Order SET address = CONCAT( addressOne, " ", addressTwo, " ", city, ", ", state, " ", zip );'
    ),

    // remove unused fields
    await queryInterface.removeColumn('Order', 'addressOne'),
    await queryInterface.removeColumn('Order', 'addressTwo'),
    await queryInterface.removeColumn('Order', 'city'),
    await queryInterface.removeColumn('Order', 'state'),
    await queryInterface.removeColumn('Order', 'zip')
  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.dropTable('users');
    */
  }
};
```

Not that I think speed is super important in one-shot migration files, but some of these operations can be done in parallel with `Promise.all`
