### ISSUE TITLE
Inconsistent init behavior?

### ISSUE THREAD

**Issue by denizdogan** [sequelize/cli#87]
So this just happened...

    d:\myapp\myapp>node_modules\.bin\sequelize init
    
    Sequelize [Node: 0.10.34, CLI: 1.0.6, ORM: 2.0.0-rc8]
    
    Created 'config\config.json'
    Successfully created migrations folder at 'd:\myapp\myapp\migrations'.
    Successfully created models folder at 'd:\myapp\myapp\models'.
    Loaded configuration file 'config\config.json'.
    Using environment 'development'.
    The file d:\myapp\myapp\models\index.js already exists. Run 'sequelize init --force'to overwrite it.
    
    d:\myapp\myapp>node_modules\.bin\sequelize init --farce
    
    Sequelize [Node: 0.10.34, CLI: 1.0.6, ORM: 2.0.0-rc8, mysql: ^2.5.4]
    
    Loaded configuration file 'config\config.json'.

    d:\myapp\myapp>

Now I'm not really sure what's going on. I passed **`--farce`** (notice the typo) but I don't get the warning about the `--force` argument to overwrite index.js this time. I also don't get any error about the unrecognized command line argument `--farce`.

Obviously, index.js wasn't overwritten by `--farce`, I understand that, but I feel like something could be done to improve this.

**Comment by sdepold** [comment]
Huh, that is indeed interesting :D Will debug it. Not sure when though.

**Comment by sdepold** [comment]
So that is what i get on my machine:

```
node_modules/.bin/sequelize init --farce

Sequelize [Node: 0.10.35, CLI: 1.0.6, ORM: 2.0.0-rc8]

Loaded configuration file 'config/config.json'.
Using environment 'development'.
The file config/config.json already exists. Run 'sequelize init --force'to overwrite it.
```

**Comment by denizdogan** [comment]
@sdepold: I can't seem to reproduce the behavior in a fresh environment either. Maybe it was just a fluke!

**Comment by sdepold** [comment]
Weird :D I'm closing this ticket for now. Feel free to re-open it once the issue happens again :)
