### ISSUE TITLE
Sequelize async config

### ISSUE THREAD

**Issue by MatteoGioioso** [sequelize/cli#877]
## What you are doing?
according to these issues: #668 and #637 and to this line of code: https://github.com/sequelize/cli/blob/master/src/helpers/config-helper.js#L117, looks like async configuration is possible.
However I could not find anything from the docs, I have been trying something as well, but without any success 

```js
const getConfig = async () => {
  const credentials = await getDbCredentials();
  const { password, username, dbname, engine, host, port } = credentials;

  return {
    development: {
      username,
      password,
      database: dbname,
      host,
      port,
      dialect: engine,
    },
  };
};

const sequelize = new Sequelize(getConfig());
```
I have been trying as well by returning a plain object with the config but nothing. I always got: ` throw new Error('Dialect needs to be explicitly supplied as of v4.0.0');
`
## What do you expect to happen?
No errors? If this feature actually exists

## What is actually happening?
error: `throw new Error('Dialect needs to be explicitly supplied as of v4.0.0');`

Dialect: postgres 
Sequelize version: 5.19.2
Node version: 10

**Comment by MatteoGioioso** [comment]
ummm...Looks like that only would works for the `cli` is that right?

**Comment by papb** [comment]
See https://github.com/sequelize/sequelize/issues/11652
