### ISSUE TITLE
Feature Request: Support for db:reset

### ISSUE THREAD

**Issue by slifty** [sequelize/cli#881]
### Is your feature request related to a problem? Please describe.
I often want to "wipe out" my test database, dropping all tables and re-running migrations.  I don't want to have to drop the database itself.

### Describe the solution you'd like
Ideally the sequelize CLI would provide a `db:reset` option which drops all tables, runs migrations, and (optionally?) runs seeds.

### Why should this be in Sequelize CLI
db:reset is a feature of some comparable tools (e.g. rake's db:migrate:reset), which makes it feel like it is probably a reasonably scoped feature for the CLI.

### Describe alternatives/workarounds you've considered
The closest existing feature to this that I have found is the CLI's `db:migrate:undo:all`

This doesn't quite fit my use case since it goes through each migration and reverts.  This represents time and computation that is wasted (which is problematic for something like automated tests which we want to keep as lean as possible).

`db:drop` and `db:create` don't work in my specific dialect, but I also am concerned that they would require a level of DB permission that I don't want to grant my tests.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by slifty** [comment]
Note: the dialect was simply being ignored (#907).

However, I still would prefer to be able to reset without running as a user with DBCREATE permission.

**Comment by fivaz** [comment]
Actually you can achive this by running ***npx sequelize-cli db:migrate:undo:all && npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all***

you can add this to your scripts in your package.json file

    "db:refresh": "npx sequelize-cli db:migrate:undo:all && npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all" 
    
and so you can run this command by doing **npm run db:refresh** in the console

**Comment by WikiRik** [comment]
I agree with the suggestion of @fivaz 
Also, it seems that [rake's db:migrate:reset](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/railties/databases.rake#L185) also drops and creates the database.
I do not really see the need of a new command, especially since it should not be an issue to drop and create test databases in my opinion. Since a workaround has been mentioned, I will close this issue. Feel free to comment if you think you still want this to be a feature
