### ISSUE TITLE
How can I execute --url option

### ISSUE THREAD

**Issue by MJunaidAhmad** [sequelize/cli#890]
How can i execute this command through umzug: 
![image](https://user-images.githubusercontent.com/12229238/80972125-2991fc00-8e37-11ea-9157-acac48f1bcd1.png)

Thanks in advance!

**Comment by WikiRik** [comment]
You should be able to instantiate sequelize with a URL like;
`const sequelize = new Sequelize('mysql://user:pass@example.com:9821/dbname');`
