### ISSUE TITLE
sequelize.import is deprecated and still used in the generated code by the cli

### ISSUE THREAD

**Issue by yahyanouali** [sequelize/cli#895]
In the sequelize manual it's marked that sequelize.import is deprecated and we should use just require instead : https://sequelize.org/master/manual/models-definition.html

But the code generated by sequelize-cli is still using it : 
```js
fs.readdirSync(__dirname)`
  .filter((file) => {
    return (
      file.indexOf(".") !== 0 && file !== basename && file.slice(-3) === ".js"
    );
  })
  .forEach((file) => {
    const model = sequelize["import"](path.join(__dirname, file));
    db[model.name] = model;
  });
```

__Dialect:__ any
__Database version:__ all
__Sequelize CLI version:__ all
__Sequelize version:__ all

**Comment by papb** [comment]
This is awful. Thanks for the report.

**Comment by papb** [comment]
For now this means that the CLI is not compatible with sequelize@next yes. Users of CLI will have to stick with v5 for now. Rest assured that v6 will not leave beta without this issue fixed.

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/cli/pull/901
