### ISSUE TITLE
sequelize db:create and sequelize db:migrate - no output/db not created/updated

### ISSUE THREAD

**Issue by thecpdubguy** [sequelize/cli#896]
## What you are doing?
I have a postgres server being ran as a docker image (default docker postgres image)
Trying to create a DB and run all migrations, I get no output indicating anything happened or went wrong. DB was not created, and no tables/migrations appeared.

As far as I can tell, configurations are identical (except for credentials and db name) to another test environment I have working fine using sequelize - not quite sure how to debug this

```bash
± |master U:5 ?:1 ✗| → npx sequelize db:create

Sequelize CLI [Node: 14.2.0, CLI: 5.5.0, ORM: 5.21.10]

Loaded configuration file "config/config.js".
Using environment "development".
```
and 
```bash
± |master U:5 ?:1 ✗| → npx sequelize db:migrate

Sequelize CLI [Node: 14.2.0, CLI: 5.5.0, ORM: 5.21.10]

Loaded configuration file "config/config.js".
Using environment "development".
```

## What do you expect to happen?
DB created and migrations ran

## What is actually happening?
Output indicates loaded config properly, database unaffected.

Full output
```bash
Sequelize CLI [Node: 14.2.0, CLI: 5.5.0, ORM: 5.21.10]

Loaded configuration file "config/config.js".
Using environment "development".
```

__Dialect:__ postgres
__Database version:__  12.3
__Sequelize CLI version:__ 5.5.0
__Sequelize version:__ 5.21.10

PS, I also posted similar message in slack, no response, just trying to figure out how to debug this. https://sequelize.slack.com/archives/C0CELV3N1/p1589913992139300

**Comment by thecpdubguy** [comment]
Related to #889 maybe?

**Comment by georgeevans1995** [comment]
@thecpdubguy Thanks for posting the issue about it only working with PG > 8 this cost me a day debugging as there is absolutely no error given, and your post finally resolved it for me. 

I also found that it appears to be related to node versions. Node V12 appears to work with pg v7 and below, but Node V14 only works with pg v8 and above
