### ISSUE TITLE
[Update README] Node 14.x is not supported- Please mention last supported node version or throw error instead of silent exit

### ISSUE THREAD

**Issue by khaledbnmohamed** [sequelize/cli#897]
## What you are doing?
trying to run normal migrations after updating to node 14.3.0
```bash
npx sequelize-cli db:migrate
```

## What do you expect to happen?
something similar to 
![image](https://user-images.githubusercontent.com/34178030/82769858-a7459800-9e36-11ea-8beb-1c62787bba6e.png)
or throw any unsupported exception
## What is actually happening?

```
Sequelize CLI [Node: 12.16.3, CLI: 5.5.1, ORM: 5.21.2]

Loaded configuration file "database/config/config.js".
Using environment "development".
```

__Dialect:_postgres
__Database version:__ 11.0
__Sequelize CLI version:__ 5.5.1
__Sequelize version:__ 5.21.2

**Comment by vitorecomp** [comment]
Looks like the same problem of the sequelize package: 
https://github.com/sequelize/sequelize/issues/12158
Solved with a update of the pg version.

**Comment by papb** [comment]
Thanks @vitorecomp! @khaledbnmohamed Can you let us know if updating pg fixes your issue?

**Comment by khaledbnmohamed** [comment]
> Thanks @vitorecomp! @khaledbnmohamed Can you let us know if updating pg fixes your issue?

I actually downgraded node back again to 12.16.3 no solve this issue. I guess I'll the solution you gave a try when I upgrade again. Thanks for your help I'll close it for now as It seems that your solution will be working ( hopefully :D )
