### ISSUE TITLE
Custom Config file for db connection

### ISSUE THREAD

**Issue by zohaib-novaturesol** [sequelize/cli#902]
I have existing project in which I am adding sequelize migrations etc.

Sequeize required to create config/config.json for the db details. But my project already config files. So, i want the way to use existing config files for the db details as well. 

Please guide about the flow how i can do this.

@jjulian @adamhooper @appleboy @wwalser @dantman

**Comment by dlyakin** [comment]
You can use another json file. Look at .sequelizerc file on link https://sequelize.org/master/manual/migrations.html

**Comment by WikiRik** [comment]
As @dlyakin mentioned you can indeed change the location of the config in the .sequelizerc file; https://sequelize.org/master/manual/migrations.html#the--code--sequelizerc--code--file
