### ISSUE TITLE
Notice: Issues will be disabled soon

### ISSUE THREAD

**Issue by sushantdhiman** [sequelize/cli#912]
Hey Everyone,

Recently I have pushed some changes in this repository to prepare it for `v6`, also took care of some old issues. You can find more details in [CHANGELOG.md](https://github.com/sequelize/cli/blob/master/CHANGELOG.md)

Maintaining this repository along with main ORM library is bit much, I often disable notifications for various repositories. This leads to increase in number of unattended issues and PRs. Within these large number of issues, most are low quality "help me" issues & a few are good quality issues.

Whenever I get chance I try to come back and merge PR(s), answer issues and update code to revive CLI project once again :)
To reduce my maintenance overhead, I plan to switch this repository to only accept PRs. I think this will also improve quality of issues reported (in the form of PR with tests).

Thanks!

**Comment by papb** [comment]
I've brought issues back.
