### ISSUE TITLE
Better logging for db:migrate

### ISSUE THREAD

**Issue by alubbe** [sequelize/cli#92]
Using db:migrate feels a little bit like a black box - you cannot tell whether no migrations were run (schema is already up2date) or it just ran any amount of new migrations. I prefer ActiveRecord's logging that tells me about each migration that just ran and even what they did.

I think a great start would be to print the name of the run migrations instead of exiting here https://github.com/sequelize/cli/blob/master/lib/tasks/db.js#L34
Then, the methods (add/remove tables, columns, index, etc.) could also print what they just did and we'd have a complete picture.

What do you think?

**Comment by sdepold** [comment]
Makes a lot of sense to me :) I think that the logging of the specific commands might be a bit complicated though.

**Comment by bulkan** [comment]
@sdepold this is done now :)

**Comment by sdepold** [comment]
Cool :)
