### ISSUE TITLE
sequelize-cli: running single seed file is slow

### ISSUE THREAD

**Issue by jasonmng** [sequelize/cli#943]
When I run all the seeds with `sequelize-cli db:seed:all` the command will finish running in under a second. However, if I try to run a single seed file with `sequelize-cli db:seed --seed {file}` it'll take about 10 seconds to run. The terminal output shows me that the seed finishes "migrating" in under .5 seconds but it then just hangs for the other 9.5 seconds.

## What you are doing?
sequelize-cli db:seed --seed {file}

## What do you expect to happen?
I expect the above command to finish quickly, under 1 second

## What is actually happening?
The seeding/migration finishes but the command hangs for about 10 seconds

__Dialect:__ mariadb
__Sequelize CLI version: 6.2.0
__Sequelize version:__ 6.3.5

**Comment by miguelci** [comment]
Also having issues with this. Any idea when the pr will be merged?
