### ISSUE TITLE
help command ought to short circuit other commands

### ISSUE THREAD

**Issue by prashtx** [sequelize/cli#95]
I inadvertently typed `sequelize help db:migrate` instead of `sequelize help:db:migrate`. The CLI ran both the help command and the migration command. I can see this causing problems for folks, especially if they hard-code config values in `config/config.json` rather use than environment variables (with the latter, I can run `sequelize help` without any database specified. For a safer demonstration of the effect, you can use `sequelize help migration:create`.

I bet the multiple tasks are a feature of gulp rather than a bug, but it would be great for the CLI to short-circuit other tasks when one of them is `help`, or at least when the first one is `help`.

**Comment by sdepold** [comment]
hm. I can totally see your point. so here is thing: while my gulp fanboy-ism slowly decreases, I was considering rewriting the CLI a bit to no longer use gulp. on the other hand it's also not too bad. anyways, one way to fix that issue would be a hack here: https://github.com/sequelize/cli/blob/master/bin/sequelize 

We could use yargs to read the task names and remove all but help, if there is help and something else.

**Comment by sushantdhiman** [comment]
Latest v3.0 is just yargs, short-circuit should not be possible now
