### ISSUE TITLE
Can you please update the resolve package to latest.

### ISSUE THREAD

**Issue by prashant93** [sequelize/cli#952]
![image](https://user-images.githubusercontent.com/4151470/123756294-67bf6a00-d8da-11eb-85a2-12a5b6074902.png)

this resolve package update will help to fix issue with path-parse vulnerability

**Comment by sitvanit** [comment]
Hi, we also have the same issue, our Whitesource scan alerts path-parse version should be 1.0.7. we consume the package just through sequelize-cli. Can you please upgrade the "resolve" package in order to fix it?
