### ISSUE TITLE
Can't require inside migrations file

### ISSUE THREAD

**Issue by Gricardov** [sequelize/cli#958]
## What you are doing?
Hi sequelize team!
I'm trying to reuse a model in a migrations file. However, when I add a require, I get this error:

ERROR: Cannot destructure property 'username' of 'config[(intermediate value)]' as it is undefined.

It happens on any file required.

```js
const dotenv = require("dotenv");
dotenv.config();

module.exports = {
  up: (queryInterface, Sequelize) => {
    const db = require('../models');
    return queryInterface.createTable('events', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
    });
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('events');
  }
};
```

## What do you expect to happen?
I want to be able to require any file I need

## What is actually happening?
I get the error

_Output, either JSON or SQL_

__Dialect:__ mysql
__Database version:__ 10.4.19-MariaDB
__Sequelize CLI version:__ ^6.2.0
__Sequelize version:__ ^6.6.5

**Comment by jooohny** [comment]
I think this is because `sequelize-cli` runs migration files in `sequelize` module not in your app itself. So, it can're resolve path to your `node-modules` and require `dotenv`. Try creating absolute path with `path` module.

**Comment by WikiRik** [comment]
Hi @Gricardov, did the suggestion above of using the `path` module solve your problem?

**Comment by Gricardov** [comment]
Hi chamo! Thanks for your response. I don't know if the solution works because 4 months have passed and I ended up using another solution

**Comment by WikiRik** [comment]
Then I'll close this issue for now. People can still comment on it if they experience the same problems
