### ISSUE TITLE
Sequelize-cli does not connect to the database

### ISSUE THREAD

**Issue by c0mrade** [sequelize/cli#969]
## What you are doing?
Trying to create a database with sequelize-cli on the AWS RDS and have my app connect to the same database. Note that I can connect to my database from this machine using `psql` so it's not a networking issue. 

I don't know if this is relevant but I'm running my app in the Kubernetes cluster and I had tried to connect my app to both PostgreSQL Kubernetes pod as well as to the AWS RDS, yielding the same results.

I created a new nodejs project and added this to .sequelizerc:
```js
const path = require('path');

module.exports = {
  "config": path.resolve('./src/config', 'sequelize.js'),
  "models-path": path.resolve('./src/models'),
  "seeders-path": path.resolve('./src/seeders'),
  "migrations-path": path.resolve('./src/migrations')
};
```

## What do you expect to happen?
I expect my database to be created and for my app to consume the database connection.

## What is actually happening?
The database does not get created and the app fails to run.

Here is what is happening when I try to create a database initially:

```
npx sequelize-cli db:create

Sequelize CLI [Node: 16.11.1, CLI: 6.2.0, ORM: 6.6.5]

Loaded configuration file "src/config/sequelize.js".
Using environment "development".

ERROR: getaddrinfo ENOTFOUND dev-rds-api.xxx.us-east-1.rds.amazonaws.com


npm notice
npm notice New minor version of npm available! 8.0.0 -> 8.1.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.1.1
npm notice Run npm install -g npm@8.1.1 to update!
npm notice
```

I can get the database to get created by passing in the connection string:

```
npx sequelize-cli db:create --url 'postgres://postgres:aaaaaa!@dev-rds-api.xxx.us-east-1.rds.amazonaws.com/web-api'

Sequelize CLI [Node: 16.11.1, CLI: 6.2.0, ORM: 6.6.5]

Parsed url postgres://postgres:*****@dev-rds-api.xxx.us-east-1.rds.amazonaws.com/web-app
Database web-app created.
```

This is what happens when my app tries to boot up:

```
yarn run v1.22.15
$ cross-env NODE_ENV=development nodemon src/index.js
[nodemon] 2.0.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node src/index.js`
error: SequelizeHostNotFoundError: getaddrinfo ENOTFOUND dev-rds-api.xxx.us-east-1.rds.amazonaws.com

    at Client._connectionCallback (/usr/src/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:175:24)
    at Client._handleErrorWhileConnecting (/usr/src/app/node_modules/pg/lib/client.js:305:19)
    at Client._handleErrorEvent (/usr/src/app/node_modules/pg/lib/client.js:315:19)
    at Connection.emit (node:events:390:28)
    at Socket.reportStreamError (/usr/src/app/node_modules/pg/lib/connection.js:52:12)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[nodemon] app crashed - waiting for file changes before starting...
```

_Output, either JSON or SQL_

__Dialect: postgres
__Database version: PostgreSQL 13.3 on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-6), 64-bit
__Sequelize CLI version: 6.2.0
__Sequelize version: 6.6.5

**Comment by eternaltyro** [comment]
After having faced this same issue a million times in non kubernetes contexts, I dunno why I didn't think to check for newlines. Did `echo <bad_base64> | base64 -d | tr -d \\n | base64` to fix the values. Thanks @c0mrade !
