### ISSUE TITLE
Exits with code "1" all the time

### ISSUE THREAD

**Issue by grabbou** [sequelize/cli#97]
sequelize migrate:db exits with code 1 all the time making it impossible to use as a "prestart" script with NPM.

**Comment by sdepold** [comment]
hm that's bad. let me check

**Comment by sdepold** [comment]
```
node_modules/.bin/sequelize db:migrate

Sequelize [Node: 0.10.35, CLI: 1.2.0, ORM: 2.0.0]

Loaded configuration file 'config/config.json'.
Using environment 'development'.
 sdepold@barfooz-20  ~/Projects/tmp  echo $?
0
```

works on my machine. Can you tell a bit more about the dirty details of your project? :D

**Comment by grabbou** [comment]
Hah, sure @sdepold. I believe it might be related to the fact I am trying to run it from a nested directory (I have models/migrations/config inside src while having package.json on a root level). 

If it works for you - I'll try to do some additional debugging. Let's put it on hold now. I'll be migrating additional data over the weekend again so I will have yet another opportunity to test it out.

**Comment by sdepold** [comment]
Just re-open this ticket when you have further information

**Comment by grabbou** [comment]
Yeah, looks like it might have been my issue. No worries, sorry for false report. Since then, everything runs flawlessly while migrating during npm pre-start.
