### ISSUE TITLE
Regular Expression Denial of Service vulnerability in the ansi-regex package in versions < 6.0.1

### ISSUE THREAD

**Issue by prashant93** [sequelize/cli#970]
sequelize-cli@6.2.0
| +-- cli-color@1.4.0
| | `-- ansi-regex@2.1.1
| `-- yargs@13.3.2
|   +-- cliui@5.0.0
|   | `-- strip-ansi@5.2.0
|   |   `-- ansi-regex@4.1.0
|   `-- string-width@3.1.0
|     `-- strip-ansi@5.2.0
|       `-- ansi-regex@4.1.0

Can Sequelize-cli team check on this
There's a Regular Expression Denial of Service vulnerability in the ansi-regex package in versions < 6.0.1: https://app.snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908

Can you please update the  cli-color and yargs they have fixed the issue

**Comment by prashant93** [comment]
@sdepold Any update

**Comment by prashant93** [comment]
-- sequelize-cli@6.2.0
  +-- cli-color@1.4.0
  | `-- ansi-regex@2.1.1
  `-- yargs@13.3.2
    +-- cliui@5.0.0
    | `-- strip-ansi@5.2.0
    |   `-- ansi-regex@4.1.0
    `-- string-width@3.1.0
      `-- strip-ansi@5.2.0
        `-- ansi-regex@4.1.0

Seqeulize CLI using vulenrable package

**Comment by fncolon** [comment]
Hello, already ping core members to handle this. Please kindly wait.

**Comment by sdepold** [comment]
sorry for the mess. the issue was long fixed in master already but it seems that no new version was released ever since 🤦

**Comment by sdepold** [comment]
fixed in 6.3.0

**Comment by prashant93** [comment]
@fncolon @sdepold  waiting for new version 6.3.0. Thanks for the fix.

**Comment by prashant93** [comment]
Thanks @sdepold @fncolon for fixing the vulnerability .
