### ISSUE TITLE
I can't migrate a specific file

### ISSUE THREAD

**Issue by MetalDz** [sequelize/cli#973]
<!--

__Dialect:__ mysql 
__Database version:__ 2.3.2
__Sequelize CLI version:__ 6.3.0
__Sequelize version:__ 6.8.0

There is no command to migrate a specific File, spacialy when you use foreign key,
/* The Commande 
$ npx sequelize db:migrate

Sequelize CLI [Node: 14.18.1, CLI: 6.3.0, ORM: 6.8.0]

Loaded configuration file "config\config.js".
Using environment "development".
== 20211026164839-create-user: migrating =======

ERROR: Can't create table `db_elfares`.`users` (errno: 150 "Foreign key constraint is incorrectly formed")
*/
i Had to rename the user, migrate the (Teams) Model, the rename the user again than migrate it, to get it done

**Comment by MetalDz** [comment]
$ npx sequelize db:migrate

Sequelize CLI [Node: 14.18.1, CLI: 6.3.0, ORM: 6.8.0]

Loaded configuration file "config\config.js".
Using environment "development".
== 20211026164839-create-user: migrating =======

ERROR: Can't create table `db_elfares`.`users` (errno: 150 "Foreign key constraint is incorrectly formed")
//
There is no command to migrate a specific File, spacialy when you use foreign key,

**Comment by WikiRik** [comment]
Hi,

Do you want help with only migrating one file or do you want help with the error message you are getting?

**Comment by MetalDz** [comment]
hi, thank for the help
i  want help with only migrating on one file

**Comment by WikiRik** [comment]
Unfortunately, there is not a command for running single migrations. But there is a workaround.
The `db:migrate` function supports two options `--from` and `--to`. 
The from option takes the migration filename to start migrations from (excluding) and the to option takes the migration filename to run migrations until.

Using both of them should allow you to run one specific migration.

**Comment by WikiRik** [comment]
Hi @MetalDz was my answer satisfactory? Or do you need assistance with anything else?

**Comment by MetalDz** [comment]
what's up @WikiRik, Thank u bro, it was helpful, i hope sequelize developers get this as a feedback to improve the product More.

**Comment by WikiRik** [comment]
Yes, I have put #659 on a project board so the feature request is noted. Thanks!
