### ISSUE TITLE
Dynamic configuration problem

### ISSUE THREAD

**Issue by Notr0M** [sequelize/cli#986]
## What you are doing?

```js
npx sequelize-cli init
```

## What do you expect to happen?
_I expected sequelize-cli load my custom config file however it tries to overwrite it_

## What is actually happening?
_.sequelizerc has been added at the root level_

```js
// .sequelizerc
const path = require('path');

module.exports = {
  'config': path.resolve('db', 'config.js')
}
```

Output,

![err](https://user-images.githubusercontent.com/39002414/147366610-27cec7f8-ef12-448c-ba1d-607e1b5ef04b.jpg)

Is that possible to load custom config during initialization not afterwards?

__Dialect:__ mysql
__Database version:__ 8.0.23
__Sequelize CLI version:__ 6.3.0
__Sequelize version:__ 6.12.2
__node version:__ 10.24.1

**Comment by ephys** [comment]
`sequelize init` is a bootstrapping command that will try to generated files like `.sequelizerc`. it might not be the command you want to use. What are you trying to do?

**Comment by Notr0M** [comment]
What I wanted to do was to create a custom config file based on `.sequelizerc` file so I don't have to change `config.js` manually.
In fact, the problem was how my project has been implemented so I had to run the `sequelize init` command frequently.

Thanks
